import { WIND_BDG_GRAPH_TYPE, WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE, GRAPH_MENU_TYPE } from '../types'

// 需要映射到API的菜单类型
export type GraphMenuTypeWithApi =
  | GRAPH_MENU_TYPE.SUSPECTED_RELATION
  | GRAPH_MENU_TYPE.RELATION_QUERY
  | GRAPH_MENU_TYPE.MULTI_TO_ONE
  | GRAPH_MENU_TYPE.ACCOUNTING_STANDARDS
  | GRAPH_MENU_TYPE.SSSE_RULES
  | GRAPH_MENU_TYPE.SZSE_RULES
  | GRAPH_MENU_TYPE.CBIRC_RULES
  | GRAPH_MENU_TYPE.BENEFICIARY_OWNER
  | GRAPH_MENU_TYPE.BENEFICIARY_PERSON
  | GRAPH_MENU_TYPE.BENEFICIARY_ORG
  | GRAPH_MENU_TYPE.ACTUAL_CONTROLLER

// 菜单类型到API类型的映射
export const WIND_BDG_GRAPH_MENU_TO_TYPE: Record<GraphMenuTypeWithApi, WIND_BDG_GRAPH_TYPE> = {
  [GRAPH_MENU_TYPE.SUSPECTED_RELATION]: WIND_BDG_GRAPH_TYPE.SuspectedRelationChart,
  [GRAPH_MENU_TYPE.RELATION_QUERY]: WIND_BDG_GRAPH_TYPE.RelationQueryChart,
  [GRAPH_MENU_TYPE.MULTI_TO_ONE]: WIND_BDG_GRAPH_TYPE.MultiToOneChart,
  [GRAPH_MENU_TYPE.ACCOUNTING_STANDARDS]: WIND_BDG_GRAPH_TYPE.RelatedPartyChart,
  [GRAPH_MENU_TYPE.SSSE_RULES]: WIND_BDG_GRAPH_TYPE.RelatedPartyChart,
  [GRAPH_MENU_TYPE.SZSE_RULES]: WIND_BDG_GRAPH_TYPE.RelatedPartyChart,
  [GRAPH_MENU_TYPE.CBIRC_RULES]: WIND_BDG_GRAPH_TYPE.RelatedPartyChart,
  [GRAPH_MENU_TYPE.BENEFICIARY_OWNER]: WIND_BDG_GRAPH_TYPE.BeneficiaryChart,
  [GRAPH_MENU_TYPE.BENEFICIARY_PERSON]: WIND_BDG_GRAPH_TYPE.BeneficiaryChart,
  [GRAPH_MENU_TYPE.BENEFICIARY_ORG]: WIND_BDG_GRAPH_TYPE.BeneficiaryChart,
  [GRAPH_MENU_TYPE.ACTUAL_CONTROLLER]: WIND_BDG_GRAPH_TYPE.ActualControllerChart,
} as const

//关联关系图谱API类型
export const RELATE_CHART_API_TYPE = {
  [GRAPH_MENU_TYPE.ACCOUNTING_STANDARDS]: 4, // 企业会计准则
  [GRAPH_MENU_TYPE.SSSE_RULES]: 2, // 上交所规则
  [GRAPH_MENU_TYPE.SZSE_RULES]: 3, // 深交所规则
  [GRAPH_MENU_TYPE.CBIRC_RULES]: 5, //银保监规则
} as const

// 操作区按钮
export const OPERATOR_RIGHT_MENU_LIST = [
  WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE.SaveImage,
  WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE.Restore,
  WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE.Size,
  // WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE.ExportReport,
  // WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE.RemoveWaterMark,
] as WIND_BDG_GRAPH_OPERATOR_RIGHT_TYPE[]

// 样例企业
export const AIGRAPH_DEFAULT_COMPANY_CODE = '1015343518'
export const AIGRAPH_DEFAULT_COMPANY_NAME = '融创房地产集团有限公司'
