import { corpDetailShareholderCfg } from '@/handle/corpModuleCfg'
import { corpDetailMainMember } from '@/handle/corpModuleCfg/base/mainMember'
import intl from '@/utils/intl'
import { ICorpMenuModuleCfg } from '../type'

export const overviewConfig: ICorpMenuModuleCfg = {
  title: intl('138663', '基础信息'),
  showList: [
    'showCompanyInfo',
    'HKCorpInfo',
    'showIndustry',
    'showActualController',
    'showShareholder',
    'showVietnamIndustry',
    'showShareSearch',
    'getShareAndInvest',
    'showshareholderchange',
    'showCompanyBranchInfo',
    'showControllerCompany',
    'showDirectInvestment',
    'structuralEntities',
    'showFinalBeneficiary',
    'showMainMemberInfo',
    'showCoreTeam',
    'showGroupSystem',
    'showHeadOffice',
    'getcomparable',
    'showCompanyChange',
    'gettaxpayer',
    'showCompanyNotice',
    'showYearReport',
  ],
  showName: [
    intl('138588', ' 工商信息 '),
    intl(414513, '公司资料'),
    intl('449235', '所属行业/产业'),
    intl('13270', '实际控制人'),
    intl('138506', ' 股东信息 '),
    intl('24413', '所属行业'), // 只有越南国家才有
    intl('228894', ' 股东穿透 '),
    intl('138279', ' 股权穿透图 '),
    intl('451218', ' 股东变更 '),
    intl('138183', ' 分支机构 '),
    intl('451208', ' 控股企业 '),
    intl('138724', ' 对外投资 '),
    intl('410253', ' 结构性主体 '),
    intl('138180', ' 最终受益人 '),
    intl('138503', ' 主要人员 '),
    intl('204943', ' 核心团队'),
    intl('148622', ' 集团系 '),
    intl('204942', ' 总公司 '),
    intl('138219', ' 竞争对手 '),
    intl('451225', ' 工商变更 '),
    intl('222479', '纳税人信息'),
    intl('222474', '企业公示'),
    intl('138149', ' 企业年报 '),
  ],
  numArr: [
    true,
    'hkUnlisted',
    'industryCount',
    ['actualcontrollerPublishCount', 'actualcontrollerCalcCount'],
    corpDetailShareholderCfg.modelNum,
    'vietnamCorpIndustryNum',
    true,
    true,
    'shareholder_change_num',
    'new_branch_num',
    'e_holdingEnterprise_count',
    'foreign_invest_num',
    'structuralEntityCount',
    ['beneficialOwner', 'beneficialNaturalPerson', 'beneficialInstitutions'],
    corpDetailMainMember.modelNum,
    'coreteam_num',
    ['group_main_num', 'group_membercorp_num'],
    'headerquarters_num',
    'competitor',
    'change_record_num',
    'tax_payer_num',
    ['share_change_num', 'shareholder_contribution_num'],
    'annual_num',
  ],
}
