// 数字经济核心产业
export const globalElectronEconomy = [
  {
    code: '8914977652',
    level: 1,
    name: '数字产品服务业',
    nameEn: 'Digital product service industry',
    node: [
      {
        code: '8914977400',
        level: 2,
        name: '数字产品租赁',
        nameEn: 'Digital product leasing',
        node: [
          { code: '8914977401', level: 3, name: '音像制品出租', nameEn: 'Audio-visual rental', node: [] },
          {
            code: '8914977657',
            level: 3,
            name: '计算机及通讯设备经营租赁',
            nameEn: 'Computer and communication equipment operating leasing',
            node: [],
          },
        ],
      },
      {
        code: '8914977403',
        level: 2,
        name: '其他数字产品服务业',
        nameEn: 'Other digital products and services',
        node: [],
      },
      {
        code: '8914977658',
        level: 2,
        name: '数字产品维修',
        nameEn: 'Digital product repair',
        node: [
          {
            code: '8914977402',
            level: 3,
            name: '计算机和辅助设备修理',
            nameEn: 'Repair of computers and auxiliary equipment',
            node: [],
          },
          { code: '8914977659', level: 3, name: '通讯设备修理', nameEn: 'Repair of communication equipment', node: [] },
        ],
      },
      {
        code: '8914977396',
        level: 2,
        name: '数字产品批发',
        nameEn: 'Wholesale of digital products',
        node: [
          {
            code: '8914977653',
            level: 3,
            name: '计算机、软件及辅助设备批发',
            nameEn: 'Wholesale of computers, software and auxiliary equipment',
            node: [],
          },
          {
            code: '8914977654',
            level: 3,
            name: '广播影视设备批发',
            nameEn: 'Wholesale of radio, film and television equipment',
            node: [],
          },
          { code: '8914977397', level: 3, name: '通讯设备批发', nameEn: 'Communication equipment wholesale', node: [] },
        ],
      },
      {
        code: '8914977398',
        level: 2,
        name: '数字产品零售',
        nameEn: 'Digital product retail',
        node: [
          {
            code: '8914977655',
            level: 3,
            name: '计算机、软件及辅助设备零售',
            nameEn: 'Retail sale of computers, software and ancillary equipment',
            node: [],
          },
          {
            code: '8914977656',
            level: 3,
            name: '音像制品、电子和数字出版物零售',
            nameEn: 'Retail sale of audio-visual products, electronic and digital publications',
            node: [],
          },
          { code: '8914977399', level: 3, name: '通信设备零售', nameEn: 'Retail of communication equipment', node: [] },
        ],
      },
    ],
  },
  {
    code: '8914977660',
    level: 1,
    name: '数字技术应用业',
    nameEn: 'Digital technology application industry',
    node: [
      {
        code: '8914977404',
        level: 2,
        name: '软件开发',
        nameEn: 'Software development',
        node: [
          { code: '8914977405', level: 3, name: '支撑软件开发', nameEn: 'Support software development', node: [] },
          { code: '8914977406', level: 3, name: '其他软件开发', nameEn: 'Other software development', node: [] },
          { code: '8914977661', level: 3, name: '基础软件开发', nameEn: 'Basic software development', node: [] },
          { code: '8914977662', level: 3, name: '应用软件开发', nameEn: 'Application software development', node: [] },
        ],
      },
      {
        code: '8914977663',
        level: 2,
        name: '电信、广播电视和卫星传输服务',
        nameEn: 'Telecommunications, radio and television and satellite transmission services',
        node: [
          { code: '8914977407', level: 3, name: '电信', nameEn: 'telecommunications', node: [] },
          { code: '8914977408', level: 3, name: '卫星传输服务', nameEn: 'Satellite transmission services', node: [] },
          {
            code: '8914977664',
            level: 3,
            name: '广播电视传输服务',
            nameEn: 'Broadcast and television transmission services',
            node: [],
          },
        ],
      },
      {
        code: '8914977674',
        level: 2,
        name: '其他数字技术应用业',
        nameEn: 'Other digital technology applications',
        node: [
          {
            code: '8914977418',
            level: 3,
            name: '三维（3D）打印技术推广服务',
            nameEn: 'Three Dimensional (3D) Print technology promotion services',
            node: [],
          },
          {
            code: '8914977675',
            level: 3,
            name: '其他未列明数字技术应用业',
            nameEn: 'Other digital technology application industries not specified',
            node: [],
          },
        ],
      },
      {
        code: '8914977665',
        level: 2,
        name: '互联网相关服务',
        nameEn: 'Internet-related services',
        node: [
          { code: '8914977410', level: 3, name: '互联网游戏服务', nameEn: 'Internet gaming services', node: [] },
          { code: '8914977411', level: 3, name: '互联网安全服务', nameEn: 'Internet Security Services', node: [] },
          {
            code: '8914977409',
            level: 3,
            name: '互联网接入及相关服务',
            nameEn: 'Internet access and related services',
            node: [],
          },
          {
            code: '8914977412',
            level: 3,
            name: '其他互联网相关服务',
            nameEn: 'Other Internet-related services',
            node: [],
          },
          { code: '8914977666', level: 3, name: '互联网搜索服务', nameEn: 'Internet search services', node: [] },
          { code: '8914977667', level: 3, name: '互联网资讯服务', nameEn: 'Internet information services', node: [] },
          { code: '8914977668', level: 3, name: '互联网数据服务', nameEn: '030306 Internet data services', node: [] },
        ],
      },
      {
        code: '8914977669',
        level: 2,
        name: '信息技术服务',
        nameEn: 'Information Technology Services',
        node: [
          { code: '8914977413', level: 3, name: '集成电路设计', nameEn: 'Integrated circuit design', node: [] },
          {
            code: '8914977414',
            level: 3,
            name: '物联网技术服务',
            nameEn: 'Internet of Things technology services',
            node: [],
          },
          {
            code: '8914977415',
            level: 3,
            name: '信息处理和存储支持服务',
            nameEn: 'Information processing and storage support services',
            node: [],
          },
          {
            code: '8914977416',
            level: 3,
            name: '地理遥感信息及测绘地理信息服务',
            nameEn: 'Geographic remote sensing information and surveying, mapping and geographic information services',
            node: [],
          },
          {
            code: '8914977417',
            level: 3,
            name: '其他信息技术服务业',
            nameEn: 'Other information technology services',
            node: [],
          },
          {
            code: '8914977670',
            level: 3,
            name: '信息系统集成服务',
            nameEn: 'Information system integration services',
            node: [],
          },
          { code: '8914977671', level: 3, name: '运行维护服务', nameEn: 'Run maintenance services', node: [] },
          {
            code: '8914977672',
            level: 3,
            name: '信息技术咨询服务',
            nameEn: 'Information Technology Consulting Services',
            node: [],
          },
          {
            code: '8914977673',
            level: 3,
            name: '动漫、游戏及其他数字内容服务',
            nameEn: 'Anime, games and other digital content services',
            node: [],
          },
        ],
      },
    ],
  },
  {
    code: '8914977419',
    level: 1,
    name: '数字要素驱动业',
    nameEn: 'Digital factors drive industry',
    node: [
      {
        code: '8914977431',
        level: 2,
        name: '信息基础设施建设',
        nameEn: 'Information infrastructure construction',
        node: [
          {
            code: '8914977432',
            level: 3,
            name: '新技术基础设施建设',
            nameEn: 'Construction of new technology infrastructure',
            node: [],
          },
          {
            code: '8914977433',
            level: 3,
            name: '其他信息基础设施建设',
            nameEn: 'Other information infrastructure construction',
            node: [],
          },
          {
            code: '8914977688',
            level: 3,
            name: '网络基础设施建设',
            nameEn: 'Network infrastructure construction',
            node: [],
          },
          {
            code: '8914977689',
            level: 3,
            name: '算力基础设施建设',
            nameEn: 'Computing power infrastructure construction',
            node: [],
          },
        ],
      },
      {
        code: '8914977424',
        level: 2,
        name: '互联网金融',
        nameEn: 'Internet finance',
        node: [
          {
            code: '8914977425',
            level: 3,
            name: '非金融机构支付服务',
            nameEn: 'Payment services for non-financial institutions',
            node: [],
          },
          { code: '8914977681', level: 3, name: '网络借贷服务', nameEn: 'Online lending services', node: [] },
          { code: '8914977682', level: 3, name: '金融信息服务', nameEn: 'Financial information services', node: [] },
        ],
      },
      {
        code: '8914977426',
        level: 2,
        name: '数字内容与媒体',
        nameEn: 'Digital Content & Media',
        node: [
          { code: '8914977430', level: 3, name: '数字内容出版', nameEn: 'First edition of digital content', node: [] },
          { code: '8914977427', level: 3, name: '电视', nameEn: 'TV', node: [] },
          {
            code: '8914977428',
            level: 3,
            name: '广播电视集成播控',
            nameEn: 'Integrated broadcast control of radio and television',
            node: [],
          },
          { code: '8914977429', level: 3, name: '电影放映', nameEn: 'Film screenings', node: [] },
          { code: '8914977683', level: 3, name: '广播', nameEn: 'broadcast', node: [] },
          {
            code: '8914977684',
            level: 3,
            name: '影视节目制作',
            nameEn: 'Film and television program production',
            node: [],
          },
          {
            code: '8914977685',
            level: 3,
            name: '电影和广播电视节目发行',
            nameEn: 'Film and radio and television distribution',
            node: [],
          },
          { code: '8914977686', level: 3, name: '录音制作', nameEn: 'Sound recording', node: [] },
          { code: '8914977687', level: 3, name: '数字广告', nameEn: 'Digital advertising', node: [] },
        ],
      },
      {
        code: '8914977434',
        level: 2,
        name: '其他数字要素驱动业',
        nameEn: 'Other digital drivers of the industry',
        node: [
          {
            code: '8914977435',
            level: 3,
            name: '安全系统监控服务',
            nameEn: 'Security system monitoring services',
            node: [],
          },
          {
            code: '8914977691',
            level: 3,
            name: '供应链管理服务',
            nameEn: 'Supply chain management services',
            node: [],
          },
          {
            code: '8914977692',
            level: 3,
            name: '数字技术研究和试验发展',
            nameEn: 'Digital technology research and experimental development',
            node: [],
          },
        ],
      },
      {
        code: '8914977676',
        level: 2,
        name: '互联网平台',
        nameEn: 'Internet Platforms',
        node: [
          {
            code: '8914977420',
            level: 3,
            name: '互联网生产服务平台',
            nameEn: 'Internet production service platform',
            node: [],
          },
          {
            code: '8914977421',
            level: 3,
            name: '互联网科技创新平台',
            nameEn: 'Internet technology innovation platform',
            node: [],
          },
          { code: '8914977422', level: 3, name: '其他互联网平台', nameEn: 'Other Internet Platforms', node: [] },
          {
            code: '8914977677',
            level: 3,
            name: '互联网生活服务平台',
            nameEn: 'Internet life service platform',
            node: [],
          },
          {
            code: '8914977678',
            level: 3,
            name: '互联网公共服务平台',
            nameEn: 'Internet public service platform',
            node: [],
          },
        ],
      },
      {
        code: '8914977679',
        level: 2,
        name: '互联网批发零售',
        nameEn: 'Internet wholesale and retail',
        node: [
          { code: '8914977423', level: 3, name: '互联网批发', nameEn: 'Internet wholesale', node: [] },
          { code: '8914977680', level: 3, name: '互联网零售', nameEn: 'Internet retail', node: [] },
        ],
      },
      {
        code: '8914977690',
        level: 2,
        name: '数据资源与产权交易',
        nameEn: 'Data resources and property rights transactions',
        node: [],
      },
    ],
  },
  {
    code: '8914977436',
    level: 1,
    name: '数字化效率提升业',
    nameEn: 'Digital efficiency improvement industry',
    node: [
      {
        code: '8914977703',
        level: 2,
        name: '数字金融',
        nameEn: 'Digital finance',
        node: [
          {
            code: '8914977704',
            level: 3,
            name: '数字资本市场服务',
            nameEn: 'Digital capital markets services',
            node: [],
          },
          { code: '8914977705', level: 3, name: '其他数字金融', nameEn: 'Other digital finance', node: [] },
          { code: '8914977447', level: 3, name: '银行金融服务', nameEn: 'Banking and financial services', node: [] },
          { code: '8914977448', level: 3, name: '互联网保险', nameEn: 'Internet insurance', node: [] },
        ],
      },
      {
        code: '8914977709',
        level: 2,
        name: '数字社会',
        nameEn: 'Digital society',
        node: [
          { code: '8914977710', level: 3, name: '智慧医疗', nameEn: 'Smart Healthcare', node: [] },
          { code: '8914977453', level: 3, name: '智慧教育', nameEn: 'Smart education', node: [] },
          { code: '8914977454', level: 3, name: '数字化社会工作', nameEn: 'Digital social work', node: [] },
        ],
      },
      {
        code: '8914977442',
        level: 2,
        name: '智能交通',
        nameEn: 'Intelligent transportation',
        node: [
          { code: '8914977700', level: 3, name: '智能水上运输', nameEn: 'Smart water transportation', node: [] },
          { code: '8914977701', level: 3, name: '其他智能交通', nameEn: 'Other intelligent transportation', node: [] },
          { code: '8914977443', level: 3, name: '智能道路运输', nameEn: 'Smart road transport', node: [] },
          { code: '8914977444', level: 3, name: '智能航空运输', nameEn: 'Intelligent air transportation', node: [] },
          { code: '8914977699', level: 3, name: '智能铁路运输', nameEn: 'Intelligent rail transportation', node: [] },
        ],
      },
      {
        code: '8914977711',
        level: 2,
        name: '数字政府',
        nameEn: 'Digital government',
        node: [
          { code: '8914977712', level: 3, name: '网上税务办理', nameEn: 'Online tax processing', node: [] },
          {
            code: '8914977713',
            level: 3,
            name: '网上社会保障服务',
            nameEn: 'Online social security services',
            node: [],
          },
          {
            code: '8914977455',
            level: 3,
            name: '行政办公自动化',
            nameEn: 'Administrative office automation',
            node: [],
          },
          { code: '8914977456', level: 3, name: '互联网海关服务', nameEn: 'Internet customs services', node: [] },
          { code: '8914977457', level: 3, name: '其他数字政府', nameEn: 'Other digital governments', node: [] },
        ],
      },
      {
        code: '8914977714',
        level: 2,
        name: '其他数字化效率提升业',
        nameEn: 'Other digital efficiency improvement industries',
        node: [
          {
            code: '8914977715',
            level: 3,
            name: '智能化电力、热力、燃气及水生产和供应',
            nameEn: 'Intelligent electricity, heat, gas and water production and supply',
            node: [],
          },
          { code: '8914977716', level: 3, name: '互联网房地产业', nameEn: 'Internet real estate industry', node: [] },
          {
            code: '8914977717',
            level: 3,
            name: '数字化水利、环境和市政设施管理',
            nameEn: 'Digital water, environmental and municipal facilities management',
            node: [],
          },
          {
            code: '8914977718',
            level: 3,
            name: '互联网文体娱乐业',
            nameEn: 'Internet, sports and entertainment industry',
            node: [],
          },
          {
            code: '8914977460',
            level: 3,
            name: '专业技术服务业数字化',
            nameEn: 'Digitalization of professional and technical services',
            node: [],
          },
          {
            code: '8914977461',
            level: 3,
            name: '互联网居民生活服务',
            nameEn: 'Internet Resident Life Services',
            node: [],
          },
          { code: '8914977458', level: 3, name: '数字采矿', nameEn: 'Digital mining', node: [] },
          { code: '8914977459', level: 3, name: '数字化建筑业', nameEn: 'Digital construction', node: [] },
        ],
      },
      {
        code: '8914977693',
        level: 2,
        name: '智慧农业',
        nameEn: 'Smart agriculture',
        node: [
          { code: '8914977437', level: 3, name: '数字化设施种植', nameEn: 'Digital facility planting', node: [] },
          { code: '8914977438', level: 3, name: '自动化养殖', nameEn: 'Automated farming', node: [] },
          { code: '8914977439', level: 3, name: '其他智慧农业', nameEn: 'Other smart agriculture', node: [] },
          { code: '8914977694', level: 3, name: '数字林业', nameEn: 'Digital forestry', node: [] },
          { code: '8914977695', level: 3, name: '新技术育种', nameEn: 'New technology breeding', node: [] },
        ],
      },
      {
        code: '8914977696',
        level: 2,
        name: '智能制造',
        nameEn: 'Smart manufacturing',
        node: [
          {
            code: '8914977440',
            level: 3,
            name: '数字化通用、专用设备制造',
            nameEn: 'Digital general-purpose, special-purpose equipment manufacturing',
            node: [],
          },
          {
            code: '8914977441',
            level: 3,
            name: '数字化电气机械、器材和仪器仪表制造',
            nameEn: 'Digital Electrical Machinery, Equipment and instrumentation manufacturing',
            node: [],
          },
          {
            code: '8914977697',
            level: 3,
            name: '数字化运输设备制造',
            nameEn: 'Digital transport equipment manufacturing',
            node: [],
          },
          { code: '8914977698', level: 3, name: '其他智能制造', nameEn: 'Other smart manufacturing', node: [] },
        ],
      },
      {
        code: '8914977445',
        level: 2,
        name: '智慧物流',
        nameEn: 'Smart logistics',
        node: [
          { code: '8914977702', level: 3, name: '智慧仓储', nameEn: 'Smart warehousing', node: [] },
          { code: '8914977446', level: 3, name: '智慧配送', nameEn: 'Smart delivery', node: [] },
        ],
      },
      {
        code: '8914977449',
        level: 2,
        name: '数字商贸',
        nameEn: 'Digital commerce',
        node: [
          { code: '8914977706', level: 3, name: '数字化批发', nameEn: 'Digital wholesale', node: [] },
          { code: '8914977707', level: 3, name: '数字化住宿', nameEn: 'Digital accommodation', node: [] },
          { code: '8914977708', level: 3, name: '数字化租赁', nameEn: 'Digital leasing', node: [] },
          { code: '8914977450', level: 3, name: '数字化零售', nameEn: 'Digital retail', node: [] },
          { code: '8914977451', level: 3, name: '数字化餐饮', nameEn: 'Digital catering', node: [] },
          { code: '8914977452', level: 3, name: '数字化商务服务', nameEn: 'Digital business services', node: [] },
        ],
      },
    ],
  },
  {
    code: '8914977623',
    level: 1,
    name: '数字产品制造业',
    nameEn: 'Digital goods manufacturing',
    node: [
      {
        code: '8914977367',
        level: 2,
        name: '计算机制造',
        nameEn: 'Computer manufacturing',
        node: [
          { code: '8914977370', level: 3, name: '其他计算机制造', nameEn: 'Other computer manufacturing', node: [] },
          { code: '8914977368', level: 3, name: '计算机零部件制造', nameEn: 'Computer parts manufacturing', node: [] },
          {
            code: '8914977369',
            level: 3,
            name: '工业控制计算机及系统制造',
            nameEn: 'Industrial control computer and system manufacturing',
            node: [],
          },
          { code: '8914977624', level: 3, name: '计算机整机制造', nameEn: 'Computer manufacturing', node: [] },
          {
            code: '8914977625',
            level: 3,
            name: '计算机外围设备制造',
            nameEn: 'Computer peripheral manufacturing',
            node: [],
          },
          {
            code: '8914977626',
            level: 3,
            name: '信息安全设备制造',
            nameEn: 'Information security equipment manufacturing',
            node: [],
          },
        ],
      },
      {
        code: '8914977638',
        level: 2,
        name: '电子元器件及设备制造',
        nameEn: 'Electronic components and equipment manufacturing',
        node: [
          {
            code: '8914977640',
            level: 3,
            name: '光伏设备及元器件制造',
            nameEn: 'Photovoltaic equipment and components manufacturing',
            node: [],
          },
          {
            code: '8914977641',
            level: 3,
            name: '电子真空器件制造',
            nameEn: 'Electronic vacuum device manufacturing',
            node: [],
          },
          { code: '8914977642', level: 3, name: '集成电路制造', nameEn: 'Integrated circuit manufacturing', node: [] },
          {
            code: '8914977639',
            level: 3,
            name: '电子元器件与机电组件设备制造',
            nameEn: 'Manufacturing of electronic components and electromechanical components',
            node: [],
          },
          {
            code: '8914977643',
            level: 3,
            name: '半导体照明器件制造',
            nameEn: 'Semiconductor lighting device manufacturing',
            node: [],
          },
          {
            code: '8914977644',
            level: 3,
            name: '电阻电容电感元件制造',
            nameEn: 'Manufacture of resistors, capacitors, inductors, and inductors',
            node: [],
          },
          {
            code: '8914977645',
            level: 3,
            name: '敏感元件及传感器制造',
            nameEn: 'Manufacture of sensitive components and sensors',
            node: [],
          },
          {
            code: '8914977646',
            level: 3,
            name: '电子专用材料制造',
            nameEn: 'Manufacture of special materials for electronics',
            node: [],
          },
          {
            code: '8914977382',
            level: 3,
            name: '半导体器件专用设备制造',
            nameEn: 'Manufacture of special equipment for semiconductor devices',
            node: [],
          },
          {
            code: '8914977383',
            level: 3,
            name: '电力电子元器件制造',
            nameEn: 'Power electronic component manufacturing',
            node: [],
          },
          {
            code: '8914977384',
            level: 3,
            name: '电气信号设备装置制造',
            nameEn: 'Electrical signal equipment device manufacturing',
            node: [],
          },
          {
            code: '8914977385',
            level: 3,
            name: '半导体分立器件制造',
            nameEn: 'Semiconductor discrete device manufacturing',
            node: [],
          },
          { code: '8914977386', level: 3, name: '显示器件制造', nameEn: 'Display device manufacturing', node: [] },
          {
            code: '8914977387',
            level: 3,
            name: '光电子器件制造',
            nameEn: 'Optoelectronic device manufacturing',
            node: [],
          },
          { code: '8914977388', level: 3, name: '电子电路制造', nameEn: 'Electronic circuit manufacturing', node: [] },
          {
            code: '8914977389',
            level: 3,
            name: '电声器件及零件制造',
            nameEn: 'Electroacoustic device and parts manufacturing',
            node: [],
          },
          {
            code: '8914977390',
            level: 3,
            name: '其他元器件及设备制造',
            nameEn: 'Other components and equipment manufacturing',
            node: [],
          },
        ],
      },
      {
        code: '8914977377',
        level: 2,
        name: '智能设备制造',
        nameEn: 'Smart device manufacturing',
        node: [
          { code: '8914977634', level: 3, name: '工业机器人制造', nameEn: 'Industrial robot manufacturing', node: [] },
          {
            code: '8914977635',
            level: 3,
            name: '智能照明器具制造',
            nameEn: 'Intelligent lighting appliance manufacturing',
            node: [],
          },
          {
            code: '8914977636',
            level: 3,
            name: '智能车载设备制造',
            nameEn: 'Intelligent in-vehicle equipment manufacturing',
            node: [],
          },
          {
            code: '8914977637',
            level: 3,
            name: '服务消费机器人制造',
            nameEn: 'Service consumer robot manufacturing',
            node: [],
          },
          {
            code: '8914977378',
            level: 3,
            name: '特殊作业机器人制造',
            nameEn: 'Special operation robot manufacturing',
            node: [],
          },
          {
            code: '8914977380',
            level: 3,
            name: '智能无人飞行器制造',
            nameEn: 'Intelligent unmanned aerial vehicle manufacturing',
            node: [],
          },
          {
            code: '8914977381',
            level: 3,
            name: '其他智能消费设备制造',
            nameEn: 'Other smart consumer device manufacturing',
            node: [],
          },
          {
            code: '8914977379',
            level: 3,
            name: '可穿戴智能设备制造',
            nameEn: 'Wearable smart device manufacturing',
            node: [],
          },
        ],
      },
      {
        code: '8914977647',
        level: 2,
        name: '其他数字产品制造业',
        nameEn: 'Other digital goods manufacturing',
        node: [
          {
            code: '8914977650',
            level: 3,
            name: '专用电线、电缆制造',
            nameEn: 'Special wire and cable manufacturing',
            node: [],
          },
          { code: '8914977651', level: 3, name: '光缆制造', nameEn: 'Fiber optic cable manufacturing', node: [] },
          {
            code: '8914977648',
            level: 3,
            name: '电子游戏游艺设备制造',
            nameEn: 'Video game amusement equipment manufacturing',
            node: [],
          },
          {
            code: '8914977649',
            level: 3,
            name: '计算器及货币专用设备制造',
            nameEn: 'Manufacture of calculators and special equipment for currency',
            node: [],
          },
          { code: '8914977391', level: 3, name: '记录媒介复制', nameEn: 'Record media copying', node: [] },
          {
            code: '8914977392',
            level: 3,
            name: '信息化学品制造',
            nameEn: 'Information chemical manufacturing',
            node: [],
          },
          {
            code: '8914977393',
            level: 3,
            name: '增材制造装备制造',
            nameEn: 'Additive manufacturing equipment manufacturing',
            node: [],
          },
          { code: '8914977394', level: 3, name: '光纤制造', nameEn: 'Fiber manufacturing', node: [] },
          {
            code: '8914977395',
            level: 3,
            name: '工业自动控制系统装置制造',
            nameEn: 'Industrial automatic control system device manufacturing',
            node: [],
          },
        ],
      },
      {
        code: '8914977627',
        level: 2,
        name: '通讯及雷达设备制造',
        nameEn: 'Communication and radar equipment manufacturing',
        node: [
          {
            code: '8914977371',
            level: 3,
            name: '通信系统设备制造',
            nameEn: 'Manufacture of communication system equipment',
            node: [],
          },
          {
            code: '8914977372',
            level: 3,
            name: '雷达及配套设备制造',
            nameEn: 'Radar and ancillary equipment manufacturing',
            node: [],
          },
          {
            code: '8914977628',
            level: 3,
            name: '通信终端设备制造',
            nameEn: 'Communication terminal equipment manufacturing',
            node: [],
          },
        ],
      },
      {
        code: '8914977629',
        level: 2,
        name: '数字媒体设备制造',
        nameEn: 'Digital media equipment manufacturing',
        node: [
          { code: '8914977632', level: 3, name: '电视机制造', nameEn: 'TV manufacturing', node: [] },
          {
            code: '8914977633',
            level: 3,
            name: '影视录放设备制造',
            nameEn: 'Film and television recording and playback equipment manufacturing',
            node: [],
          },
          {
            code: '8914977373',
            level: 3,
            name: '广播电视节目制作及发射设备制造',
            nameEn: 'Radio and television program production and transmission equipment manufacturing',
            node: [],
          },
          {
            code: '8914977374',
            level: 3,
            name: '广播电视专用配件制造',
            nameEn: 'Radio and television special accessories manufacturing',
            node: [],
          },
          {
            code: '8914977375',
            level: 3,
            name: '应用电视设备及其他广播电视设备制造',
            nameEn: 'Application television equipment and other radio and television equipment manufacturing',
            node: [],
          },
          { code: '8914977376', level: 3, name: '音响设备制造', nameEn: 'Audio equipment manufacturing', node: [] },
          {
            code: '8914977630',
            level: 3,
            name: '广播电视接收设备制造',
            nameEn: 'Radio and television receiving equipment manufacturing',
            node: [],
          },
          {
            code: '8914977631',
            level: 3,
            name: '专业音响设备制造',
            nameEn: 'Professional audio equipment manufacturing',
            node: [],
          },
        ],
      },
    ],
  },
]
