import { IndustryTreeNode } from './type'

// 战略新兴产业
export const globalStrategicEmergingIndustry: IndustryTreeNode[] = [
  {
    code: '142614869',
    level: 1,
    name: '新能源产业',
    nameEn: 'New Energy Industry',
    node: [
      {
        code: '142614627',
        level: 2,
        name: '核电产业',
        nameEn: 'Nuclear Power Industry',
        node: [],
      },
      {
        code: '142614640',
        level: 2,
        name: '智能电网产业',
        nameEn: 'Smart Grid Industry',
        node: [],
      },
      {
        code: '142614636',
        level: 2,
        name: '生物质能及其他新能源产业',
        nameEn: 'Biomass energy and other new energy industries',
        node: [],
      },
      {
        code: '142614633',
        level: 2,
        name: '太阳能产业',
        nameEn: 'Solar Energy Industry',
        node: [],
      },
      {
        code: '142614630',
        level: 2,
        name: '风能产业',
        nameEn: 'Wind energy industry',
        node: [],
      },
    ],
  },
  {
    code: '142614862',
    level: 1,
    name: '新能源汽车产业',
    nameEn: 'New Energy Vehicle Industry',
    node: [
      {
        code: '142614625',
        level: 2,
        name: '新能源汽车相关服务',
        nameEn: 'New energy vehicle related services',
        node: [],
      },
      {
        code: '142614623',
        level: 2,
        name: '新能源汽车相关设施制造',
        nameEn: 'Manufacturing of facilities related to new energy vehicles',
        node: [],
      },
      {
        code: '142614620',
        level: 2,
        name: '新能源汽车整车制造',
        nameEn: 'New energy vehicle manufacturing',
        node: [],
      },
      {
        code: '142614621',
        level: 2,
        name: '新能源汽车装置、配件制造',
        nameEn: 'Manufacturing of new energy vehicle devices and accessories',
        node: [],
      },
    ],
  },
  {
    code: '142614662',
    level: 1,
    name: '相关服务业',
    nameEn: 'Related services',
    node: [
      {
        code: '142614905',
        level: 2,
        name: '新技术与创新创业服务',
        nameEn: 'New technology and innovation and entrepreneurship services',
        node: [],
      },
      {
        code: '142614666',
        level: 2,
        name: '其他相关服务',
        nameEn: 'Other related services',
        node: [],
      },
    ],
  },
  {
    code: '142614898',
    level: 1,
    name: '数字创意产业',
    nameEn: 'Digital creative industry',
    node: [
      {
        code: '142614660',
        level: 2,
        name: '设计服务',
        nameEn: 'Design services',
        node: [],
      },
      {
        code: '142614661',
        level: 2,
        name: '数字创意与融合服务',
        nameEn: 'Digital Creativity and Convergence Services',
        node: [],
      },
      {
        code: '142614657',
        level: 2,
        name: '数字文化创意活动',
        nameEn: 'Digital cultural and creative activities',
        node: [],
      },
      {
        code: '142614656',
        level: 2,
        name: '数字创意技术设备制造',
        nameEn: 'Digital creative technology equipment manufacturing',
        node: [],
      },
    ],
  },
  {
    code: '142614451',
    level: 1,
    name: '新一代信息技术产业',
    nameEn: 'New Generation Information Technology Industry',
    node: [
      {
        code: '142609953',
        level: 2,
        name: '下一代信息网络产业',
        nameEn: 'Next Generation Information Network Industry',
        node: [],
      },
      {
        code: '142614460',
        level: 2,
        name: '互联网与云计算、大数据服务',
        nameEn: 'Internet and cloud computing, big data services',
        node: [],
      },
      {
        code: '142609959',
        level: 2,
        name: '新兴软件和新型信息技术服务',
        nameEn: 'Emerging software and new information technology services',
        node: [],
      },
      {
        code: '142614455',
        level: 2,
        name: '电子核心产业',
        nameEn: 'Electronic core industry',
        node: [],
      },
      {
        code: '142609964',
        level: 2,
        name: '人工智能',
        nameEn: 'Artificial Intelligence',
        node: [],
      },
    ],
  },
  {
    code: '142614604',
    level: 1,
    name: '生物产业',
    nameEn: 'Biological Industry',
    node: [
      {
        code: '142614616',
        level: 2,
        name: '其他生物业',
        nameEn: 'Other sanitary properties',
        node: [],
      },
      {
        code: '142614614',
        level: 2,
        name: '生物质能产业',
        nameEn: 'Biomass energy industry',
        node: [],
      },
      {
        code: '142614853',
        level: 2,
        name: '生物农业及相关产业',
        nameEn: 'Bio-agriculture and related industries',
        node: [],
      },
      {
        code: '142614850',
        level: 2,
        name: '生物医学工程产业',
        nameEn: 'Biomedical Engineering Industry',
        node: [],
      },
      {
        code: '142614847',
        level: 2,
        name: '生物医药产业',
        nameEn: 'Biomedical Industry',
        node: [],
      },
    ],
  },
  {
    code: '142614642',
    level: 1,
    name: '节能环保产业',
    nameEn: 'Energy-saving and environmental protection industry',
    node: [
      {
        code: '142614893',
        level: 2,
        name: '资源循环利用产业',
        nameEn: 'Resource recycling industry',
        node: [],
      },
      {
        code: '142614889',
        level: 2,
        name: '先进环保产业',
        nameEn: 'Advanced environmental protection industry',
        node: [],
      },
      {
        code: '142614885',
        level: 2,
        name: '高效节能产业',
        nameEn: 'High-efficiency and energy-saving industry',
        node: [],
      },
    ],
  },
  {
    code: '142614478',
    level: 1,
    name: '新材料产业',
    nameEn: 'New Material Industry',
    node: [
      {
        code: '142614589',
        level: 2,
        name: '前沿新材料',
        nameEn: 'Frontier new materials',
        node: [],
      },
      {
        code: '142614581',
        level: 2,
        name: '高性能纤维及制品和复合材料',
        nameEn: 'High performance fibers and products and composites',
        node: [],
      },
      {
        code: '142614812',
        level: 2,
        name: '先进无机非金属材料',
        nameEn: 'Advanced inorganic non-metallic material',
        node: [],
      },
      {
        code: '142609980',
        level: 2,
        name: '先进钢铁材料',
        nameEn: 'Advanced steel materials',
        node: [],
      },
      {
        code: '142614843',
        level: 2,
        name: '新材料相关服务',
        nameEn: 'New material related services',
        node: [],
      },
      {
        code: '142614520',
        level: 2,
        name: '先进有色金属材料',
        nameEn: 'Advanced non-ferrous metal materials',
        node: [],
      },
      {
        code: '142614790',
        level: 2,
        name: '先进石化化工新材料',
        nameEn: 'Advanced Petrochemical New Material',
        node: [],
      },
    ],
  },
  {
    code: '142609966',
    level: 1,
    name: '高端装备制造产业',
    nameEn: 'High-end equipment manufacturing industry',
    node: [
      {
        code: '142614465',
        level: 2,
        name: '智能制造装备产业',
        nameEn: 'Intelligent manufacturing equipment industry',
        node: [],
      },
      {
        code: '142609970',
        level: 2,
        name: '航空装备产业',
        nameEn: 'Aviation equipment industry',
        node: [],
      },
      {
        code: '142609974',
        level: 2,
        name: '轨道交通装备产业',
        nameEn: 'Rail transit equipment industry',
        node: [],
      },
      {
        code: '142614475',
        level: 2,
        name: '海洋工程装备产业',
        nameEn: 'Marine engineering equipment industry',
        node: [],
      },
      {
        code: '142614470',
        level: 2,
        name: '卫星及应用产业',
        nameEn: 'Satellite and application industry',
        node: [],
      },
    ],
  },
]
