export enum PageModuleEnum {
  /**  企业信息详情 */
  EAPI = 1103,
  /**  标准信息详情 */
  STANDARD_INFO = 5553,
  /**  APP产品详情 */
  APP_PRODUCT_DETAILS = 5552,
  /**  资质大全 */
  QUALIFICATION_GUIDE = 3123,
  /**  图谱平台 */
  KG_PLATFORM = 1117,
  /**  专项数据 */
  SPECIAL_DATA = 1118,
  /**  海外企业详情页 */
  OVERSEAS_COMPANY_DETAILS = 2341,
  /**  VIP服务 */
  VIP_SERVICE = 1104,
  /**  榜单名录 */
  RANKING_LIST = 1105,
  /**  便携工具 */
  PORTABLE_TOOLS = 1106,
  /**  尽调平台 */
  INVESTIGATION_PLATFORM = 1107,
  /**  场景应用 */
  SCENE_APPLICATION = 1108,
  /**  各数据详情页 */
  DATA_DETAIL_PAGE = 1109,
  /**  集团系 */
  GROUP = 1110,
  /**  企业详情 */
  COMPANY_DETAILS = 1111,
  /**  公司人物详情 */
  CHARACTER_INFO = 1112,
  /**  集团系详情 */
  GROUP_INFO = 5542,
  /**  首页 */
  HOME_PAGE = 1113,
  /**  搜索 */
  SEARCH = 1114,
  /**  特色企业 */
  FEATURED_COMPANIES = 1115,
  /**  通用 */
  GENERAL = 1116,
  /**  移动端 */
  MOBILE = 2121,
  /**  企业年报详情 */
  COMPANY_ANNUAL_REPORT = 2713,
  /**  查企业 */
  QUERY_COMPANY = 2714,
  /**  查关系 */
  QUERY_RELATIONSHIP = 2715,
  /**  查集团 */
  QUERY_GROUP = 2716,
  /**  查全球企业 */
  QUERY_OVERSEAS_COMPANY = 2717,
  /**  企业榜单名录 */
  COMPANY_RANKING_LIST = 2718,
  /**  股权穿透图 */
  SHAREHOLDER_TRANSPARENCY_MAP = 2719,
  /**  疑似关系图 */
  SUSPECT_RELATIONSHIP_GRAPH = 2720,
  /**  疑似控制人 */
  SUSPECT_CONTROLLER = 2721,
  /**  融资图谱 */
  FINANCING_MAP = 2722,
  /**  关联方图谱 */
  RELATED_PARTY_MAP = 2723,
  /**  多对一触达 */
  MULTIPLE_TO_ONE_REACH = 2724,
  /**  招投标查询 */
  BID_SEARCH = 2725,
  /**  专利 */
  PATENT = 2726,
  /**  招聘查询 */
  EMPLOYMENT_SEARCH = 2727,
  /**  重点园区 */
  KEY_INDUSTRIAL_PARKS = 2728,
  /**  万寻地图 */
  WAN_XUAN_MAP = 2729,
  /**  新企发现 */
  NEW_ENTERPRISE_DISCOVERY = 2730,
  /**  企业数据浏览器 */
  COMPANY_DATA_BROWSER = 2731,
  /**  批量查询导出 */
  BATCH_QUERY_EXPORT = 2732,
  /**  数据API */
  DATA_API = 2733,
  /**  企业动态 */
  COMPANY_DYNAMIC = 2734,
  /**  我的账号 */
  MY_ACCOUNT = 5543,
  /**  联系我们 */
  CONTACT_US = 5551,
  /**  免责声明 */
  DISCLAIMER = 5550,
  /**  隐私政策 */
  PRIVACY_POLICY = 5549,
  /**  用户协议 */
  USER_AGREEMENT = 5548,
  /**  我的订单 */
  MY_ORDER = 5547,
  /**  我的数据 */
  MY_DATA = 5546,
  /**  我的收藏 */
  MY_COLLECTION = 5545,
  /**数据出境整改 */
  DATA_EXPORT_REVIEW = 7116,
}
