// 通过一级菜单和二级菜单的关系映射
import { ECorpDetailModule, ECorpDetailSubModule, TCorpDetailSubModule } from './type.ts'

export const corpDetailMenuStructure: Record<ECorpDetailModule, TCorpDetailSubModule[]> = {
  [ECorpDetailModule.Overview]: [
    ECorpDetailSubModule.ShowCompanyInfo,
    ECorpDetailSubModule.ShowIndustry,
    ECorpDetailSubModule.ShowActualController,
    ECorpDetailSubModule.ShowShareholder,
    ECorpDetailSubModule.ShowVietnamIndustry,
    ECorpDetailSubModule.ShowShareSearch,
    ECorpDetailSubModule.GetShareAndInvest,
    ECorpDetailSubModule.ShowShareholderChange,
    ECorpDetailSubModule.ShowCompanyBranchInfo,
    ECorpDetailSubModule.ShowControllerCompany,
    ECorpDetailSubModule.ShowDirectInvestment,
    ECorpDetailSubModule.ShowFinalBeneficiary,
    ECorpDetailSubModule.StructuralEntities,
    ECorpDetailSubModule.ShowMainMemberInfo,
    ECorpDetailSubModule.ShowCoreTeam,
    ECorpDetailSubModule.ShowGroupSystem,
    ECorpDetailSubModule.ShowHeadOffice,
    ECorpDetailSubModule.GetComparable,
    ECorpDetailSubModule.ShowCompanyChange,
    ECorpDetailSubModule.GetTaxpayer,
    ECorpDetailSubModule.ShowCompanyNotice,
    ECorpDetailSubModule.ShowYearReport,
  ],
  [ECorpDetailModule.IpoBusinessData]: [
    ECorpDetailSubModule.ShowIpoYield,
    ECorpDetailSubModule.ShowIpoSales,
    ECorpDetailSubModule.ShowIpoBusiness,
    ECorpDetailSubModule.ShowIpoStock,
  ],
  [ECorpDetailModule.PublishFundData]: [ECorpDetailSubModule.ShowFundSize, ECorpDetailSubModule.ShowItsFunds],
  [ECorpDetailModule.PrivateFundData]: [ECorpDetailSubModule.ShowPrivateFundInfo],
  [ECorpDetailModule.Financing]: [
    ECorpDetailSubModule.ShowShares,
    ECorpDetailSubModule.ShowDeclarCompany,
    ECorpDetailSubModule.ShowBond,
    ECorpDetailSubModule.ShowComBondRate,
    ECorpDetailSubModule.ShowInvestmentAgency,
    ECorpDetailSubModule.ShowInvestmentEvent,
    ECorpDetailSubModule.ShowPVEC,
    ECorpDetailSubModule.PvecOut,
    ECorpDetailSubModule.ShowMerge,
    ECorpDetailSubModule.ShowGrantCredit,
    ECorpDetailSubModule.AbsInfo,
    ECorpDetailSubModule.ShowChattleFinancing,
    ECorpDetailSubModule.ShowChattelMortgage,
    ECorpDetailSubModule.ShowInsurance,
  ],
  [ECorpDetailModule.Business]: [
    ECorpDetailSubModule.FinancialData,
    ECorpDetailSubModule.BusinessScope,
    ECorpDetailSubModule.ShowComBuInfo,
    ECorpDetailSubModule.ShowApp,
    ECorpDetailSubModule.ShowHotels,
    ECorpDetailSubModule.ResearchReport01,
    ECorpDetailSubModule.MajorGovProject,
    ECorpDetailSubModule.BiddingInfo,
    ECorpDetailSubModule.Jobs,
    ECorpDetailSubModule.ShowLandInfo,
    ECorpDetailSubModule.GetFundPe,
    ECorpDetailSubModule.ShowCustomersSup,
    ECorpDetailSubModule.GetRelatedParty,
    ECorpDetailSubModule.GovernmentSupport01,
    ECorpDetailSubModule.GetGovSupport,
  ],
  [ECorpDetailModule.Qualifications]: [
    ECorpDetailSubModule.GetPermission02,
    ECorpDetailSubModule.Credit,
    ECorpDetailSubModule.Jrxx,
    ECorpDetailSubModule.ShowFranchise,
    ECorpDetailSubModule.GetFinancialLicence,
    ECorpDetailSubModule.GetTeleLics,
    ECorpDetailSubModule.GetGameApproval,
    ECorpDetailSubModule.ShowBuildOrder,
    ECorpDetailSubModule.EnterpriseDevelopment,
    ECorpDetailSubModule.LogisticsCreditRating,
    ECorpDetailSubModule.GetImpexp,
    ECorpDetailSubModule.GetAuthentication,
    ECorpDetailSubModule.GetTaxCredit1,
    ECorpDetailSubModule.Hzpscxk,
    ECorpDetailSubModule.SelectList,
    ECorpDetailSubModule.ListInformation,
  ],
  [ECorpDetailModule.Intellectual]: [
    ECorpDetailSubModule.GetTechScore,
    ECorpDetailSubModule.GetBrand,
    ECorpDetailSubModule.GetPatent,
    ECorpDetailSubModule.GetProductionCopyright,
    ECorpDetailSubModule.GetSoftwareCopyright,
    ECorpDetailSubModule.GetStandardPlan,
    ECorpDetailSubModule.GetDomainName,
    ECorpDetailSubModule.GetWeixin,
    ECorpDetailSubModule.GetWeibo,
    ECorpDetailSubModule.GetToutiao,
  ],
  [ECorpDetailModule.Risk]: [
    ECorpDetailSubModule.GetCourtDecision,
    ECorpDetailSubModule.GetFilingInfo,
    ECorpDetailSubModule.GetCourtOpenAnnouncement,
    ECorpDetailSubModule.ShowDeliveryAnnouncement,
    ECorpDetailSubModule.GetCourtAnnouncement,
    ECorpDetailSubModule.GetPersonEnforced,
    ECorpDetailSubModule.GetDishonesty,
    ECorpDetailSubModule.GetEndCase,
    ECorpDetailSubModule.GetCorpConsumption,
    ECorpDetailSubModule.GetJudicialSale,
    ECorpDetailSubModule.ShowBankruptcy,
    ECorpDetailSubModule.GetEvaluation,
  ],
  [ECorpDetailModule.BusinessRisk]: [
    ECorpDetailSubModule.ShowViolationsPenalties,
    ECorpDetailSubModule.GetOperationException,
    ECorpDetailSubModule.GetCancelFiling,
    ECorpDetailSubModule.GetClearInfo,
    ECorpDetailSubModule.GetOwingTax,
    ECorpDetailSubModule.GetTaxIllegal,
    ECorpDetailSubModule.GetIllegal,
    ECorpDetailSubModule.GetNoStandard,
    ECorpDetailSubModule.GetInspection,
    ECorpDetailSubModule.GetDoubleRandom,
    ECorpDetailSubModule.GetProdRecall,
    ECorpDetailSubModule.ShowGuarantee,
    ECorpDetailSubModule.ShowStockMortgage,
    ECorpDetailSubModule.ShowPledgedStock,
    ECorpDetailSubModule.GetDefaultBond,
    ECorpDetailSubModule.ShowIntellectualPropertyRights,
  ],
  [ECorpDetailModule.History]: [
    ECorpDetailSubModule.HistoryCompany,
    ECorpDetailSubModule.HistoryShareholder,
    ECorpDetailSubModule.HistoryLegalPerson,
    ECorpDetailSubModule.HistoryInvest,
    ECorpDetailSubModule.HistoryDomainName,
    ECorpDetailSubModule.HistoryShowPledgedStock,
    ECorpDetailSubModule.GetLandMortgage,
    ECorpDetailSubModule.GetMultipleCertificate,
    ECorpDetailSubModule.GetVoidAgeStatement,
    ECorpDetailSubModule.Beneficiary,
    ECorpDetailSubModule.UltimateController,
    ECorpDetailSubModule.HistoryPatent,
  ],
}
