import { AIGRAPH_EXCEL_SHEET_KEYS } from '../../types'

export const sheetColumnIdsMap = {
  [AIGRAPH_EXCEL_SHEET_KEYS.BASIC]: [
    'graphName',
    'graphType',
    // 'mergeSameNameNodes',
    'groupByRelationType',
    'defaultGroupCount',
    // 'fisheyeEffect',
    // 'enableNodeJump',
  ],
  [AIGRAPH_EXCEL_SHEET_KEYS.RELATION]: [
    'index',
    'fromNodeName',
    'toNodeName',
    'relationshipType',
    'relationship',
    'operation',
  ],
  [AIGRAPH_EXCEL_SHEET_KEYS.NODE]: [
    'index',
    'nodeName',
    'registerStatus',
    'isListedOrBondIssuer',
    'country',
    'province',
    'city',
    'district',
    'nationalStandardIndustryCategory',
    'nationalStandardIndustryClass',
    'nationalStandardIndustrySubclass',
    'nationalStandardIndustryType',
    'operation',
  ],
}

export const cellConfig = {
  index: {
    name: '序号',
    type: 'text',
    editable: false,
    width: 50,
    fixed: 'left',
  },
  operation: {
    name: '操作',
    type: 'button',
    width: 80,
  },
  graphName: {
    name: '图谱名称',
    type: 'text',
    editable: true,
    width: 300,
  },
  graphType: {
    name: '图谱类型',
    type: 'select',
    width: 230,
    options: [
      { key: 1, name: '思维导图', type: 'brain', layout: 'mindmap', disabled: ['fisheyeEffect'] },
      {
        key: 2,
        name: '树结构图-上下结构',
        type: 'tree',
        layout: 'TB',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      {
        key: 3,
        name: '树结构图-左右结构',
        type: 'tree',
        layout: 'LR',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      {
        key: 4,
        name: '树结构图-上下紧凑结构',
        type: 'tree',
        layout: 'Compact',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      {
        key: 5,
        name: '树结构图-缩进结构',
        type: 'tree',
        layout: 'Indent',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      {
        key: 6,
        name: 'Dagre流程图-上下结构',
        type: 'detach',
        layout: 'TB',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      {
        key: 7,
        name: 'Dagre流程图-左右结构',
        type: 'detach',
        layout: 'LR',
        disabled: ['groupByRelationType', 'defaultGroupCount', 'fisheyeEffect'],
      },
      { key: 8, name: '脑图树-左右结构', type: 'brain', layout: 'LR', disabled: ['fisheyeEffect'] },
      {
        key: 9,
        name: '力导向布局图',
        type: 'force',
        layout: '',
        disabled: ['groupByRelationType', 'defaultGroupCount'],
      },
    ],
    defaultValue: 7,
    editable: true,
  },
  mergeSameNameNodes: {
    name: '相同节点名称合并',
    type: 'select',
    width: 150,
    options: [
      { key: true, name: '是' },
      { key: false, name: '否' },
    ],
    defaultValue: false,
    editable: true,
  },
  groupByRelationType: {
    name: '按关系类型聚合展示',
    type: 'select',
    width: 150,
    options: [
      { key: true, name: '是' },
      { key: false, name: '否' },
    ],
    defaultValue: false,
    editable: true,
  },
  defaultGroupCount: {
    name: '聚合节点默认展示条数',
    type: 'text',
    width: 160,
    defaultValue: 5,
    editable: true,
  },
  fisheyeEffect: {
    name: '鱼眼功能',
    type: 'select',
    width: 80,
    options: [
      { key: true, name: '开启' },
      { key: false, name: '屏蔽' },
    ],
    defaultValue: false,
    editable: true,
  },
  enableNodeJump: {
    name: '节点跳转',
    type: 'select',
    width: 80,
    options: [
      { key: true, name: '是' },
      { key: false, name: '否' },
    ],
    defaultValue: true,
    editable: true,
  },
  fromNodeName: {
    name: '源节点名称',
    type: 'text',
    editable: true,
    width: 300,
    fixed: 'left',
  },
  toNodeName: {
    name: '目标节点名称',
    type: 'text',
    editable: true,
    width: 300,
  },
  relationshipType: {
    name: '关系类型',
    type: 'text',
    editable: true,
    width: 300,
  },
  relationship: {
    name: '关系描述',
    type: 'text',
    editable: true,
    width: 200,
  },
  nodeName: {
    name: '节点名称',
    type: 'text',
    editable: true,
    width: 300,
    fixed: 'left',
  },
  registerStatus: {
    name: '企业存续状态',
    type: 'text',
    editable: true,
    width: 120,
  },
  isListedOrBondIssuer: {
    name: '是否上市或发债',
    type: 'select',
    editable: true,
    width: 150,
    options: [
      { key: '1', name: '上市企业' },
      { key: '2', name: '发债企业' },
      { key: '0', name: '非上市发债企业' },
    ],
  },
  country: {
    name: '国家',
    type: 'text',
    editable: true,
    width: 150,
  },
  province: {
    name: '省份',
    type: 'text',
    editable: true,
    width: 150,
  },
  city: {
    name: '城市',
    type: 'text',
    editable: true,
    width: 100,
  },
  district: {
    name: '区县',
    type: 'text',
    editable: true,
    width: 100,
  },
  nationalStandardIndustryCategory: {
    name: '国标行业-门类',
    type: 'text',
    editable: true,
    width: 200,
  },
  nationalStandardIndustryClass: {
    name: '国标行业-大类',
    type: 'text',
    editable: true,
    width: 200,
  },
  nationalStandardIndustrySubclass: {
    name: '国标行业-中类',
    type: 'text',
    editable: true,
    width: 200,
  },
  nationalStandardIndustryType: {
    name: '国标行业-小类',
    type: 'text',
    editable: true,
    width: 200,
  },
}
