import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoSH: CorpBasicInfo = {
  anotherNames: null,
  areaCode: '030203',
  biz_reg_no: '',
  bus_address: '',
  business_scope:
    '一、帮助和保护我协会会员的合法权益、帮助困难职工走出困境组织或参与到社会各类公益活动；帮助有困难的同事、贫困的乡亲失学的优秀学子和社会底层挣扎的许多男势群体一、太力发展公益活动志愿者队伍，倡导良好社会道德风尚三、促进会员间的交流，为会员的慈善活动提供咨询和帮助；四、在相关范围，依法募集慈善资金，接受企业、个人的赞助',
  cancel_date: '',
  configType: 'NGO',
  corp_id: '1225626853',
  corp_name: '贵阳市花溪农村商业银行爱心协会',
  corp_old_id: '',
  corp_type: '--',
  corp_type_id: 160900000,
  credit_code: '51520111059061043R',
  domainCount: 0,
  eng_name: 'Love Association of Huaxi Rural Commercial Bank, Guiyang City',
  formerNameList: [],
  gbIndustryList: [],
  industryGbFold: '',
  industryWindFold: '',
  industryWindFoldCode: '',
  issue_date: '',
  legal_person_id: 'W00000000000006YF0GC',
  legal_person_name: '吴勇',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2018-06-05',
  oper_period_end: '2022-06-04',
  org_code: '51520111059061043R',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  province: '贵州省',
  reg_address: '阳光社区清溪路209号',
  reg_authority: '贵阳市花溪区民政局',
  reg_capital: 5,
  reg_date: '2012-11-29',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '',
  seIndustriesCount: 0,
  state: '存续',
  taxIdNo: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
