import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoNGO: CorpBasicInfo = {
  anotherNames: null,
  areaCode: '030301',
  biz_reg_no: '',
  bus_address: '',
  business_scope:
    '（一）资助贫困家庭、残疾人改善生活；（二）资助贫困病患就医；（三）资助贫困学生就学；（四）资助贫困学校基础建设改善；（五）资助自然灾害等突发事件造成损害的救助。',
  cancel_date: '',
  configType: 'NGO',
  corp_id: '1226065840',
  corp_name: '北京小米公益基金会',
  corp_old_id: '',
  corp_type: '--',
  corp_type_id: 160900000,
  credit_code: '53110000MJ0179644C',
  domainCount: 0,
  eng_name: 'Beijing Xiaomi Charity Foundation',
  formerNameList: [],
  gbIndustryList: [],
  industryGbFold: '',
  industryWindFold: '',
  industryWindFoldCode: '',
  issue_date: '',
  legal_person_id: 'W000000000000072JIDQ',
  legal_person_name: '刘德',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2020-03-26',
  oper_period_end: '2024-02-02',
  org_code: '53110000MJ0179644C',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  province: '北京市',
  reg_address: '北京市海淀区西二旗中路33号院6号楼14层001号',
  reg_authority: '北京市民政局',
  reg_capital: 10000000,
  reg_date: '2019-02-03',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '',
  seIndustriesCount: 0,
  state: '存续',
  taxIdNo: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
