import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoLS: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030301',
  biz_reg_no: '21101201930020735',
  bus_address: '',
  business_scope:
    '北京德佑谦律师事务所为宋凯栋律师设立的个人律师事务所，以专业、严谨为基石，秉承“德”“谦”相佑，为客户提供“优质、高效”的法律服务为宗旨。本所以投融资、民商事案件、行政案件、刑事案件、公司企业法律顾问等为专业领域，提供诉讼、仲裁、非诉法律服务。充分发挥服务专业、工作勤勉、守德敬业精神，以达服务客户的满意。',
  cancel_date: '',
  configType: '00',
  corp_id: '1248823373',
  corp_name: '北京德佑谦律师事务所',
  corp_old_id: '',
  corp_type: '--',
  corp_type_id: 912034101,
  credit_code: '31110000MD02212308',
  domainCount: 0,
  eng_name: 'Beijing Deyouqian Law Firm',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'L',
      industryName: '租赁和商务服务业',
      type: 'gb',
      windId: '1248823373',
    },
    {
      industryCode: 'L72',
      industryName: '商务服务业',
      type: 'gb',
      windId: '1248823373',
    },
    {
      industryCode: 'L723',
      industryName: '法律服务',
      type: 'gb',
      windId: '1248823373',
    },
    {
      industryCode: 'L7231',
      industryName: '律师及相关法律服务',
      type: 'gb',
      windId: '1248823373',
    },
  ],
  industryGbFold: '租赁和商务服务业-商务服务业-法律服务-律师及相关法律服务',
  industryWindFold: '工业-商业和专业服务',
  industryWindFoldCode: '2020',
  issue_date: '',
  legal_person_id: 'W000000000000072H5Q9',
  legal_person_name: '宋凯栋',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '',
  oper_period_end: '',
  org_code: '31110000MD02212308',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '',
  province: '北京市',
  reg_address: '北京市丰台区方庄南路15号楼4层1座524房（本房屋为复式，本律所占其中一层）',
  reg_authority: '',
  reg_capital: 50,
  reg_date: '2019-05-05',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '正常',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
