import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoFPC: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030504',
  biz_reg_no: '632122NA000396X',
  bus_address: '民和县川口镇米拉湾村',
  business_scope:
    '大豆、玉米、百合、党参、柴胡、苗木种植、销售；为本社成员提供技术服务（依法须经批准的项目，经相关部门批准后方可开展经营活动）',
  cancel_date: '20230621',
  configType: 'FPC',
  corp_id: '1002954109',
  corp_name: '民和勤丰种植专业合作社',
  corp_old_id: '',
  corp_type: '农民专业合作社',
  corp_type_id: 298020000,
  credit_code: '936321225950146891',
  domainCount: 0,
  employee_num: 1,
  eng_name: 'Minhe Qinfeng Planting Professional Cooperative',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'A',
      industryName: '农、林、牧、渔业',
      type: 'gb',
      windId: '1002954109',
    },
    {
      industryCode: 'A01',
      industryName: '农业',
      type: 'gb',
      windId: '1002954109',
    },
    {
      industryCode: 'A012',
      industryName: '豆类、油料和薯类种植',
      type: 'gb',
      windId: '1002954109',
    },
    {
      industryCode: 'A0121',
      industryName: '豆类种植',
      type: 'gb',
      windId: '1002954109',
    },
  ],
  industryGbFold: '农、林、牧、渔业-农业-豆类、油料和薯类种植-豆类种植',
  industryWindFold: '日常消费-食品饮料-食品-农产品',
  industryWindFoldCode: '30202010',
  issue_date: '2023-06-21',
  legal_person_id: '79CE3E24090DA14B5ED3BD3FAA3A5905',
  legal_person_name: '李万存',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2012-07-12',
  oper_period_end: '',
  org_code: '936321225950146891',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '民和县川口镇米拉湾村',
  province: '青海省',
  reg_address: '民和县川口镇米拉湾村',
  reg_authority: '民和回族土族自治县市场监督管理局',
  reg_capital: 400,
  reg_date: '2012-07-12',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '20230621',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '注销',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
