import { IndicatorBulkImportApi } from '@/BulkImport'
import { ApiCodeForWfc, IndicatorCorpSearchRes } from 'gel-api'

export const searchMock: IndicatorCorpSearchRes[] = [
  {
    queryText: null,
    corpId: '1047934153',
    corpName: '小米科技有限责任公司',
    engName: 'XIAOMI INC.',
    creditCode: '91110108551385082Q',
    artificialPerson: '雷军',
    formerNames: ['北京小米科技有限责任公司'],
    dataFrom: '298010000',
    region: '北京市 海淀区',
    matched: null,
    formerName: '北京小米科技有限责任公司',
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1226065840',
    corpName: '北京小米公益基金会',
    engName: 'Beijing Xiaomi Charity Foundation',
    creditCode: '53110000MJ0179644C',
    artificialPerson: '刘德',
    formerNames: null,
    dataFrom: '160900000',
    region: '北京市 海淀区',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1374463216',
    corpName: '小米汽车科技有限公司',
    engName: 'XIAOMI EV TECHNOLOGY CO., LTD.',
    creditCode: '91110400MA7D6T4W01',
    artificialPerson: '雷军',
    formerNames: null,
    dataFrom: '298010000',
    region: '北京市',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1368957865',
    corpName: '小米汽车有限公司',
    engName: 'Xiaomi Automobile Co., Ltd',
    creditCode: '91110400MA04ENG447',
    artificialPerson: '雷军',
    formerNames: null,
    dataFrom: '298010000',
    region: '北京市',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1046396352',
    corpName: '小米通讯技术有限公司',
    engName: 'Xiaomi Communications Co., Ltd.',
    creditCode: '91110108558521630L',
    artificialPerson: '屈恒',
    formerNames: ['北京紫米科技发展有限公司', '北京小米通讯技术有限公司'],
    dataFrom: '298010000',
    region: '北京市 海淀区',
    matched: null,
    formerName: '北京紫米科技发展有限公司',
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1197122646',
    corpName: '小米科技(武汉)有限公司',
    engName: 'XIAOMI TECHNOLOGY (WUHAN) CO., LTD.',
    creditCode: '91420100MA4KWE6L5W',
    artificialPerson: '曾学忠',
    formerNames: null,
    dataFrom: '298010000',
    region: '湖北省 武汉市',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1376394141',
    corpName: '小米智能技术有限公司',
    engName: 'Xiaomi Intelligent Technology Co., Ltd.',
    creditCode: '91110400MA7FTTQJ1B',
    artificialPerson: '雷军',
    formerNames: null,
    dataFrom: '298010000',
    region: '北京市',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1376403120',
    corpName: '小米景曦科技有限公司',
    engName: 'Xiaomi Jingxi Technology Co., Ltd',
    creditCode: '91110400MA7GDCNR5C',
    artificialPerson: '刘凌迪',
    formerNames: null,
    dataFrom: '298010000',
    region: '北京市',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1030208713',
    corpName: '北京小米移动软件有限公司',
    engName: 'BEIJING XIAOMI MOBILE SOFTWARE CO., LTD.',
    creditCode: '91110108596084056A',
    artificialPerson: '屈恒',
    formerNames: null,
    dataFrom: '298010000',
    region: '北京市 海淀区',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
  {
    queryText: null,
    corpId: '1199513089',
    corpName: '小米之家商业有限公司',
    engName: 'Xiaomi Home Commercial Co., Ltd',
    creditCode: '91420100MA4KUU2U6N',
    artificialPerson: '孙波',
    formerNames: null,
    dataFrom: '298010000',
    region: '湖北省 武汉市 洪山区',
    matched: null,
    formerName: null,
    source: 1,
    creditCodeMatch: null,
    formerNamesMatch: null,
    engNameMatched: null,
    corpNameMatched: null,
  },
]

export const corpSearchMock: IndicatorBulkImportApi['searchCompanies'] = async () => ({
  Data: {
    list: searchMock,
    page: {
      pageNo: 1,
      pageSize: 10,
      total: 10,
    },
  },
  ErrorCode: ApiCodeForWfc.SUCCESS,
  ErrorMessage: '',
  status: '200',
})
