import { IntellectualTypeEnum, PatentTypeEnum } from '@/handle/link'

export const LinksTableDataSource = [
  {
    companyCode: '1035946278',
    companyName: '上海沪北物流发展有限公司',
    tenderingName: '执法船中标公告',
    tenderingId: '386520476',
    groupName: '小米系',
    groupId: '2010500722',
    productName: '小米服务通',
    productId: '4723933',
    email: 'wind@qq.com',
    browserName: '智能家居',
    browserType: '产品',
    browserValue: '智能家居',
    riskName: '法院公告',
    riskId: '99514453',
    intellectualName: '专利:发明申请',
    intellectualId: '49308729',
    intellectualType: IntellectualTypeEnum.PATENT,
    intellectualExtraType: PatentTypeEnum.FMSQ,
    feturedName: 'PEVC被投企业',
    feturedId: '2010100686',
  },
  {
    companyCode: '1002532464',
    companyName: '上海久通融资租赁有限公司',
    tenderingName: '租赁服务中标公示',
    tenderingId: '386635084',
    groupName: '海信系',
    groupId: '2010506448',
    productName: '平安地铁',
    productId: '287135',
    email: '12137128937123',
    riskName: '开庭公告',
    riskId: '364433050',
    intellectualName: '专利:授权发明',
    intellectualId: '31673077',
    intellectualType: IntellectualTypeEnum.PATENT,
    intellectualExtraType: PatentTypeEnum.SQFM,
    feturedName: 'TopBrand中国品牌500强',
    feturedId: '10000744',
  },
  {
    companyName: '无公司鏈接',
    tenderingName: '无招投標鏈接',
    groupName: '无集團西鏈接',
    productName: '无产品链接',
    email: '邮箱会验证',
    riskName: '送达公告',
    riskId: '363145433',
    intellectualName: '专利:实用新型',
    intellectualId: '190407840',
    intellectualType: IntellectualTypeEnum.PATENT,
    intellectualExtraType: PatentTypeEnum.SYXX,
    feturedName: '中国酒店集团规模TOP50',
    feturedId: '20000302',
  },
  {
    companyName: '',
    tenderingName: '',
    groupName: '',
    productName: '',
    email: '',
    riskName: '裁判文书',
    riskId: '181689798',
    intellectualName: '专利:外观设计',
    intellectualId: '6082418',
    intellectualType: IntellectualTypeEnum.PATENT,
    intellectualExtraType: PatentTypeEnum.WGSJ,
  },
  {
    companyName: '',
    tenderingName: '',
    groupName: '',
    productName: '',
    email: '',
    riskName: '被执行人',
    riskId: '226586015',
    intellectualName: '商标',
    intellectualId: '81227457',
    intellectualType: IntellectualTypeEnum.BRAND,
  },
]