// 绿色低碳技术
export const globalLowCarbon = [
  {
    code: '8915359018',
    level: 1,
    name: '节能与能量回收利用',
    nameEn: 'Energy saving and energy recovery',
    node: [
      {
        code: '8915359022',
        level: 2,
        name: '节气技术',
        nameEn: 'Gas saving technology',
        node: [
          { code: '8915359023', level: 3, name: '燃料预混技术', nameEn: 'Fuel premixing technology', node: [] },
          { code: '8915359024', level: 3, name: '燃料预热技术', nameEn: 'Fuel preheating technology', node: [] },
          { code: '8915357823', level: 3, name: '气体燃烧器', nameEn: 'Gas burners', node: [] },
          {
            code: '8915357824',
            level: 3,
            name: '燃烧优化技术',
            nameEn: 'Combustion optimization technology',
            node: [],
          },
        ],
      },
      {
        code: '8915357819',
        level: 2,
        name: '节油技术',
        nameEn: 'Fuel-saving technology',
        node: [
          { code: '8915359021', level: 3, name: '燃料回收技术', nameEn: 'Fuel recovery technology', node: [] },
          { code: '8915359020', level: 3, name: '燃料控制技术', nameEn: 'Fuel control technology', node: [] },
          {
            code: '8915359019',
            level: 3,
            name: '燃烧发动机怠速控制',
            nameEn: 'Combustion engine idle control',
            node: [],
          },
          {
            code: '8915357822',
            level: 3,
            name: '燃烧优化技术',
            nameEn: 'Combustion optimization technology',
            node: [],
          },
          { code: '8915357821', level: 3, name: '电气控制技术', nameEn: 'Electrical control technology', node: [] },
          {
            code: '8915357820',
            level: 3,
            name: '气体燃料内燃机',
            nameEn: 'Gas fuel internal combustion engine',
            node: [],
          },
        ],
      },
      { code: '8915357827', level: 2, name: '能量回收利用', nameEn: 'Energy recovery', node: [] },
      {
        code: '8915357825',
        level: 2,
        name: '节电技术',
        nameEn: 'Power-saving technology',
        node: [
          { code: '8915359025', level: 3, name: '新型照明', nameEn: 'New lighting', node: [] },
          { code: '8915359026', level: 3, name: '智能电网', nameEn: 'Smart grid', node: [] },
          { code: '8915357826', level: 3, name: '用电控制', nameEn: 'Electricity control', node: [] },
        ],
      },
    ],
  },
  {
    code: '8915359027',
    level: 1,
    name: '清洁能源',
    nameEn: 'Clean energy',
    node: [
      {
        code: '8915359030',
        level: 2,
        name: '太阳能',
        nameEn: 'solar energy',
        node: [
          {
            code: '8915359031',
            level: 3,
            name: '光伏转换',
            nameEn: 'PV conversion',
            node: [
              {
                code: '8915359032',
                level: 4,
                name: '有机化合物太阳能电池',
                nameEn: 'Organic compound solar cells',
                node: [],
              },
              { code: '8915359034', level: 4, name: '光伏系统', nameEn: 'Photovoltaic systems', node: [] },
              {
                code: '8915359033',
                level: 4,
                name: '多元化合物太阳能电池',
                nameEn: 'Multi-compound solar cells',
                node: [],
              },
              {
                code: '8915357834',
                level: 4,
                name: '太阳能电池封装、模块、零部件等',
                nameEn: 'Solar cell packages, modules, components, etc',
                node: [],
              },
              { code: '8915357833', level: 4, name: '硅太阳能电池', nameEn: 'Silicon solar cells', node: [] },
              {
                code: '8915357832',
                level: 4,
                name: '染料敏化太阳能电池',
                nameEn: 'Dye-sensitized solar cells',
                node: [],
              },
            ],
          },
          { code: '8915357835', level: 3, name: '太阳能机械', nameEn: 'Solar machinery', node: [] },
          { code: '8915357831', level: 3, name: '光热转换', nameEn: 'Photothermal conversion', node: [] },
        ],
      },
      {
        code: '8915359045',
        level: 2,
        name: '生物质能',
        nameEn: 'Biomass',
        node: [
          {
            code: '8915359046',
            level: 3,
            name: '生物发酵或厌氧处理',
            nameEn: 'Biological fermentation or anaerobic treatment',
            node: [],
          },
          {
            code: '8915357847',
            level: 3,
            name: '生物质高温分解或气化',
            nameEn: 'Biomass pyrolysis or gasification',
            node: [],
          },
          { code: '8915357846', level: 3, name: '生物燃料', nameEn: 'Biofuels', node: [] },
        ],
      },
      {
        code: '8915359039',
        level: 2,
        name: '地热能',
        nameEn: 'geothermal energy',
        node: [
          {
            code: '8915359040',
            level: 3,
            name: '地热产生机械能',
            nameEn: 'Geothermal heat produces mechanical energy',
            node: [],
          },
          { code: '8915357840', level: 3, name: '地热直接利用', nameEn: 'Direct use of geothermal energy', node: [] },
        ],
      },
      {
        code: '8915359035',
        level: 2,
        name: '风能',
        nameEn: 'wind energy',
        node: [
          { code: '8915359036', level: 3, name: '风力机械', nameEn: 'Wind machinery', node: [] },
          { code: '8915357836', level: 3, name: '风力发电', nameEn: 'Wind power', node: [] },
        ],
      },
      {
        code: '8915357828',
        level: 2,
        name: '水能',
        nameEn: 'Water',
        node: [
          {
            code: '8915359028',
            level: 3,
            name: '水力发电',
            nameEn: 'hydropower',
            node: [
              { code: '8915359029', level: 4, name: '水力发电站', nameEn: 'Hydroelectric power stations', node: [] },
              { code: '8915357829', level: 4, name: '流体发动机', nameEn: 'Fluid engines', node: [] },
            ],
          },
          { code: '8915357830', level: 3, name: '水力机械', nameEn: 'Hydraulic machinery', node: [] },
        ],
      },
      {
        code: '8915359047',
        level: 2,
        name: '核能',
        nameEn: 'nuclear energy',
        node: [
          { code: '8915359049', level: 3, name: '核能发电', nameEn: 'Nuclear power generation', node: [] },
          { code: '8915359048', level: 3, name: '核裂变', nameEn: 'nuclear fission', node: [] },
          { code: '8915357849', level: 3, name: '核动力', nameEn: 'nuclear power', node: [] },
          { code: '8915357848', level: 3, name: '核聚变', nameEn: 'nuclear fusion', node: [] },
        ],
      },
      {
        code: '8915357837',
        level: 2,
        name: '海洋能',
        nameEn: 'Ocean energy',
        node: [
          {
            code: '8915359037',
            level: 3,
            name: '潮汐能或波能',
            nameEn: 'Tidal or wave energy',
            node: [
              {
                code: '8915359038',
                level: 4,
                name: '潮汐能或波能发电站',
                nameEn: 'Tidal or wave power stations',
                node: [],
              },
              { code: '8915357838', level: 4, name: '潮汐能或波能发动机', nameEn: 'Tidal or wave engines', node: [] },
            ],
          },
          {
            code: '8915357839',
            level: 3,
            name: '海洋热能转换(OTEC)',
            nameEn: 'Ocean Thermal Energy Conversion (OTEC)',
            node: [],
          },
        ],
      },
      {
        code: '8915357841',
        level: 2,
        name: '氢能',
        nameEn: 'Hydrogen',
        node: [
          { code: '8915359044', level: 3, name: '氢燃料电池', nameEn: 'Hydrogen fuel cells', node: [] },
          { code: '8915359041', level: 3, name: '制氢技术', nameEn: 'Hydrogen production technology', node: [] },
          { code: '8915357845', level: 3, name: '氢制冷', nameEn: 'Hydrogen refrigeration', node: [] },
          {
            code: '8915357842',
            level: 3,
            name: '储氢技术',
            nameEn: 'Hydrogen storage technology',
            node: [
              { code: '8915359043', level: 4, name: '无机储氢', nameEn: 'Inorganic hydrogen storage', node: [] },
              { code: '8915359042', level: 4, name: '液化储氢', nameEn: 'Liquefaction hydrogen storage', node: [] },
              { code: '8915357844', level: 4, name: '有机储氢', nameEn: 'Organic hydrogen storage', node: [] },
              { code: '8915357843', level: 4, name: '合金储氢', nameEn: 'Alloy hydrogen storage', node: [] },
            ],
          },
        ],
      },
    ],
  },
  {
    code: '8915359055',
    level: 1,
    name: '温室气体捕集利用封存',
    nameEn: 'Greenhouse gas capture utilization sequestration',
    node: [
      {
        code: '8915357856',
        level: 2,
        name: 'CO2 的捕集利用封存',
        nameEn: 'CO2 capture is used for storage',
        node: [
          {
            code: '8915359056',
            level: 3,
            name: '碳捕集',
            nameEn: 'Carbon capture',
            node: [
              { code: '8915359058', level: 4, name: '化学净化', nameEn: 'Chemical purification', node: [] },
              { code: '8915359057', level: 4, name: '吸收分离', nameEn: 'Absorption separation', node: [] },
              {
                code: '8915359059',
                level: 4,
                name: '其他碳捕集技术',
                nameEn: 'Other carbon capture technologies',
                node: [],
              },
              { code: '8915357859', level: 4, name: '生物捕集', nameEn: 'Biotrap', node: [] },
              {
                code: '8915357858',
                level: 4,
                name: '液化/固化分离',
                nameEn: 'Liquefaction/curing separation',
                node: [],
              },
              { code: '8915357857', level: 4, name: '吸附分离', nameEn: 'Adsorption separation', node: [] },
            ],
          },
          {
            code: '8915359063',
            level: 3,
            name: '碳封存',
            nameEn: 'Carbon sequestration',
            node: [
              { code: '8915359065', level: 4, name: '其他封存技术', nameEn: 'Other sealing techniques', node: [] },
              { code: '8915359064', level: 4, name: '容器封存技术', nameEn: 'Container storage technology', node: [] },
              {
                code: '8915357865',
                level: 4,
                name: '封存监测技术',
                nameEn: 'Sequestration monitoring technology',
                node: [],
              },
              {
                code: '8915357864',
                level: 4,
                name: '地下封存技术',
                nameEn: 'Underground storage technology',
                node: [],
              },
            ],
          },
          {
            code: '8915357860',
            level: 3,
            name: '碳利用',
            nameEn: 'Carbon utilization',
            node: [
              { code: '8915359061', level: 4, name: '加氢催化', nameEn: 'Hydrocatalysis', node: [] },
              { code: '8915359060', level: 4, name: 'CO2 化学品', nameEn: 'CO2 chemicals', node: [] },
              { code: '8915359062', level: 4, name: '消防', nameEn: 'firefighting', node: [] },
              { code: '8915357863', level: 4, name: '制冷', nameEn: 'refrigeration', node: [] },
              { code: '8915357862', level: 4, name: '食品', nameEn: 'foodstuff', node: [] },
              {
                code: '8915357861',
                level: 4,
                name: '混凝土建材等',
                nameEn: 'concrete building materials, etc',
                node: [],
              },
            ],
          },
        ],
      },
      {
        code: '8915357866',
        level: 2,
        name: '其它温室气体减排',
        nameEn: 'Other greenhouse gas emission reductions',
        node: [
          { code: '8915359067', level: 3, name: '含氟气体减排技术', nameEn: 'F-gas reduction technology', node: [] },
          { code: '8915359066', level: 3, name: '甲烷减排技术', nameEn: 'Methane abatement technologies', node: [] },
          {
            code: '8915357867',
            level: 3,
            name: '氧化亚氮减排技术',
            nameEn: 'Nitrous oxide emission reduction technology',
            node: [],
          },
        ],
      },
    ],
  },
  {
    code: '8915358997',
    level: 1,
    name: '化石能源降碳技术',
    nameEn: 'Fossil energy carbon reduction technology',
    node: [
      {
        code: '8915357811',
        level: 2,
        name: '石油及天然气清洁化',
        nameEn: 'Clean oil and gas',
        node: [
          {
            code: '8915359014',
            level: 3,
            name: '清洁石油化工及转化',
            nameEn: 'Clean petrochemical industry and conversion',
            node: [
              { code: '8915359015', level: 4, name: '炼化制氢', nameEn: 'Refining hydrogen production', node: [] },
              {
                code: '8915357816',
                level: 4,
                name: '先进炼油技术（包括组分炼油，分子炼油）',
                nameEn: 'Advanced refining technology (including component refining, molecular refining)',
                node: [],
              },
              { code: '8915357815', level: 4, name: '加氢技术', nameEn: 'Hydrogenation technology', node: [] },
            ],
          },
          {
            code: '8915359016',
            level: 3,
            name: '天然气开采与转化',
            nameEn: 'Natural gas extraction and conversion',
            node: [
              {
                code: '8915359017',
                level: 4,
                name: '天然气制液体燃料',
                nameEn: 'Natural gas to liquid fuel',
                node: [],
              },
              { code: '8915357818', level: 4, name: '天然气制甲醇', nameEn: 'Natural gas to methanol', node: [] },
              {
                code: '8915357817',
                level: 4,
                name: '天然气低碳开采技术',
                nameEn: 'Natural gas low-carbon extraction technology',
                node: [],
              },
            ],
          },
          {
            code: '8915359011',
            level: 3,
            name: '石油低碳开采',
            nameEn: 'Low-carbon extraction of oil',
            node: [
              {
                code: '8915359013',
                level: 4,
                name: '智能控制技术',
                nameEn: 'Intelligent control technology',
                node: [],
              },
              {
                code: '8915357812',
                level: 4,
                name: '油田高效开采技术',
                nameEn: 'Oilfield efficient extraction technology',
                node: [],
              },
              {
                code: '8915357814',
                level: 4,
                name: '其他低碳开采技术',
                nameEn: 'Other low-carbon mining technologies',
                node: [],
              },
              { code: '8915357813', level: 4, name: '瓦斯利用技术', nameEn: 'Gas utilization technology', node: [] },
              { code: '8915359012', level: 4, name: 'CO2 驱油技术', nameEn: 'CO2 flooding technology', node: [] },
            ],
          },
        ],
      },
      {
        code: '8915357798',
        level: 2,
        name: '煤炭清洁高效利用',
        nameEn: 'Clean and efficient use of coal',
        node: [
          {
            code: '8915357809',
            level: 3,
            name: '煤化工（气化，液化和焦化）',
            nameEn: 'Coal chemical industry (gasification, liquefaction and coking)',
            node: [
              {
                code: '8915357810',
                level: 4,
                name: '煤制化学品（包括煤制甲醇，煤制烯烃，煤制芳烃）',
                nameEn: 'Coal-to-chemicals (including coal-to-methanol, coal-to-olefins, coal-to-aromatics)',
                node: [],
              },
              { code: '8915359010', level: 4, name: '煤气化', nameEn: 'Coal gasification', node: [] },
              { code: '8915359009', level: 4, name: '煤制燃料', nameEn: 'Coal-based fuels', node: [] },
            ],
          },
          {
            code: '8915357806',
            level: 3,
            name: '工业用煤',
            nameEn: 'Industrial coal',
            node: [
              { code: '8915357808', level: 4, name: '烟气处理技术', nameEn: 'Flue gas treatment technology', node: [] },
              {
                code: '8915357807',
                level: 4,
                name: '高效燃烧技术',
                nameEn: 'Efficient combustion technology',
                node: [],
              },
              { code: '8915359007', level: 4, name: '干熄焦技术', nameEn: 'Dry quenching technology', node: [] },
              {
                code: '8915359006',
                level: 4,
                name: '煤粉制备技术',
                nameEn: 'Pulverized coal preparation technology',
                node: [],
              },
              {
                code: '8915359008',
                level: 4,
                name: '工业炉节能改造',
                nameEn: 'Energy-saving transformation of industrial furnaces',
                node: [],
              },
            ],
          },
          {
            code: '8915358998',
            level: 3,
            name: '煤炭低碳开采',
            nameEn: 'Low-carbon mining of coal',
            node: [
              { code: '8915357801', level: 4, name: '井下处理技术', nameEn: 'Downhole treatment technology', node: [] },
              {
                code: '8915357800',
                level: 4,
                name: '资源综合利用技术',
                nameEn: 'Comprehensive utilization technology of resources',
                node: [],
              },
              {
                code: '8915357803',
                level: 4,
                name: '设备节能改造技术',
                nameEn: 'Equipment energy-saving transformation technology',
                node: [],
              },
              {
                code: '8915357802',
                level: 4,
                name: '先进绿色选煤技术',
                nameEn: 'Advanced green coal preparation technology',
                node: [],
              },
              { code: '8915358999', level: 4, name: '褐煤开采', nameEn: 'Lignite mining', node: [] },
              {
                code: '8915357799',
                level: 4,
                name: '保水开采技术',
                nameEn: 'Water retention mining technology',
                node: [],
              },
              {
                code: '8915359001',
                level: 4,
                name: '智能控制技术',
                nameEn: 'Intelligent control technology',
                node: [],
              },
              {
                code: '8915359000',
                level: 4,
                name: '地下气化技术',
                nameEn: 'Underground gasification technology',
                node: [],
              },
              {
                code: '8915359002',
                level: 4,
                name: '水源热泵技术',
                nameEn: 'Water source heat pump technology',
                node: [],
              },
            ],
          },
          {
            code: '8915359003',
            level: 3,
            name: '煤炭发电',
            nameEn: 'Coal power generation',
            node: [
              { code: '8915357805', level: 4, name: '热电联产', nameEn: 'Combined heat and power', node: [] },
              {
                code: '8915357804',
                level: 4,
                name: '整体煤气化联合循环发电系统',
                nameEn: 'Integrated coal gasification combined cycle power generation system',
                node: [],
              },
              { code: '8915359005', level: 4, name: '分布式发电', nameEn: 'Distributed generation', node: [] },
              {
                code: '8915359004',
                level: 4,
                name: '超临界发电技术',
                nameEn: 'Supercritical power generation technology',
                node: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    code: '8915357850',
    level: 1,
    name: '储能技术',
    nameEn: 'Energy storage technology',
    node: [
      {
        code: '8915359053',
        level: 2,
        name: '电化学储能',
        nameEn: 'Electrochemical energy storage',
        node: [
          { code: '8915359054', level: 3, name: '电容器', nameEn: 'capacitor', node: [] },
          {
            code: '8915357855',
            level: 3,
            name: '车用电池或电容器',
            nameEn: 'Automotive batteries or capacitors',
            node: [],
          },
          { code: '8915357854', level: 3, name: '二次电池', nameEn: 'Secondary battery', node: [] },
        ],
      },
      {
        code: '8915359050',
        level: 2,
        name: '机械储能',
        nameEn: 'Mechanical energy storage',
        node: [
          { code: '8915359051', level: 3, name: '动能存储', nameEn: 'Kinetic energy storage', node: [] },
          { code: '8915357851', level: 3, name: '压缩空气', nameEn: 'pressurized air', node: [] },
        ],
      },
      {
        code: '8915357852',
        level: 2,
        name: '热储能',
        nameEn: 'Thermal energy storage',
        node: [
          { code: '8915359052', level: 3, name: '储热设备', nameEn: 'Heat storage equipment', node: [] },
          { code: '8915357853', level: 3, name: '储热材料', nameEn: 'Heat storage materials', node: [] },
        ],
      },
    ],
  },
]
