export { getTagConfig, type TagCfgByModule } from './config'
export { getCorpTagConfig } from './corpTagConfig'
export { getCorpTagClickHandler, getCorpTagUrl, handleJumpCorpTag, type CorpTagUrlObj } from './corpTagUrl'
export { TagsModule } from './module'
export { getRiskTagCfg } from './risk'
export type { TagColors, TagSizes, TagTypes } from './type'
export { getPublicSentimentTagColorAndType, splitTags2ArrByModule, splitTags2MapByModule } from './util'
