import { corpDetailHisEquityPledge, corpDetailInvestigationFiling, corpDetailLandInfo } from '@/handle/corpModuleCfg'
import intl from '@/utils/intl'
import { ICorpMenuCfg } from './type.ts'

export const CompanyDetailZFMenus: ICorpMenuCfg = {
  // 事业单位&政府机关
  overview: {
    // 基础信息
    title: intl('138663', '基础信息'),
    showList: [
      'showCompanyInfo',
      'showshareholderchange',
      'showCompanyBranchInfo',
      'showControllerCompany',
      'showDirectInvestment',
      'showHeadOffice',
      'showCompanyChange',
    ],
    showName: [
      intl('138588', ' 工商信息 '),
      intl('451218', ' 股东变更 '),
      intl('138183', '分支机构'),
      intl('451208', '控股企业'),
      intl('138724', '对外投资'),
      intl('204942', '总公司'),
      intl('451225', '工商变更'),
    ],
    numArr: [
      true,
      'shareholder_change_num',
      'new_branch_num',
      'e_holdingEnterprise_count',
      'foreign_invest_num',
      'headerquarters_num',
      'change_record_num',
    ],
  },
  financing: {
    // 金融行为
    title: intl('261899', '金融行为'),
    showList: ['showBond', 'showInvestmentAgency', 'showInvestmentEvent', 'pvecOut', 'showGrantcredit', 'absinfo'],
    showName: [
      intl('138664', '发行债券'),
      intl('451212', '投资机构'),
      intl('40559', '投资事件'),
      intl('437444', 'PEVC退出'),
      intl('138684', '银行授信'),
      intl('138122', 'ABS信息'),
    ],
    numArr: [
      'sharedbonds_num',
      'invest_orgs_num',
      'invest_events_num',
      'pevcquit_num',
      'banktrust_num',
      'companyabs_num',
    ],
  },
  bussiness: {
    // 经营状况
    title: intl('451255', '经营状况'),
    showList: ['showApp', 'majorGovProject', 'biddingInfo', 'jobs', 'showLandInfo', 'getfundpe', 'showCustomersSup'],
    showName: [
      intl('451258', 'APP产品'),
      intl('314693', '政府重大项目'),
      intl('271633', '招投标'),
      intl('138356', '招聘'),
      intl('114647', '土地信息'),
      intl('119142', '私募基金'),
      intl('205516', '客户和供应商'),
    ],
    numArr: [
      'product_num',
      'gov_major_project_num',
      true,
      'recruitt_num',
      corpDetailLandInfo.modelNum,
      'fundpe_num',
      ['customer_num', 'supplier_num'],
    ],
  },
  qualifications: {
    //资质荣誉
    title: intl('284064', '资质荣誉'),
    showList: [
      'getpermission02',
      'getpermission',
      'credit',
      'jrxx',
      'getfinanciallicence',
      'getteleLics',
      'showBuildOrder',
      'getimpexp',
      'showfranchise',
      'getauthentication',
      'gettaxcredit1',
      'hzpscxk',
      'listInformation',
      'selectList',
    ],
    showName: [
      intl('222481', '行政许可[信用中国]'),
      intl('222480', '行政许可[工商局]'),
      intl('99999693', '征信备案'),
      intl('99999690', '金融信息服务备案'),
      intl('222483', '金融许可'),
      intl('205397', '电信许可'),
      intl('216392', '建筑资质'),
      intl('205419', '进出口信用'),
      intl('216405', '商业特许经营'),
      intl('332373', '认证认可'),
      intl('332374', 'A级纳税人'),
      intl('368136', '化妆品生产许可'),
      intl('138468', '上榜信息'),
      intl('286256', '入选名录'),
    ],
    numArr: [
      'admin_licence_num',
      'adminLicenceCount',
      corpDetailInvestigationFiling.modelNum,
      'financialRecordNum',
      'financial_licence_num',
      'telelic_num',
      'build_qualification_num',
      'impexp_num',
      'commercial_franchise_info_num',
      'certification_merge_num',
      'taxaCreditCount',
      'cosmeticslicenseNum',
      'ranked_num',
      'listingTagsDataCount',
    ],
  },
  intellectual: {
    // 知识产权
    title: intl('120665', '知识产权'),
    showList: [
      'getbrand',
      'getpatent',
      'getproductioncopyright',
      'getsoftwarecopyright',
      'getStandardPlan',
      'getdomainname',
      'getweixin',
      'getweibo',
      'gettoutiao',
    ],
    showName: [
      intl('138799', '商标'),
      intl('124585', '专利'),
      intl('138756', '作品著作权'),
      intl('138788', '软件著作权'),
      intl('326113', '标准信息'),
      intl('138804', '网站备案'),
      intl('138581', '微信公众号'),
      intl('138579', '微博账号'),
      intl('138559', '头条号'),
    ],
    numArr: [
      true,
      true,
      'workcopyr_num',
      'softwarecopyright_num',
      'standardInfo',
      'domain_num',
      'webchat_public_num',
      'micro_blog_num',
      'today_headline_num',
    ],
  },
  risk: {
    // 法律诉讼
    title: intl('228331', '司法风险'),
    showList: [],
    fnList: [],
    showName: [],
    numArr: [],
  },
  businessRisk: {
    // 经营风险
    title: intl('138415', '经营风险'),
    showList: [],
    fnList: [],
    showName: [],
    numArr: [],
  },
  history: {
    // 历史数据
    title: intl('33638', '历史数据'),
    showList: [
      'historycompany',
      'historylegalperson',
      'historyinvest',
      'historydomainname',
      'historyshowPledgedstock',
      'getlandmortgage',
    ],
    showName: [
      intl('257705', '工商信息'),
      intl('138370', '法人和高管'),
      intl('138724', '对外投资'),
      intl('138804', '网站备案'),
      intl('138281', '股权出质'),
      intl('205406', '土地抵押'),
    ],
    numArr: [
      'his_business_info_num',
      'his_manager_num',
      'his_invest_num',
      'his_domain_num',
      corpDetailHisEquityPledge.modelNum,
      'landmortgage_num',
    ],
  },
}
