import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoSOE: CorpBasicInfo = {
  anotherNames: null,
  areaCode: '030501',
  biz_reg_no: '',
  bus_address: '',
  business_scope:
    '组织实施全县小米产业发展规划；种质资源及农作物品种的调查保护；小米新品种选育、引进、试验、示范和良种推广；小米产业生产、加工、贮藏、流通以及新技术的引进、试验、示范和推广；引导服务小米产业新型技术培训工作。',
  cancel_date: '',
  configType: 'SOE',
  corp_id: '1355909797',
  corp_name: '米脂县小米产业发展中心',
  corp_old_id: '',
  corp_type: '--',
  corp_type_id: 160307000,
  credit_code: '126108276911246340',
  domainCount: 0,
  eng_name: 'Mizhi County Xiaomi Industry Development Center',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'M',
      industryName: '科学研究和技术服务业',
      type: 'gb',
      windId: '1355909797',
    },
    {
      industryCode: 'M74',
      industryName: '专业技术服务业',
      type: 'gb',
      windId: '1355909797',
    },
    {
      industryCode: 'M748',
      industryName: '工程技术与设计服务',
      type: 'gb',
      windId: '1355909797',
    },
    {
      industryCode: 'M7485',
      industryName: '规划设计管理',
      type: 'gb',
      windId: '1355909797',
    },
  ],
  industryGbFold: '科学研究和技术服务业-专业技术服务业-工程技术与设计服务-规划设计管理',
  industryWindFold: '',
  industryWindFoldCode: 'M7485',
  issue_date: '',
  legal_person_id: 'W00000000000006NB574',
  legal_person_name: '李涛',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2024-05-09',
  oper_period_end: '2029-05-09',
  org_code: '126108276911246340',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  province: '陕西省',
  reg_address: '米脂县盘龙北路14号',
  reg_authority: '米脂县事业单位登记管理局',
  reg_capital: 30,
  reg_date: '',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '',
  seIndustriesCount: 0,
  state: '正常',
  telCount: 0,
  usednames: [
    {
      orgType: '事业单位曾用名',
      useFrom: '',
      useTo: '',
      used_name: '米脂县种子技术推广站',
    },
  ],
  xxIndustryList: {},
}
