import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoGOV: CorpBasicInfo = {
  anotherNames: null,
  areaCode: '030103',
  biz_reg_no: '',
  bus_address: '',
  business_scope:
    '培训公务员、政策研究人员，承办市委市政府举办的专题研讨班，开展多种形式的委托培训和合作培训；开展哲学社会科学研究，行政管理体制改革、科学行政、依法行政、社会管理、应急管理、公共服务等方面的理论和实践问题研究；开展决策咨询工作，为市委、市政府提供决策咨询；开展与境内外有关机构的合作与交流。',
  cancel_date: '',
  configType: 'GOV',
  corp_id: '1179064448',
  corp_name: '镇江市行政学院',
  corp_old_id: '127DC6C',
  corp_type: '--',
  corp_type_id: 160300000,
  credit_code: '',
  domainCount: 0,
  eng_name: 'Zhenjiang City School of Administration',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'P',
      industryName: '教育',
      type: 'gb',
      windId: '1179064448',
    },
    {
      industryCode: 'P83',
      industryName: '教育',
      type: 'gb',
      windId: '1179064448',
    },
    {
      industryCode: 'P839',
      industryName: '技能培训、教育辅助及其他教育',
      type: 'gb',
      windId: '1179064448',
    },
    {
      industryCode: 'P8399',
      industryName: '其他未列明教育',
      type: 'gb',
      windId: '1179064448',
    },
  ],
  industryGbFold: '教育-教育-技能培训、教育辅助及其他教育-其他未列明教育',
  industryWindFold: '可选消费-消费者服务Ⅱ-酒店、餐馆与休闲Ⅲ-餐馆',
  industryWindFoldCode: '25301040',
  issue_date: '',
  legal_person_id: '',
  legal_person_name: '',
  mailCount: 0,
  org_code: '',
  overseasCorpIndustryList: [],
  postal_address: '',
  province: '江苏省',
  reg_address: '江苏省镇江市京口区小米山路519号',
  reg_authority: '政府机构',
  reg_date: '',
  reg_unit: '',
  revokeDate: '',
  revokeOrCancelDate: '',
  seIndustriesCount: 0,
  state: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
