import axios from './index'

const trreData = {
  Data: {
    valid: 1,
    childrenNode: [
      {
        valid: 1,
        childrenNode: [
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62880',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '造价咨询资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62881',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '设计与施工一体化资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62882',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '勘查资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62883',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '监理资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62884',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '建筑业企业资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62885',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: '设计资质',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000011',
                level: 4,
                parentCode: 'Q1000000010',
                name: '建筑业企业资质',
                sort: 1,
                isLeaf: 0,
                status: 1,
              },
            ],
            code: 'Q1000000010',
            level: 3,
            parentCode: 'Q1000000001',
            name: '建筑行业资质',
            sort: 1,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891889',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '经营证券期货业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948899248',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券投资咨询业务资格',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948900504',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券自营业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948901761',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券经纪业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948903018',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券承销与保荐业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948904275',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券资产管理业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948904276',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券外资股业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948906789',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '期货监管业务资格',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '1225192993',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '从事证券市场资信评级业务许可批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '2597253491',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '证券登记结算机构批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000016',
                level: 4,
                parentCode: 'Q1000000012',
                name: '证券',
                sort: 1,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891634',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '金融许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891629',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '支付业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891631',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '装帧流通人民币许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891632',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '国库集中支付代理银行资格认定',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891633',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '银行卡清算业务许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137979989',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '银行卡清算机构获准筹备机构',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137026951',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '银行卡清算机构准入',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142623262',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '银行办理即期结售汇业务',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622857',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '代理国家金库业务',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142623263',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '银行资本金本外币转换',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622858',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '个人本外币兑换特许业务',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622859',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '无记名国债兑付业务',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622860',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '非税收入收缴业务及代理银行资格',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000015',
                level: 4,
                parentCode: 'Q1000000012',
                name: '银行',
                sort: 2,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137027207',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '金融控股公司准入',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '1225193195',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '公募基金注册',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895990',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '合格境内机构投资者资格的批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895991',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '合格境外机构投资者托管人资格的批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895992',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '合格境外投资者批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000017',
                level: 4,
                parentCode: 'Q1000000012',
                name: '资管',
                sort: 3,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948899247',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '基金监管特定客户资产管理业务资格',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948906790',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '基金销售业务资格许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948923046',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: '基金托管业务资格许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000013',
                level: 4,
                parentCode: 'Q1000000012',
                name: '基金',
                sort: 4,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137026952',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '企业征信机构备案',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891630',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '小额贷款公司经营许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891885',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '融资担保业务经营许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891635',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '保险许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891636',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '保险中介许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891637',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '典当经营许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '8277600181',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: '保险类中介机构经营业务范围批复',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137027208',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '信用评级机构备案',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891886',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '在宣传品、出版物或者其他商品上使用人民币',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891887',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '黄金及其制品进出口行政许可',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137026950',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: '设立经营个人征信业务的征信机构审批',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000014',
                level: 4,
                parentCode: 'Q1000000012',
                name: '其他',
                sort: 5,
                isLeaf: 0,
                status: 1,
              },
            ],
            code: 'Q1000000012',
            level: 3,
            parentCode: 'Q1000000001',
            name: '金融行业许可',
            sort: 2,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025383',
                level: 4,
                parentCode: 'Q1000000007',
                name: '民用爆炸物品生产许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025643',
                level: 4,
                parentCode: 'Q1000000007',
                name: '开采黄金矿产许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000019',
            level: 3,
            parentCode: 'Q1000000001',
            name: '制造业行业许可',
            sort: 3,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025227',
                level: 4,
                parentCode: 'Q1000000003',
                name: '国产网络游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025487',
                level: 4,
                parentCode: 'Q1000000003',
                name: '游戏变更审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025486',
                level: 4,
                parentCode: 'Q1000000003',
                name: '进口电子游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025226',
                level: 4,
                parentCode: 'Q1000000003',
                name: '进口网络游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025644',
                level: 4,
                parentCode: 'Q1000000009',
                name: '设立互联网域名注册服务机构审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025645',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信设备进网许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025646',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信网码号资源调整审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025384',
                level: 4,
                parentCode: 'Q1000000009',
                name: '互联网域名根服务器设置及其运行机构和注册',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026640',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电子认证服务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025386',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信网码号资源使用审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '68337',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信业务经营许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000009',
            level: 3,
            parentCode: 'Q1000000001',
            name: '电信\\互联网行业许可',
            sort: 4,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '142623265',
                level: 4,
                parentCode: 'Q1000000004',
                name: '进出口企业名录登记',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000018',
            level: 3,
            parentCode: 'Q1000000001',
            name: '进出口行业企业许可',
            sort: 5,
            isLeaf: 0,
            status: 1,
          },
        ],
        code: 'Q1000000001',
        level: 2,
        parentCode: 'Q1000000000',
        name: '资质大全(按行业)',
        sort: 1,
        isLeaf: 0,
        status: 1,
      },
      {
        valid: 1,
        childrenNode: [
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025227',
                level: 4,
                parentCode: 'Q1000000003',
                name: '国产网络游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025487',
                level: 4,
                parentCode: 'Q1000000003',
                name: '游戏变更审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025486',
                level: 4,
                parentCode: 'Q1000000003',
                name: '进口电子游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025226',
                level: 4,
                parentCode: 'Q1000000003',
                name: '进口网络游戏审批许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000003',
            level: 3,
            parentCode: 'Q1000000002',
            name: '国家新闻出版署',
            sort: 1,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137026952',
                level: 4,
                parentCode: 'Q1000000004',
                name: '企业征信机构备案',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137027208',
                level: 4,
                parentCode: 'Q1000000004',
                name: '信用评级机构备案',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891629',
                level: 4,
                parentCode: 'Q1000000004',
                name: '支付业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891631',
                level: 4,
                parentCode: 'Q1000000004',
                name: '装帧流通人民币许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891632',
                level: 4,
                parentCode: 'Q1000000004',
                name: '国库集中支付代理银行资格认定',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891886',
                level: 4,
                parentCode: 'Q1000000004',
                name: '在宣传品、出版物或者其他商品上使用人民币',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891887',
                level: 4,
                parentCode: 'Q1000000004',
                name: '黄金及其制品进出口行政许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026950',
                level: 4,
                parentCode: 'Q1000000004',
                name: '设立经营个人征信业务的征信机构审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891633',
                level: 4,
                parentCode: 'Q1000000004',
                name: '银行卡清算业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137027207',
                level: 4,
                parentCode: 'Q1000000004',
                name: '金融控股公司准入',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137979989',
                level: 4,
                parentCode: 'Q1000000004',
                name: '银行卡清算机构获准筹备机构',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026951',
                level: 4,
                parentCode: 'Q1000000004',
                name: '银行卡清算机构准入',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142623262',
                level: 4,
                parentCode: 'Q1000000004',
                name: '银行办理即期结售汇业务',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622857',
                level: 4,
                parentCode: 'Q1000000004',
                name: '代理国家金库业务',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142623263',
                level: 4,
                parentCode: 'Q1000000004',
                name: '银行资本金本外币转换',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622858',
                level: 4,
                parentCode: 'Q1000000004',
                name: '个人本外币兑换特许业务',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622859',
                level: 4,
                parentCode: 'Q1000000004',
                name: '无记名国债兑付业务',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622860',
                level: 4,
                parentCode: 'Q1000000004',
                name: '非税收入收缴业务及代理银行资格',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142623265',
                level: 4,
                parentCode: 'Q1000000004',
                name: '进出口企业名录登记',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000004',
            level: 3,
            parentCode: 'Q1000000002',
            name: '中国人民银行',
            sort: 2,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '65891634',
                level: 4,
                parentCode: 'Q1000000005',
                name: '金融许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891630',
                level: 4,
                parentCode: 'Q1000000005',
                name: '小额贷款公司经营许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891885',
                level: 4,
                parentCode: 'Q1000000005',
                name: '融资担保业务经营许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891635',
                level: 4,
                parentCode: 'Q1000000005',
                name: '保险许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891636',
                level: 4,
                parentCode: 'Q1000000005',
                name: '保险中介许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891889',
                level: 4,
                parentCode: 'Q1000000005',
                name: '经营证券期货业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891637',
                level: 4,
                parentCode: 'Q1000000005',
                name: '典当经营许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '8277600181',
                level: 4,
                parentCode: 'Q1000000005',
                name: '保险类中介机构经营业务范围批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000005',
            level: 3,
            parentCode: 'Q1000000002',
            name: '中国银行保险监督管理委员会',
            sort: 3,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '1225193195',
                level: 4,
                parentCode: 'Q1000000006',
                name: '公募基金注册',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895990',
                level: 4,
                parentCode: 'Q1000000006',
                name: '合格境内机构投资者资格的批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895991',
                level: 4,
                parentCode: 'Q1000000006',
                name: '合格境外机构投资者托管人资格的批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895992',
                level: 4,
                parentCode: 'Q1000000006',
                name: '合格境外投资者批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948899247',
                level: 4,
                parentCode: 'Q1000000006',
                name: '基金监管特定客户资产管理业务资格',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948899248',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券投资咨询业务资格',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948900504',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券自营业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948901761',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券经纪业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948903018',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券承销与保荐业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948904275',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券资产管理业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948904276',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券外资股业务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948906789',
                level: 4,
                parentCode: 'Q1000000006',
                name: '期货监管业务资格',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948906790',
                level: 4,
                parentCode: 'Q1000000006',
                name: '基金销售业务资格许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948923046',
                level: 4,
                parentCode: 'Q1000000006',
                name: '基金托管业务资格许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '1225192993',
                level: 4,
                parentCode: 'Q1000000006',
                name: '从事证券市场资信评级业务许可批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '2597253491',
                level: 4,
                parentCode: 'Q1000000006',
                name: '证券登记结算机构批复',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000006',
            level: 3,
            parentCode: 'Q1000000002',
            name: '中国证券监督管理委员会',
            sort: 4,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025644',
                level: 4,
                parentCode: 'Q1000000009',
                name: '设立互联网域名注册服务机构审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025645',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信设备进网许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025646',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信网码号资源调整审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025384',
                level: 4,
                parentCode: 'Q1000000009',
                name: '互联网域名根服务器设置及其运行机构和注册',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026640',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电子认证服务许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025383',
                level: 4,
                parentCode: 'Q1000000007',
                name: '民用爆炸物品生产许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025386',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信网码号资源使用审批',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025643',
                level: 4,
                parentCode: 'Q1000000007',
                name: '开采黄金矿产许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '68337',
                level: 4,
                parentCode: 'Q1000000009',
                name: '电信业务经营许可',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000007',
            level: 3,
            parentCode: 'Q1000000002',
            name: '中华人民共和国工业和信息化部',
            sort: 5,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '62884',
                level: 4,
                parentCode: 'Q1000000008',
                name: '建筑业企业资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62882',
                level: 4,
                parentCode: 'Q1000000008',
                name: '勘查资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62883',
                level: 4,
                parentCode: 'Q1000000008',
                name: '监理资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62881',
                level: 4,
                parentCode: 'Q1000000008',
                name: '设计与施工一体化资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62880',
                level: 4,
                parentCode: 'Q1000000008',
                name: '造价咨询资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62885',
                level: 4,
                parentCode: 'Q1000000008',
                name: '设计资质',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000008',
            level: 3,
            parentCode: 'Q1000000002',
            name: '中华人民共和国住房和城乡建设部',
            sort: 6,
            isLeaf: 0,
            status: 1,
          },
        ],
        code: 'Q1000000002',
        level: 2,
        parentCode: 'Q1000000000',
        name: '资质大全(按发证机关)',
        sort: 2,
        isLeaf: 0,
        status: 1,
      },
    ],
    code: 'Q1000000000',
    level: 1,
    parentCode: '',
    name: '资质大全',
    sort: 1,
    isLeaf: 0,
    status: 1,
  },
  ErrorCode: '0',
  ErrorMessage: '',
  Page: {
    CurrentPage: 0,
    PageSize: 0,
    Records: 0,
    TotalPage: 0,
  },
  State: 0,
}

const mockEnData = {
  Data: {
    valid: 1,
    childrenNode: [
      {
        valid: 1,
        childrenNode: [
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62884',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Qualifications for construction enterprises',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62882',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Survey Qualifications',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62883',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Supervision Qualification',
                    sort: 3,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62881',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Integrated qualification for design and construction',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62880',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Cost consulting qualifications',
                    sort: 5,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '62885',
                    level: 4,
                    parentCode: 'Q1000000008',
                    name: 'Design Qualification',
                    sort: 6,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000011',
                level: 4,
                parentCode: 'Q1000000010',
                name: 'Qualifications for construction enterprises',
                sort: 1,
                isLeaf: 0,
                status: 1,
              },
            ],
            code: 'Q1000000010',
            level: 3,
            parentCode: 'Q1000000001',
            name: 'Construction industry qualifications',
            sort: 1,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891889',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Operating securities and futures business license',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948899248',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Qualifications for securities investment consulting business',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948900504',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Securities proprietary business license',
                    sort: 3,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948901761',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Securities brokerage business license',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948903018',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Securities underwriting and sponsorship business license',
                    sort: 5,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948904275',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Securities asset management business license',
                    sort: 6,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948904276',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Securities foreign equity business license',
                    sort: 7,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948906789',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Qualifications for futures regulatory business',
                    sort: 8,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '2597253491',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Approval from securities registration and settlement institutions',
                    sort: 10,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000016',
                level: 4,
                parentCode: 'Q1000000012',
                name: 'Security',
                sort: 1,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891634',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Financial License',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891629',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Payment business license',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891633',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Bank card clearing business license',
                    sort: 3,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137979989',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Bank card clearing agency approved as a preparatory institution',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142623262',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Banks handle spot foreign exchange transactions',
                    sort: 6,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622857',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Agent national treasury business',
                    sort: 7,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '142622860',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Non-tax income collection business and agency bank qualifications',
                    sort: 11,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891631',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Install, uh, the circulation of RMB permits',
                    sort: 12,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891632',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Treasury centralized payment agency bank qualification certification',
                    sort: 13,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000015',
                level: 4,
                parentCode: 'Q1000000012',
                name: 'Bank',
                sort: 2,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137027207',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Access to financial holding companies',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '1225193195',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Public fund registration',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895990',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Approval of qualified domestic institutional investor qualifications',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895991',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Approval of the qualification of a qualified foreign institutional investor custodian',
                    sort: 3,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948895992',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Approved by qualified overseas investors',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000017',
                level: 4,
                parentCode: 'Q1000000012',
                name: 'Asset Management',
                sort: 3,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948906790',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Qualifications for fund sales business',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948899247',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Fund regulation specific customer asset management business qualifications',
                    sort: 3,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '948923046',
                    level: 4,
                    parentCode: 'Q1000000006',
                    name: 'Fund custody business qualification license',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000013',
                level: 4,
                parentCode: 'Q1000000012',
                name: 'Fund',
                sort: 4,
                isLeaf: 0,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891635',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Insurance License',
                    sort: 1,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891636',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Insurance intermediary license',
                    sort: 2,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137026952',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Enterprise credit agency filing',
                    sort: 4,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137027208',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Credit rating agency filing',
                    sort: 5,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '137026950',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Establish a credit investigation agency for the operation of personal credit investigation business for approval',
                    sort: 6,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891887',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Administrative license for the import and export of gold and its products',
                    sort: 7,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891886',
                    level: 4,
                    parentCode: 'Q1000000004',
                    name: 'Use RMB on promotional materials, publications or other commodities',
                    sort: 8,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891637',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Pawn business license',
                    sort: 9,
                    isLeaf: 1,
                    status: 1,
                  },
                  {
                    valid: 1,
                    childrenNode: [],
                    code: '65891630',
                    level: 4,
                    parentCode: 'Q1000000005',
                    name: 'Small loan company operating license',
                    sort: 10,
                    isLeaf: 1,
                    status: 1,
                  },
                ],
                code: 'Q1000000014',
                level: 4,
                parentCode: 'Q1000000012',
                name: 'Other',
                sort: 5,
                isLeaf: 0,
                status: 1,
              },
            ],
            code: 'Q1000000012',
            level: 3,
            parentCode: 'Q1000000001',
            name: 'Financial industry license',
            sort: 2,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025643',
                level: 4,
                parentCode: 'Q1000000007',
                name: 'Exploitation of gold mineral permits',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000019',
            level: 3,
            parentCode: 'Q1000000001',
            name: 'Manufacturing industry license',
            sort: 3,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025644',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Establish an Internet domain name registration service agency for approval',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025384',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Internet domain name root server settings and operation agencies and registration management agencies set up approval',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026640',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Electronic certification service license',
                sort: 5,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025227',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Approval license for domestic online games',
                sort: 7,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025486',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Imported video game approval license',
                sort: 8,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025226',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Approval permit for imported online games',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000009',
            level: 3,
            parentCode: 'Q1000000001',
            name: 'Telecommunications/internet industry license',
            sort: 4,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '142623265',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Registration of import and export enterprise directory',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000018',
            level: 3,
            parentCode: 'Q1000000001',
            name: 'Import and export industry enterprise license',
            sort: 5,
            isLeaf: 0,
            status: 1,
          },
        ],
        code: 'Q1000000001',
        level: 2,
        parentCode: 'Q1000000000',
        name: 'Qualifications (by industry)',
        sort: 1,
        isLeaf: 0,
        status: 1,
      },
      {
        valid: 1,
        childrenNode: [
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025227',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Approval license for domestic online games',
                sort: 7,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025486',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Imported video game approval license',
                sort: 8,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025226',
                level: 4,
                parentCode: 'Q1000000003',
                name: 'Approval permit for imported online games',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000003',
            level: 3,
            parentCode: 'Q1000000002',
            name: 'National Press and Publication Administration',
            sort: 1,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137027207',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Access to financial holding companies',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142623265',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Registration of import and export enterprise directory',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891629',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Payment business license',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891633',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Bank card clearing business license',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026952',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Enterprise credit agency filing',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137979989',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Bank card clearing agency approved as a preparatory institution',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137027208',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Credit rating agency filing',
                sort: 5,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026950',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Establish a credit investigation agency for the operation of personal credit investigation business for approval',
                sort: 6,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142623262',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Banks handle spot foreign exchange transactions',
                sort: 6,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891887',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Administrative license for the import and export of gold and its products',
                sort: 7,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622857',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Agent national treasury business',
                sort: 7,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891886',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Use RMB on promotional materials, publications or other commodities',
                sort: 8,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '142622860',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Non-tax income collection business and agency bank qualifications',
                sort: 11,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891631',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Install, uh, the circulation of RMB permits',
                sort: 12,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891632',
                level: 4,
                parentCode: 'Q1000000004',
                name: 'Treasury centralized payment agency bank qualification certification',
                sort: 13,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000004',
            level: 3,
            parentCode: 'Q1000000002',
            name: "The People's Bank of China",
            sort: 2,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '65891634',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Financial License',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891635',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Insurance License',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891889',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Operating securities and futures business license',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891636',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Insurance intermediary license',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891637',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Pawn business license',
                sort: 9,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '65891630',
                level: 4,
                parentCode: 'Q1000000005',
                name: 'Small loan company operating license',
                sort: 10,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000005',
            level: 3,
            parentCode: 'Q1000000002',
            name: 'State Administration for Financial Regulation',
            sort: 3,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '948906790',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Qualifications for fund sales business',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '1225193195',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Public fund registration',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895990',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Approval of qualified domestic institutional investor qualifications',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948899248',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Qualifications for securities investment consulting business',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895991',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Approval of the qualification of a qualified foreign institutional investor custodian',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948899247',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Fund regulation specific customer asset management business qualifications',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948900504',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Securities proprietary business license',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948895992',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Approved by qualified overseas investors',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948901761',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Securities brokerage business license',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948923046',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Fund custody business qualification license',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948903018',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Securities underwriting and sponsorship business license',
                sort: 5,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948904275',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Securities asset management business license',
                sort: 6,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948904276',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Securities foreign equity business license',
                sort: 7,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '948906789',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Qualifications for futures regulatory business',
                sort: 8,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '2597253491',
                level: 4,
                parentCode: 'Q1000000006',
                name: 'Approval from securities registration and settlement institutions',
                sort: 10,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000006',
            level: 3,
            parentCode: 'Q1000000002',
            name: 'China Securities Regulatory Commission',
            sort: 4,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '137025643',
                level: 4,
                parentCode: 'Q1000000007',
                name: 'Exploitation of gold mineral permits',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025644',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Establish an Internet domain name registration service agency for approval',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137025384',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Internet domain name root server settings and operation agencies and registration management agencies set up approval',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '137026640',
                level: 4,
                parentCode: 'Q1000000009',
                name: 'Electronic certification service license',
                sort: 5,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000007',
            level: 3,
            parentCode: 'Q1000000002',
            name: "Ministry of Industry and Information Technology of the People's Republic of China",
            sort: 5,
            isLeaf: 0,
            status: 1,
          },
          {
            valid: 1,
            childrenNode: [
              {
                valid: 1,
                childrenNode: [],
                code: '62884',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Qualifications for construction enterprises',
                sort: 1,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62882',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Survey Qualifications',
                sort: 2,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62883',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Supervision Qualification',
                sort: 3,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62881',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Integrated qualification for design and construction',
                sort: 4,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62880',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Cost consulting qualifications',
                sort: 5,
                isLeaf: 1,
                status: 1,
              },
              {
                valid: 1,
                childrenNode: [],
                code: '62885',
                level: 4,
                parentCode: 'Q1000000008',
                name: 'Design Qualification',
                sort: 6,
                isLeaf: 1,
                status: 1,
              },
            ],
            code: 'Q1000000008',
            level: 3,
            parentCode: 'Q1000000002',
            name: "Ministry of Housing and Urban-Rural Development of the People's Republic of China",
            sort: 6,
            isLeaf: 0,
            status: 1,
          },
        ],
        code: 'Q1000000002',
        level: 2,
        parentCode: 'Q1000000000',
        name: 'Qualifications (by the issuing authority)',
        sort: 2,
        isLeaf: 0,
        status: 1,
      },
    ],
    code: 'Q1000000000',
    level: 1,
    parentCode: '',
    name: 'License Library',
    sort: 1,
    isLeaf: 0,
    status: 1,
  },
  ErrorCode: '0',
  ErrorMessage: '',
  Page: {
    CurrentPage: 0,
    PageSize: 0,
    Records: 0,
    TotalPage: 0,
  },
  State: 0,
}

// 资质荣誉搜索
export const qualificationsearch = (data) => {
  // return Promise.resolve(searchData)
  return axios.request({
    cmd: `search/qua/quaDirectoryPreSearch`,
    // url: `http://localhost:9091/treeData`,
    method: 'post',
    data,
  })
}

// 资质荣誉热门
export const qualificationhot = (id = 'Q1000000000') => {
  return axios.request({
    cmd: `detail/quadirectory/quadirectoryHotList/${id}`,
    // url: `http://localhost:9091/treeData`,
    method: 'post',
    data: {
      qualificationCode: id,
    },
  })
}

// 资质荣誉热门切换
export const qualificationhotchange = (data) => {
  return axios
    .request({
      cmd: `detail/quadirectory/quadirectoryHotListV2/${data.qualificationCode}`,
      // url: `http://localhost:9091/treeData`,
      method: 'post',
      data,
    })
    .then((res) => {
      return res
    })
    .catch((err) => {
      console.error('🚀 ~qualificationhotchange ~ err:', err)
    })
}

// 获取资质荣誉菜单
export const getqualificationtree = (id = 'Q1000000000') => {
  // return fetch(`http://10.100.4.62:62601/Wind.WFC.Enterprise.Web/Enterprise/gel/detail/quadirectory/quaDirectoryTree/${id}`, {
  //     method: "post",
  //     body:JSON.stringify({
  //         qualificationCode: id,
  //     }) ,
  // }).then((response) => {
  //     if (!response.ok) {
  //       return Promise.reject(response.status);
  //     }
  //     return response.json();
  //   });
  // return Promise.resolve(trreData)
  return axios
    .request({
      cmd: `detail/quadirectory/quaDirectoryTree/${id}`,
      // url: `http://localhost:9091/treeData`,
      method: 'post',
      data: {
        qualificationCode: id,
      },
    })
    .then((res) => {
      if (window.en_access_config) {
        return mockEnData
      }
      // return mockEnData
      if (!res || !res.Data) {
        return trreData
      }
      return res
    })
    .catch((err) => {
      return trreData
    })
}

// 获取资质荣誉列表
export const getqualificationslist = (data) => {
  // return Promise.resolve(trreData)
  return axios.request({
    cmd: `detail/quadirectory/quaDirectoryCompList/${data.qualificationCode}`,
    // url: `http://localhost:9091/treeData`,
    method: 'post',
    data,
    noWarning: true,
  })
}

// 获取资质荣誉详情
export const getqualificationdetail = (data) => {
  return axios.request({
    cmd: `detail/quadirectory/quaDirectoryChildrenTable/${data.qualificationCode}`,
    method: 'post',
    data,
  })
}

// 获取资质荣誉筛选项
export const getqualificationfilter = (id = '137025227') => {
  return axios.request({
    cmd: `detail/quadirectory/quaDirectoryFilterItem/${id}`,
    // url: `http://localhost:9091/treeData`,
    method: 'post',
    data: {
      qualificationCode: id,
    },
  })
}
