/**
 * Credit report configuration
 */

import { CorpBasicInfo, CorpBasicNumFront, CorpOtherInfo, ReportPageJson, UserPackageFlags } from 'gel-types'
import {
  corpActualController,
  corpAnnualReport,
  corpBelongIndustry,
  corpBranchStructure,
  corpChangeInfo,
  corpCompetitor,
  corpCoreTeam,
  corpEquityChangeInformation,
  corpFinalBeneficiary,
  corpGroupSystem,
  corpHeaderQuarter,
  corpHoldCompany,
  corpMainPersonnel,
  corpShareholderAndCapitalContribution,
  corpShareholderChange,
  corpShareholderPenetration,
  corpShareholderUnregular,
  corpTaxPayer,
} from './baseInfo'
import {
  corpCancellationRecord,
  corpDoubleRandomInspection,
  corpEquityPledge,
  corpInspectionCheck,
  corpIntegrityInformation,
  corpIntellectualPropertyPledge,
  corpLiquidationInfo,
  corpManageAbnormal,
  corpProductRecall,
  corpSeriousViolation,
  corpStockPledge,
  corpTaxDebt,
  corpTaxViolation,
  corpWarrantyInformation,
} from './businessRisk'
import { getCorpInfoConfigByInfo } from './bussInfo'
import {
  corpABSInfo,
  corpBankCredit,
  corpBondIssue,
  corpChattelFinancing,
  corpChattelMortgageMortgagee,
  corpChattelMortgageMortgager,
  corpDebtRating,
  corpInfoAwaitListing,
  corpInvestAgency,
  corpInvestEvent,
  corpMergeInfo,
  corpPEVCFinance,
  corpPEVCQuit,
  corpSharedStock,
} from './finance'
import { filterReportConfigByCorpType } from './helper/filterReportConfigByCorpType'
import { filterReportConfigByUserInfo } from './helper/filterReportConfigByUserInfo'
import { getShareholderInfoByCorpArea } from './helper/getShareholderInfoByCorpArea'
import { getShareholderReportByBasicNum } from './helper/getShareholderReportByBasicNum'
import { handleHKBaseInfo } from './helper/handleHKBaseInfo'
import {
  corpMicroblogAccount,
  corpPatentBranch,
  corpPatentHoldCompany,
  corpPatentOutboundInvestment,
  corpPatentSelf,
  corpSoftwareCopyright,
  corpStandardInfo,
  corpTodayHeadline,
  corpTrademarkBranch,
  corpTrademarkHoldCompany,
  corpTrademarkOutboundInvest,
  corpTrademarkSelf,
  corpWebsiteRegistration,
  corpWechatPublic,
  corpWorkCopyright,
} from './intellectual'

import {
  corpAppProducts,
  corpBiddingAnnouncements,
  corpBusinessAssociates,
  corpCompanyReports,
  corpCustomersAndSuppliers,
  corpEnterpriseBusiness,
  corpGovernmentMajorProjects,
  corpGovernmentSubsidies,
  corpGovernmentSupport,
  corpHotels,
  corpLandInformation,
  corpPrivateEquityFunds,
  corpRecruitment,
  corpTenderingAnnouncements,
} from './business'
import { filterReportConfigByBasicNum } from './helper/filterReportConfigByBasicNum'
import {
  corpBusinessLicenseInvalidDeclaration,
  corpHistoryBusinessInfo,
  corpHistoryEquityPledge,
  corpHistoryLandMortgage,
  corpHistoryLegalRepresentative,
  corpHistoryOverseasInvestment,
  corpHistoryShareholder,
  corpHistoryWebsiteRegistration,
  corpMultiCertificate,
} from './history'
import {
  corpBussDataBusinessCumulative,
  corpBussDataBusinessCurrent,
  corpBussDataInventoryCumulative,
  corpBussDataInventoryCurrent,
  corpBussDataOutputCumulative,
  corpBussDataOutputCurrent,
  corpBussDataSalesCumulative,
  corpBussDataSalesCurrent,
  corpFinancialIndicator,
  corpMainBusinessScope,
  corpReportBalanceSheet,
  corpReportProfitStatement,
} from './IpoBusinessData'
import {
  corpAdministrativeLicenseBureau,
  corpAdministrativeLicenseCreditChina,
  corpAExcellentTaxpayer,
  corpBuildingQualification,
  corpCertification,
  corpCommercialFranchise,
  corpDirectoryList,
  corpFinancialLicense,
  corpRankedCompanyList,
  corpRealEstateDevelopmentQualification,
  corpTelecomLicense,
} from './qualification'
import {
  corpAppraisal,
  corpBankruptcyReorganization,
  corpCourtNotice,
  corpCreditDishonest,
  corpDeliveryAnnouncement,
  corpEndCase,
  corpEnforcement,
  corpFilingInfo,
  corpJudicialAuction,
  corpJudicialDocument,
  corpLimitHighConsumption,
  corpTrialNotice,
} from './risk'

// Default configuration
export const getDDRPConfig = (
  baseInfo: CorpBasicInfo | undefined,
  basicNum: Partial<CorpBasicNumFront> | undefined,
  otherInfo: CorpOtherInfo | undefined,
  userFlags: UserPackageFlags | undefined
): ReportPageJson => {
  const bussInfo = getCorpInfoConfigByInfo(baseInfo)

  const hkBaseInfo = handleHKBaseInfo(basicNum, otherInfo)
  const res: ReportPageJson = [
    {
      key: 'CompanyInfo',
      title: '企业基本情况',
      titleIntl: '451094',
      type: 'section',
      children: [
        bussInfo,
        ...(hkBaseInfo ? [hkBaseInfo] : []),
        corpBelongIndustry,
        {
          type: 'section',
          key: 'Shareholder',
          title: '股东信息',
          titleIntl: '138506',
          children: [
            corpShareholderUnregular,
            getShareholderReportByBasicNum(basicNum),
            getShareholderInfoByCorpArea(baseInfo?.areaCode),
          ],
        },
        corpShareholderPenetration,
        corpShareholderChange,
        corpActualController,
        corpFinalBeneficiary,
        corpBranchStructure,
        corpHoldCompany,
        corpMainPersonnel,
        corpCoreTeam,
        corpGroupSystem,
        corpHeaderQuarter,
        corpCompetitor,
        corpChangeInfo,
        corpTaxPayer,
        corpAnnualReport,
        {
          type: 'section',
          key: 'EnterprisePublicity',
          title: '企业公示',
          titleIntl: '222474',
          children: [corpShareholderAndCapitalContribution, corpEquityChangeInformation],
        },
      ],
    },
    {
      key: 'BussData',
      title: '业务数据',
      titleIntl: '64824',
      type: 'section',
      children: [
        {
          type: 'section',
          key: 'BussDataOutput',
          title: '产量',
          children: [corpBussDataOutputCumulative, corpBussDataOutputCurrent],
        },
        {
          type: 'section',
          key: 'BussDataSales',
          title: '销量',
          children: [corpBussDataSalesCumulative, corpBussDataSalesCurrent],
        },
        {
          type: 'section',
          key: 'BussDataBusiness',
          title: '业务量',
          children: [corpBussDataBusinessCumulative, corpBussDataBusinessCurrent],
        },
        {
          type: 'section',
          key: 'BussDataInventory',
          title: '库存',
          children: [corpBussDataInventoryCumulative, corpBussDataInventoryCurrent],
        },
      ],
    },
    {
      type: 'section',
      key: 'FinanceInfo',
      title: '金融行为',
      titleIntl: '138296',
      children: [
        corpSharedStock,
        corpInfoAwaitListing,
        corpBondIssue,
        corpDebtRating,
        corpInvestAgency,
        corpInvestEvent,
        corpPEVCFinance,
        corpPEVCQuit,
        corpMergeInfo,
        corpBankCredit,
        corpABSInfo,
        corpChattelFinancing,
        corpChattelMortgageMortgager,
        corpChattelMortgageMortgagee,
      ],
    },
    {
      type: 'section',
      key: 'BusinessInfo',
      title: '经营信息',
      children: [
        corpReportProfitStatement,
        corpReportBalanceSheet,
        corpFinancialIndicator,
        corpMainBusinessScope,
        corpEnterpriseBusiness,
        corpAppProducts,
        corpHotels,
        corpCompanyReports,
        corpGovernmentMajorProjects,
        corpTenderingAnnouncements,
        corpBiddingAnnouncements,
        corpRecruitment,
        corpLandInformation,
        corpPrivateEquityFunds,
        corpCustomersAndSuppliers,
        corpBusinessAssociates,
        corpGovernmentSubsidies,
        corpGovernmentSupport,
      ],
    },
    {
      type: 'section',
      key: 'Qualification',
      title: '资质荣誉',
      titleIntl: '451116',
      children: [
        corpAdministrativeLicenseCreditChina,
        corpAdministrativeLicenseBureau,
        corpCommercialFranchise,
        corpFinancialLicense,
        corpTelecomLicense,
        corpBuildingQualification,
        corpRealEstateDevelopmentQualification,
        corpCertification,
        corpAExcellentTaxpayer,
        corpDirectoryList,
        corpRankedCompanyList,
      ],
    },

    {
      type: 'section',
      key: 'IntellectualProperty',
      title: '企业知识产权',
      titleIntl: '451095',
      children: [
        {
          title: '商标',
          titleIntl: '138799',
          type: 'nodeWithChildren',
          key: 'Trademark',
          children: [corpTrademarkSelf, corpTrademarkHoldCompany, corpTrademarkOutboundInvest, corpTrademarkBranch],
        },
        {
          title: '专利',
          titleIntl: '124585',
          type: 'nodeWithChildren',
          key: 'Patent',
          children: [corpPatentSelf, corpPatentHoldCompany, corpPatentOutboundInvestment, corpPatentBranch],
        },
        corpWorkCopyright,
        corpSoftwareCopyright,
        corpStandardInfo,
        corpWebsiteRegistration,
        corpWechatPublic,
        corpMicroblogAccount,
        corpTodayHeadline,
      ],
    },
    {
      type: 'section',
      key: 'JudicialRisk',
      title: '司法风险',
      children: [
        corpJudicialDocument,
        corpFilingInfo,
        corpTrialNotice,
        corpDeliveryAnnouncement,
        corpCourtNotice,
        corpEnforcement,
        corpCreditDishonest,
        corpEndCase,
        corpLimitHighConsumption,
        corpJudicialAuction,
        corpBankruptcyReorganization,
        corpAppraisal,
      ],
    },
    {
      type: 'section',
      key: 'BusinessRisk',
      title: '经营风险',
      children: [
        corpIntegrityInformation,
        corpManageAbnormal,
        corpCancellationRecord,
        corpLiquidationInfo,
        corpTaxDebt,
        corpTaxViolation,
        corpSeriousViolation,
        corpInspectionCheck,
        corpDoubleRandomInspection,
        corpProductRecall,
        corpWarrantyInformation,
        corpStockPledge,
        corpEquityPledge,
        corpIntellectualPropertyPledge,
      ],
    },
    {
      type: 'section',
      key: 'HistoryInfo',
      title: '历史信息',
      children: [
        corpHistoryBusinessInfo,
        corpHistoryShareholder,
        corpHistoryLegalRepresentative,
        corpHistoryOverseasInvestment,
        corpHistoryWebsiteRegistration,
        corpHistoryEquityPledge,
        corpHistoryLandMortgage,
        corpMultiCertificate,
        corpBusinessLicenseInvalidDeclaration,
      ],
    },
  ]

  const filteredConfitByUserInfo = filterReportConfigByUserInfo(res, userFlags)
  const filteredConfitByCorpType = filterReportConfigByCorpType(filteredConfitByUserInfo, baseInfo?.configType)
  const filteredConfitByBasicNum = filterReportConfigByBasicNum(filteredConfitByCorpType, basicNum)
  return filteredConfitByBasicNum
}
