import { IBuryPointConfig } from './type'
import { PageModuleEnum } from '@/api/pointBuried/module.ts'

export const characterTracker: IBuryPointConfig[] = [
  {
    moduleId: 922602101083,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-侧边栏点击',
    opActive: 'click',
  },
  {
    moduleId: 922602101084,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-全部关联企业点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101085,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-全部关联企业筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101086,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-全部关联企业筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101087,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-全部关联企业筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101088,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-全部关联企业筛选角色',
    opActive: 'filter',
  },
  {
    moduleId: 922602101089,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-担任法人点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101090,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-担任法人筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101091,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-担任法人筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101092,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-担任法人筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101093,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-对外投资点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101094,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-对外投资筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101095,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-对外投资筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101096,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-对外投资筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101097,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-在外任职点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101098,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-在外任职筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101099,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-在外任职筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101100,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-在外任职筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101101,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101102,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101103,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101104,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101105,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-疑似实控点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101106,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-疑似实控筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101107,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-疑似实控筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101108,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-疑似实控筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101109,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-合作伙伴点击跳转人物',
    opActive: 'click',
  },
  {
    moduleId: 922602101110,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-合作伙伴点击查看详情',
    opActive: 'click',
  },
  {
    moduleId: 922602101111,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史担任法人点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101112,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史担任法人筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101113,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史担任法人筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101114,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史担任法人筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101115,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史对外投资点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101116,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史对外投资筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101117,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史对外投资筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101118,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史对外投资筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101119,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史在外任职点击跳转',
    opActive: 'click',
  },
  {
    moduleId: 922602101120,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史在外任职筛选状态',
    opActive: 'filter',
  },
  {
    moduleId: 922602101121,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史在外任职筛选国家地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101122,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史在外任职筛选行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101123,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史疑似实控点击跳转',
    opActive: 'filter',
  },
  {
    moduleId: 922602101129,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益股权链',
    opActive: 'click',
  },
  {
    moduleId: 922602101130,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-历史最终受益股权链',
    opActive: 'click',
  },
  {
    moduleId: 922602101131,
    pageId: PageModuleEnum.CHARACTER_INFO,
    pageName: '人物详情页',
    describe: '人物详情页-最终受益筛选受益类型',
    opActive: 'filter',
  },
]
