import { IBuryPointConfig } from '@/api/pointBuried/config/type.ts'
import { PageModuleEnum } from '@/api/pointBuried/module.ts'

export const corpDetailBuryList: IBuryPointConfig[] = [

  {
    moduleId: 922602100187,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击监控/取消监控按钮',
    opActive: 'click',
  },
  {
    moduleId: 922602100272,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-加载页面',
    opActive: 'enter',
  },
  {
    moduleId: 922602100273,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击关注/取消关注按钮',
    opActive: 'click',
  },
  {
    moduleId: 922602100276,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击查看全部新闻链接',
    opActive: 'click',
  },
  {
    moduleId: 922602100277,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击关系图谱按钮',
    opActive: 'click',
  },
  {
    moduleId: 922602100278,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-工商信息-点击WI行业中心链接',
    opActive: 'click',
  },
  {
    moduleId: 922602100282,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-股东信息-点击疑似实际控制人图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100286,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-并购信息-点击中国并购库图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100287, // todo
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-待上市信息-点击新股中心图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100288,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-股权出质-点击出质人tab',
    opActive: 'click',
  },
  {
    moduleId: 922602100289,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-股权出质-点击质权人tab',
    opActive: 'click',
  },
  {
    moduleId: 922602100290,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-股权出质-点击出质标的tab',
    opActive: 'click',
  },
  {
    moduleId: 922602100291,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-上榜信息-点击企业排行榜图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100292,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-菜单-点击任意二级菜单进行定位',
    opActive: 'click',
  },
  {
    moduleId: 922602100312,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击下载报告按钮	24年9月开始没有数据',
    opActive: 'click',
  },
  {
    moduleId: 922602100313,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情页-企业标签-点击查看更多',
    opActive: 'click',
  },
  {
    moduleId: 922602100314,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-工商信息-点击实际控制人图谱图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100327,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-上榜信息-点击榜单详情',
    opActive: 'click',
  },
  {
    moduleId: 922602100328,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-债券信息-点击募集说明书下载链接',
    opActive: 'click',
  },
  {
    moduleId: 922602100346,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-股东穿透-切换合并统计',
    opActive: 'click',
  },
  {
    moduleId: 922602100369,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击更新图标',
    opActive: 'click',
  },
  {
    moduleId: 922602100376,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-加载股权穿透弹框',
    opActive: 'click',
  },
  {
    moduleId: 922602100377,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-加载疑似关系弹框',
    opActive: 'click',
  },
  {
    moduleId: 922602100378,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击查看风险详情',
    opActive: 'click',
  },
  {
    moduleId: 922602100876,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '股权穿透图',
    opActive: 'click',
  },
  {
    moduleId: 922602100877,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '投资穿透图',
    opActive: 'click',
  },
  {
    moduleId: 922602100967,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '实控人-点击查看判定理由',
    opActive: 'click',
  },
  {
    moduleId: 922602100968,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '受益人-点击股权链',
    opActive: 'click',
  },
  {
    moduleId: 922602100969,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '受益人-点击查看受益人图谱',
    opActive: 'click',
  },
]
