import { FilterConfigItem } from '../types'

export const mockFilterConfig: FilterConfigItem[] = [
  {
    itemType: '1',
    itemEn: 'corp_name',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 1,
    itemName: '企业名称',
    itemField: 'corp_name',
    logicOption: 'any,notAny,all',
    placeholder: '请输入企业名称',
  },
  {
    itemType: '1',
    itemEn: 'biz_scope',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 3,
    itemName: '经营范围',
    itemField: 'biz_scope',
    itemRemark: '是否做多行文本处理',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '2',
    itemEn: 'wkg_tags',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 107,
    itemName: '产品',
    itemField: 'wkg_tags',
    logicOption: 'any',
  },
  {
    searchPlaceholder: '请输入所属园区名称',
    itemType: '9',
    itemEn: '',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 140,
    itemName: '所属园区',
    itemField: 'park_id',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'artificial_person',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 4,
    itemName: '法人姓名',
    itemField: 'artificial_person',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'stockholder_people',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 5,
    itemName: '股东-自然人',
    itemField: 'stockholder_people',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'shareholder_corp',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 6,
    itemName: '股东-企业名称',
    itemField: 'stockholder_corp',
    logicOption: 'any',
  },
  {
    itemType: '1',
    itemEn: 'corp_brief',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 7,
    itemName: '企业简介',
    itemField: 'brief.search',
    itemRemark: '是否做多行文本处理',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '1',
    itemEn: 'register_address',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 8,
    itemName: '注册地址',
    itemField: 'register_address',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '1',
    itemEn: 'business_address',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 9,
    itemName: '办公地址',
    itemField: 'business_address',
    logicOption: 'any,notAny,all',
  },
]

export const mockAreaFilterConfig: FilterConfigItem[] = [
  {
    itemType: '0',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 89,
    itemName: '地区',
    itemField: 'area_code',
    logicOption: 'prefix',
  },
]

export const mockIndustryFilterConfig: FilterConfigItem[] = [
  {
    itemId: 90,
    itemType: '0',
    itemName: '国民经济行业分类',
    selfDefine: 0,
    itemOption: [],
    itemField: 'industry_code',
    logicOption: 'prefix',
    hasExtra: false,
    parentId: 0,
    isVip: 0,
  },
  {
    itemId: 229,
    itemType: '0',
    itemName: 'WIND行业',
    selfDefine: 0,
    itemOption: [],
    itemField: 'industry_wind_code',
    logicOption: 'prefix',
    hasExtra: false,
    parentId: 0,
    isVip: 0,
  },
  {
    itemId: 213,
    itemType: '10',
    itemName: '战略性新兴产业',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
      {
        label: '置信度：宽',
        value: 'lenient',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'lenient',
    itemField: 'strategicNewIndustry',
    logicOption: 'any',
    hasExtra: false,
    parentId: 0,
    isVip: 0,
  },
  {
    itemId: 222,
    itemType: '0',
    itemName: '高技术产业（制造业）',
    selfDefine: 0,
    itemOption: [],
    itemField: 'highTechManufacturingIndustry',
    logicOption: 'any',
    hasExtra: false,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 223,
    itemType: '10',
    itemName: '高技术产业（服务业）',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'moderate',
    itemField: 'highTechServiceIndustry',
    logicOption: 'any',
    hasExtra: false,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 224,
    itemType: '0',
    itemName: '知识产权（专利）密集型产业',
    selfDefine: 0,
    itemOption: [],
    itemField: 'intellectualPropertyIndustry',
    logicOption: 'any',
    hasExtra: false,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 225,
    itemType: '10',
    itemName: '绿色低碳转型产业',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
      {
        label: '置信度：宽',
        value: 'lenient',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'lenient',
    itemField: 'greenIndustry',
    logicOption: 'any',
    hasExtra: true,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 226,
    itemType: '10',
    itemName: '农业及相关产业',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'moderate',
    itemField: 'agricultureIndustry',
    logicOption: 'any',
    hasExtra: true,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 227,
    itemType: '10',
    itemName: '养老产业',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'moderate',
    itemField: 'agingCareIndustry',
    logicOption: 'any',
    hasExtra: true,
    parentId: 0,
    isVip: 1,
  },
  {
    itemId: 228,
    itemType: '10',
    itemName: '数字经济及其核心产业',
    extraOptions: [
      {
        label: '置信度：严',
        value: 'strict',
      },
      {
        label: '置信度：较严',
        value: 'moderate',
      },
    ],
    selfDefine: 0,
    itemOption: [],
    confidence: 'moderate',
    itemField: 'digitalEconomyIndustry',
    logicOption: 'any',
    hasExtra: true,
    parentId: 0,
    isVip: 1,
  },
  {
    searchPlaceholder: '请输入细分赛道名称',
    itemType: '9',
    itemEn: '',
    itemOption: [],
    selfDefine: 0,
    hasExtra: false,
    isVip: 1,
    parentId: 0,
    itemId: 141,
    hoverHint:
      '由RimeData来觅数据根据一级市场的投资特征，基于被投企业的官网信息、主营构成、产品业务、上榜信息、新闻报道进行精准分类，目前仅覆盖有PEVC投融事件的中国大陆企业',
    itemName: '来觅赛道',
    itemField: 'track_id',
    logicOption: 'any',
  },
]

export const mockBasicFilterConfig: FilterConfigItem[] = [
  {
    itemType: '1',
    itemEn: 'corp_name',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 1,
    itemName: '企业名称',
    itemField: 'corp_name',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '3',
    itemEn: 'govlevel',
    selfDefine: 0,
    itemOption: [
      {
        name: '存续',
        value: '存续',
      },
      {
        name: '迁出',
        value: '迁出',
      },
      {
        name: '注销',
        value: '注销',
      },
      {
        name: '吊销，未注销',
        value: '吊销,未注销',
      },
      {
        name: '停业',
        value: '停业',
      },
      {
        name: '撤销',
        value: '撤销',
      },
      {
        name: '非正常户',
        value: '非正常户',
      },
      {
        name: '吊销，已注销',
        value: '吊销,已注销',
      },
      {
        name: '责令关闭',
        value: '责令关闭',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 77,
    itemName: '营业状态',
    itemField: 'govlevel',
    logicOption: 'any',
  },
  {
    itemType: '4',
    itemEn: 'established_time',
    selfDefine: 4,
    itemOption: [
      {
        name: '一个月内',
        value: '30',
      },
      {
        name: '六个月内',
        value: '180',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 12,
    itemName: '成立日期',
    itemField: 'established_time',
    itemRemark: '年月日',
    logicOption: 'range',
  },
  {
    itemType: '4',
    itemEn: 'cancel_time',
    selfDefine: 4,
    itemOption: [
      {
        name: '一个月内',
        value: '30',
      },
      {
        name: '六个月内',
        value: '180',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 37,
    itemName: '注销日期',
    itemField: 'cancel_time',
    itemRemark: '年月日',
    logicOption: 'range',
  },
  {
    itemType: '3',
    itemEn: 'corp_type_filter',
    selfDefine: 0,
    itemOption: [
      {
        name: '有限责任公司',
        value: '有限责任公司',
      },
      {
        name: '股份有限公司',
        value: '股份有限公司',
      },
      {
        name: '集体所有制',
        value: '集体所有制',
      },
      {
        name: '外商投资企业',
        value: '外商投资企业',
      },
      {
        name: '港澳台投资企业',
        value: '港澳台投资企业',
      },
      {
        name: '个人独资企业',
        value: '个人独资企业',
      },
      {
        name: '联营企业',
        value: '联营企业',
      },
      {
        name: '有限合伙',
        value: '有限合伙',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 79,
    itemName: '企业类型',
    itemField: 'corp_type_filter',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: 'capital_amount',
    selfDefine: 2,
    itemOption: [
      {
        name: '100万以内',
        value: '0-100',
      },
      {
        name: '100万-500万',
        value: '100-500',
      },
      {
        name: '500万-1000万',
        value: '500-1000',
      },
      {
        name: '1000万-3000万',
        value: '1000-3000',
      },
      {
        name: '3000万-5000万',
        value: '3000-5000',
      },
      {
        name: '5000万以上',
        value: '5000-',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 10,
    itemName: '注册资本',
    itemField: 'register_capital',
    itemRemark: '万',
    logicOption: 'range',
  },
  {
    itemType: '4',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '人民币',
        value: '人民币,CNY',
      },
      {
        name: '美元',
        value: '美元',
      },
      {
        name: '其它',
        value: '港元,欧元,日元,英镑,新加坡元,澳元,加元,韩元',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 11,
    itemName: '注册资本币种',
    itemField: 'capital_unit',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 2,
    itemOption: [
      {
        name: '100万以内',
        value: '0-100',
      },
      {
        name: '100万-500万',
        value: '100-500',
      },
      {
        name: '500万-1000万',
        value: '500-1000',
      },
      {
        name: '1000万-3000万',
        value: '1000-3000',
      },
      {
        name: '3000万-5000万',
        value: '3000-5000',
      },
      {
        name: '5000万以上',
        value: '5000-',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 57,
    itemName: '实缴资本',
    itemField: 'contributed_capital',
    itemRemark: '万',
    logicOption: 'range',
  },
  {
    itemType: '4',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '人民币',
        value: 'CNY',
      },
      {
        name: '美元',
        value: 'USD',
      },
      {
        name: '其它',
        value: 'HKD,EUR,JPY,GBP,SGD,AUD,CAD,CHF',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 58,
    itemName: '实缴资本币种',
    itemField: 'contributed_capital_currency',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'artificial_person',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 4,
    itemName: '法人姓名',
    itemField: 'artificial_person',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: 'corp_size',
    selfDefine: 0,
    itemOption: [
      {
        name: '大型企业',
        value: '企业规模:大型企业',
      },
      {
        name: '中型企业',
        value: '企业规模:中型企业',
      },
      {
        name: '小型企业',
        value: '企业规模:小型企业',
      },
      {
        name: '微型企业',
        value: '企业规模:微型企业',
      },
      {
        name: '小微企业',
        value: '企业规模:小微企业',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 84,
    itemName: '企业规模',
    itemField: 'corporation_tags3',
    itemRemark: '',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        itemOption: [
          {
            name: '中央企业',
            label: '中央企业',
            value: '中央企业',
          },
          {
            itemOption: [
              {
                name: '央企一级子公司',
                label: '央企一级子公司',
                value: '央企一级子公司',
              },
              {
                name: '央企二级子公司',
                label: '央企二级子公司',
                value: '央企二级子公司',
              },
              {
                name: '央企三级子公司',
                label: '央企三级子公司',
                value: '央企三级子公司',
              },
              {
                name: '央企四级子公司',
                label: '央企四级子公司',
                value: '央企四级子公司',
              },
              {
                name: '央企五级子公司',
                label: '央企五级子公司',
                value: '央企五级子公司',
              },
              {
                name: '央企六级子公司',
                label: '央企六级子公司',
                value: '央企六级子公司',
              },
            ],
            name: '央企子公司',
            label: '央企子公司',
            value: [
              '央企一级子公司',
              '央企二级子公司',
              '央企三级子公司',
              '央企四级子公司',
              '央企五级子公司',
              '央企六级子公司',
            ],
          },
          {
            name: '中央国有企业',
            label: '中央国有企业',
            value: '中央国有企业',
          },
          {
            name: '地方国有企业',
            label: '地方国有企业',
            value: '地方国有企业',
          },
          {
            name: '省级国有企业',
            label: '省级国有企业',
            value: '省级国有企业',
          },
          {
            name: '市级国有企业',
            label: '市级国有企业',
            value: '市级国有企业',
          },
          {
            name: '区县级国有企业',
            label: '区县级国有企业',
            value: '区县级国有企业',
          },
        ],
        name: '国有企业',
        value: [
          '中央企业',
          '央企一级子公司',
          '央企二级子公司',
          '央企三级子公司',
          '央企四级子公司',
          '央企五级子公司',
          '央企六级子公司',
          '中央国有企业',
          '地方国有企业',
          '省级国有企业',
          '市级国有企业',
          '区县级国有企业',
        ],
      },
      {
        name: '民营企业',
        value: '民营企业',
      },
      {
        name: '外资企业',
        value: '外资企业',
      },
      {
        name: '公众企业',
        value: '公众企业',
      },
      {
        name: '集体企业',
        value: '集体企业',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 75,
    itemName: '企业所有制性质',
    multiCbx: 1,
    itemField: 'corp_nature',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 2,
    itemOption: [
      {
        name: '100人以下',
        value: '0-100',
      },
      {
        name: '100-199人',
        value: '100-199',
      },
      {
        name: '200-499人',
        value: '200-499',
      },
      {
        name: '500-999人',
        value: '500-999',
      },
      {
        name: '1000-2999人',
        value: '1000-2999',
      },
      {
        name: '3000-9999人',
        value: '3000-9999',
      },
      {
        name: '10000人以上',
        value: '10000-',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 85,
    itemName: '参保人数',
    itemField: 'endowment_num',
    itemRemark: '人',
    logicOption: 'range',
  },
  {
    itemType: '1',
    itemEn: 'register_address',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 8,
    itemName: '注册地址',
    itemField: 'register_address',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '1',
    itemEn: 'business_address',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 9,
    itemName: '办公地址',
    itemField: 'business_address',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '1',
    itemEn: 'biz_scope',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 3,
    itemName: '经营范围',
    itemField: 'biz_scope',
    itemRemark: '是否做多行文本处理',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '1',
    itemEn: 'corp_brief',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 7,
    itemName: '企业简介',
    itemField: 'brief.search',
    itemRemark: '是否做多行文本处理',
    logicOption: 'any,notAny,all',
  },
  {
    itemType: '2',
    itemEn: 'wkg_tags',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 107,
    itemName: '产品',
    itemField: 'wkg_tags',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'stockholder_people',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 5,
    itemName: '股东-自然人',
    itemField: 'stockholder_people',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'shareholder_corp',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 6,
    itemName: '股东-企业名称',
    itemField: 'stockholder_corp',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'group_system',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 29,
    itemName: '集团系',
    itemField: 'group_system',
    logicOption: 'prefix',
  },
  {
    itemType: '4',
    itemEn: 'group_type',
    selfDefine: 0,
    itemOption: [
      {
        name: '主体公司',
        value: '主体公司',
      },
      {
        name: '成员公司',
        value: '成员公司',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 180,
    itemName: '集团公司类型',
    itemField: 'group_type',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: 'data_from',
    selfDefine: 0,
    itemOption: [
      {
        name: '境内企业',
        value: '298010000,298020000,298040000',
      },
      {
        name: '个体工商户',
        value: '298030000',
      },
      {
        name: '政府机构',
        value: '160300000',
      },
      {
        name: '社会组织',
        value: '160900000',
      },
      {
        name: '事业单位',
        value: '160307000',
      },
      {
        name: '律所',
        value: '912034101',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 78,
    itemName: '机构类型',
    itemField: 'data_from',
    logicOption: 'any',
  },
  {
    itemType: '5',
    itemEn: 'tel',
    selfDefine: 0,
    itemOption: [
      {
        name: '有联系电话',
        value: 'true',
      },
      {
        name: '无联系电话',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 80,
    itemName: '有无电话',
    itemField: 'tel',
    logicOption: 'bool',
  },
]

export const mockRelationFilterConfig: FilterConfigItem[] = [
  {
    itemType: '2',
    itemEn: 'artificial_person',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 4,
    itemName: '法人姓名',
    itemField: 'artificial_person',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'stockholder_people',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 5,
    itemName: '股东-自然人',
    itemField: 'stockholder_people',
    logicOption: 'any',
  },
  {
    itemType: '2',
    itemEn: 'shareholder_corp',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 6,
    itemName: '股东-企业名称',
    itemField: 'stockholder_corp',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '国有控股',
        value: '国有控股',
      },
      {
        name: '集体控股',
        value: '集体控股',
      },
      {
        name: '私人控股',
        value: '私人控股',
      },
      {
        name: '港澳台商控股',
        value: '港澳台商控股',
      },
      {
        name: '外商控股',
        value: '外商控股',
      },
      {
        name: '国有绝对控股',
        value: '国有绝对控股',
      },
      {
        name: '国有相对控股',
        value: '国有相对控股',
      },
      {
        name: '集体绝对控股',
        value: '集体绝对控股',
      },
      {
        name: '集体相对控股',
        value: '集体相对控股',
      },
      {
        name: '私人绝对控股',
        value: '私人绝对控股',
      },
      {
        name: '私人相对控股',
        value: '私人相对控股',
      },
      {
        name: '港澳台商绝对控股',
        value: '港澳台商绝对控股',
      },
      {
        name: '港澳台商相对控股',
        value: '港澳台商相对控股',
      },
      {
        name: '外商绝对控股',
        value: '外商绝对控股',
      },
      {
        name: '外商相对控股',
        value: '外商相对控股',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 146,
    itemName: '控股方式',
    itemField: 'corporation_tags',
    logicOption: 'any',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: '',
        selfDefine: 2,
        itemOption: [
          {
            name: '30%',
            value: '30-',
          },
          {
            name: '50%',
            value: '50-',
          },
        ],
        hasExtra: false,
        parentId: 130,
        isVip: 1,
        itemId: 132,
        itemName: '外商持股比例',
        itemField: 'parent_stockshare_foreign',
        itemRemark: '%',
        logicOption: 'range',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有外商投资',
        value: 'true',
      },
      {
        name: '无外商投资',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 130,
    itemName: '有无外商投资',
    itemField: 'parent_stockshare_foreign',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'foreign invest number',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 13,
        isVip: 1,
        itemId: 14,
        itemName: '对外投资数量',
        itemField: 'count.foreign_invest_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'foreign invest',
    selfDefine: 0,
    itemOption: [
      {
        name: '有对外投资',
        value: 'true',
      },
      {
        name: '无对外投资',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 13,
    itemName: '有无对外投资',
    itemField: 'count.foreign_invest_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'branch number',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 15,
        isVip: 1,
        itemId: 16,
        itemName: '分支机构数量',
        itemField: 'count.branch_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'branch',
    selfDefine: 0,
    itemOption: [
      {
        name: '有分支机构',
        value: 'true',
      },
      {
        name: '无分支机构',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 15,
    itemName: '有无分支机构',
    itemField: 'count.branch_num',
    logicOption: 'bool',
  },
]

export const mockBuildFilterConfig: FilterConfigItem[] = [
  {
    itemType: '3',
    itemEn: 'corp_size',
    selfDefine: 0,
    itemOption: [
      {
        name: '大型企业',
        value: '企业规模:大型企业',
        values: [],
      },
      {
        name: '中型企业',
        value: '企业规模:中型企业',
        values: [],
      },
      {
        name: '小型企业',
        value: '企业规模:小型企业',
        values: [],
      },
      {
        name: '微型企业',
        value: '企业规模:微型企业',
        values: [],
      },
      {
        name: '小微企业',
        value: '企业规模:小微企业',
        values: [],
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 84,
    itemName: '企业规模',
    itemField: 'corporation_tags3',
    itemRemark: '',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '初创期',
        value: '生命周期:初创期',
        values: [],
      },
      {
        name: '青春期',
        value: '生命周期:青春期',
        values: [],
      },
      {
        name: '成长期',
        value: '生命周期:成长期',
        values: [],
      },
      {
        name: '成熟期',
        value: '生命周期:成熟期',
        values: [],
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 86,
    itemName: '生命周期',
    itemField: 'corporation_tags3',
    logicOption: 'any',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        selfDefine: 0,
        itemOption: [
          {
            name: '主板',
            value: '2010000008',
            values: [],
          },
          {
            name: '科创板',
            value: '2010037380',
            values: [],
          },
          {
            name: '创业板',
            value: '2010000010',
            values: [],
          },
          {
            name: '北交所',
            value: '2010037381',
            values: [],
          },
          {
            name: '新三板',
            value: '2010000024',
            values: [],
          },
          {
            name: '新四板',
            value: '2010000032',
            values: [],
          },
        ],
        hasExtra: false,
        parentId: 19,
        isVip: 1,
        itemId: 60,
        itemName: '上市/挂牌板块',
        itemField: 'market_type_code.keyword',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '是',
        value: 'true',
      },
      {
        name: '否',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 19,
    itemName: '是否上市/挂牌',
    itemField: 'market_type_code.keyword',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: 'bond_code',
    selfDefine: 0,
    itemOption: [
      {
        name: '有债券信息',
        value: 'true',
      },
      {
        name: '无债券信息',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 20,
    itemName: '有无债券信息',
    itemField: 'corp_tags|debt',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: '',
        selfDefine: 0,
        itemOption: [
          {
            name: '天使轮',
            value: '105001200,105001201,105001210',
            values: [],
          },
          {
            name: 'A轮',
            value:
              '105001300,105001301,105001308,105001315,105001316,105001309,105001310,105001302,105001303,105001304,105001305,105001311,105001312,105001313,105001317,105001314,105001306,105001307',
            values: [],
          },
          {
            name: 'B轮',
            value:
              '105001400,105001401,105001411,105001406,105001402,105001403,105001404,105001414,105001415,105001416,105001409,105001410,105001407',
            values: [],
          },
          {
            name: 'C轮',
            value:
              '105001500,105001501,105001502,105001503,105001504,105001511,105001512,105001508,105001509,105001506,105001507,105001510',
            values: [],
          },
          {
            name: 'D轮',
            value:
              '105001600,105001601,105001602,105001603,105001604,105001605,105001610,105001611,105001608,105001609,105001606,105001607',
            values: [],
          },
          {
            name: 'E轮',
            value:
              '105001700,105001701,105001702,105001703,105001704,105001705,105001710,105001711,105001708,105001709,105001706,105001707',
            values: [],
          },
          {
            name: 'F轮',
            value:
              '105001801,105001900,105001804,105001903,105001901,105001803,105001902,105001800,105002020,105002000,105002200,105002010,105002800',
            values: [],
          },
          {
            name: 'IPO',
            value: '105002201',
            values: [],
          },
          {
            name: 'Post-IPO',
            value: '105002801',
            values: [],
          },
          {
            name: '战略融资',
            value: '105002100',
            values: [],
          },
        ],
        hasExtra: false,
        parentId: 17,
        isVip: 1,
        itemId: 18,
        itemName: '融资轮次',
        itemField: 'financing_round',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有PEVC融资',
        value: 'true',
      },
      {
        name: '无PEVC融资',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 17,
    itemName: '有无PEVC融资',
    itemField: 'count.pevc_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有银行借款',
        value: 'true',
      },
      {
        name: '无银行借款',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 112,
    itemName: '是否有银行借款',
    itemField: 'bank_loan_start',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'foreign invest number',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 13,
        isVip: 1,
        itemId: 14,
        itemName: '对外投资数量',
        itemField: 'count.foreign_invest_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'foreign invest',
    selfDefine: 0,
    itemOption: [
      {
        name: '有对外投资',
        value: 'true',
      },
      {
        name: '无对外投资',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 13,
    itemName: '有无对外投资',
    itemField: 'count.foreign_invest_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: '',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 125,
        isVip: 0,
        itemId: 126,
        itemName: '并购事件数量',
        itemField: 'merger_acquisition_num',
        logicOption: 'range',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有并购信息',
        value: 'true',
      },
      {
        name: '无并购信息',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 125,
    itemName: '有无并购信息',
    itemField: 'merger_acquisition_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        itemEn: 'position_name',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 101,
        isVip: 1,
        itemId: 102,
        itemName: '招聘职位名称',
        itemField: 'position_name',
        logicOption: 'any',
      },
    ],
    itemEn: 'position_name',
    selfDefine: 0,
    itemOption: [
      {
        name: '有招聘',
        value: 'true',
      },
      {
        name: '无招聘',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 101,
    itemName: '是否有招聘',
    itemField: 'position_name',
    logicOption: 'bool',
  },
]

export const mockQualificationFilterConfig: FilterConfigItem[] = [
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: '',
        selfDefine: 0,
        itemOption: [
          {
            name: '2014',
            value: '2014',
          },
          {
            name: '2015',
            value: '2015',
          },
          {
            name: '2016',
            value: '2016',
          },
          {
            name: '2017',
            value: '2017',
          },
          {
            name: '2018',
            value: '2018',
          },
          {
            name: '2019',
            value: '2019',
          },
          {
            name: '2020',
            value: '2020',
          },
          {
            name: '2021',
            value: '2021',
          },
          {
            name: '2022',
            value: '2022',
          },
          {
            name: '2023',
            value: '2023',
          },
          {
            name: '2024',
            value: '2024',
          },
        ],
        hasExtra: false,
        parentId: 135,
        isVip: 1,
        itemId: 136,
        itemName: '入选年度',
        itemField: 'selectedYear',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '是',
        value: 'true',
      },
      {
        name: '否',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 135,
    itemName: '是否A级纳税人',
    itemField: 'selectedYear',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: 'financial_license_code',
        selfDefine: 0,
        itemOption: [
          {
            hoverHint:
              '指中国银行业监督管理委员会依法颁发的特许金融机构经营金融业务的法律文件。金融许可证适用于银监会监管的、经批准经营金融业务的金融机构。',
            name: '金融许可证',
            value: '金融许可证',
          },
          {
            name: '保险许可证',
            value: '保险许可证',
          },
          {
            name: '保险中介许可证',
            value: '保险中介许可证',
          },
          {
            name: '小额贷款公司经营许可',
            value: '小额贷款公司经营许可',
          },
        ],
        hasExtra: false,
        parentId: 115,
        isVip: 1,
        itemId: 116,
        itemName: '银保监会颁发',
        itemField: 'financial_license_code',
        logicOption: 'any',
      },
      {
        itemType: '3',
        itemEn: 'financial_license_code',
        selfDefine: 0,
        itemOption: [
          {
            name: '支付业务许可',
            value: '支付业务许可',
          },
          {
            name: '银行卡清算业务许可',
            value: '银行卡清算业务许可',
          },
          {
            name: '国库集中支付代理银行资格认定',
            value: '国库集中支付代理银行资格认定',
          },
          {
            name: '黄金及其制品进出口行政许可',
            value: '黄金及其制品进出口行政许可',
          },
        ],
        hasExtra: false,
        parentId: 115,
        isVip: 1,
        itemId: 117,
        itemName: '人民银行颁发',
        itemField: 'financial_license_code',
        logicOption: 'any',
      },
      {
        itemType: '3',
        itemEn: 'financial_license_code',
        selfDefine: 0,
        itemOption: [
          {
            name: '经营证券期货业务许可',
            value: '经营证券期货业务许可',
          },
        ],
        hasExtra: false,
        parentId: 115,
        isVip: 1,
        itemId: 118,
        itemName: '证监会颁发',
        itemField: 'financial_license_code',
        logicOption: 'any',
      },
      {
        itemType: '3',
        itemEn: 'financial_license_code',
        selfDefine: 0,
        itemOption: [
          {
            name: '融资担保业务经营许可',
            value: '融资担保业务经营许可',
          },
        ],
        hasExtra: false,
        parentId: 115,
        isVip: 1,
        itemId: 119,
        itemName: '金融局颁发',
        itemField: 'financial_license_code',
        logicOption: 'any',
      },
    ],
    itemEn: 'financial_license_code',
    selfDefine: 0,
    itemOption: [
      {
        name: '有金融许可',
        value: 'true',
      },
      {
        name: '无金融许可',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 115,
    itemName: '有无金融许可',
    hoverHint: '指金融机构行政许可，包含银保监会、人民银行、证监会和金融局办法的所有许可证书',
    itemField: 'financial_license_code',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有征信备案',
        value: 'true',
      },
      {
        name: '无征信备案',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 100,
    itemName: '有无征信备案',
    itemField: 'creditfiling_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有行政许可',
        value: 'true',
      },
      {
        name: '无行政许可',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 1,
    isVip: 1,
    itemId: 134,
    itemName: '有无行政许可',
    itemField: 'adminLicense_nested',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: '',
        selfDefine: 0,
        itemOption: [
          {
            name: '报关企业分支机构',
            value: '912030001',
          },
          {
            name: '进出口货物收发货人',
            value: '912030002',
          },
          {
            name: '临时注册登记单位',
            value: '912030003',
          },
          {
            name: '无进出口经营权的加工生产企业',
            value: '68886719',
          },
          {
            name: '出口监管仓库',
            value: '68886720',
          },
          {
            name: '无报关权的其他企业',
            value: '68886721',
          },
          {
            name: '特殊监管区双重身份企业',
            value: '68886722',
          },
          {
            name: '进出境运输工具负责人',
            value: '68886723',
          },
          {
            name: '保税仓库',
            value: '68886724',
          },
          {
            name: '进出口收发货人分支机构',
            value: '68886725',
          },
          {
            name: '报关企业',
            value: '68886726',
          },
        ],
        hasExtra: false,
        parentId: 22,
        isVip: 1,
        itemId: 23,
        itemName: '进出口信用经营类别',
        itemField: 'iecreditBusinesscategoryCode',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有进出口信用信息',
        value: 'true',
      },
      {
        name: '无进出口信用信息',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 22,
    itemName: '有无进出口信用信息',
    itemField: 'iecreditBusinesscategoryCode',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '3',
        itemEn: '',
        selfDefine: 0,
        itemOption: [
          {
            name: 'A',
            value: '7053813503',
          },
          {
            name: 'AA',
            value: '7053813246',
          },
          {
            name: 'AAA',
            value: '7053813502',
          },
        ],
        hasExtra: false,
        parentId: 104,
        isVip: 1,
        itemId: 105,
        itemName: '物流企业信用评价等级',
        itemField: 'logistics_ent_credit_rating.keyword',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有物流企业信用评级',
        value: 'true',
      },
      {
        name: '无物流企业信用评级',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 104,
    itemName: '有无物流企业信用评级',
    itemField: 'logistics_ent_credit_rating.keyword',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '4',
        itemEn: '',
        selfDefine: 0,
        itemOption: [
          {
            name: '一级',
            value: '107002001',
          },
          {
            name: '二级',
            value: '107002002',
          },
          {
            name: '三级',
            value: '107002003',
          },
          {
            name: '四级',
            value: '107002004',
          },
          {
            name: '暂定级',
            value: '107002005',
          },
          {
            name: '暂定二级',
            value: '107002006',
          },
          {
            name: '暂定三级',
            value: '107002007',
          },
          {
            name: '暂定四级',
            value: '107002008',
          },
        ],
        hasExtra: false,
        parentId: 113,
        isVip: 1,
        itemId: 114,
        itemName: '房地产企业开发资质等级',
        itemField: 'redqualificationLevelCode',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有房地产企业开发资质',
        value: 'true',
      },
      {
        name: '无房地产企业开发资质',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 113,
    itemName: '有无房地产企业开发资质',
    itemField: 'redqualificationLevelCode',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        itemEn: 'qualifications',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 98,
        isVip: 1,
        itemId: 99,
        itemName: '建筑资质证书',
        itemField: 'qualifications',
        logicOption: 'any',
      },
    ],
    itemEn: 'qualification_no',
    selfDefine: 0,
    itemOption: [
      {
        name: '有建筑资质',
        value: 'true',
      },
      {
        name: '无建筑资质',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 98,
    itemName: '有无建筑资质',
    itemField: 'qualification_no',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有商业特许经营',
        value: 'true',
      },
      {
        name: '无商业特许经营',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 137,
    itemName: '有无商业特许经营',
    itemField: 'count.businessfranchise_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        itemEn: '',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 143,
        isVip: 1,
        itemId: 144,
        itemName: '认证认可证书类型',
        itemField: 'certificationAccrediation_nested.certificateType',
        logicOption: 'any',
      },
      {
        itemId: 145,
        itemName: '认证认可到期日期',
        itemType: '4',
        itemEn: '',
        selfDefine: 4,
        itemField: 'certificationAccrediation_nested.expireDate',
        itemRemark: '年月日',
        logicOption: 'range',
        hasExtra: false,
        parentId: 143,
        isVip: 1,
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有认证认可',
        value: 'true',
      },
      {
        name: '无认证认可',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 143,
    itemName: '有无认证认可',
    itemField: 'certificationAccrediation_nested',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有金融APP备案',
        value: 'true',
      },
      {
        name: '无金融APP备案',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 153,
    itemName: '有无金融APP备案',
    itemField: 'corp_business_tags|financialAppAppr',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        itemEn: '',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 154,
        isVip: 1,
        itemId: 155,
        itemName: '化妆品生产许可内容',
        itemField: 'cosmeticsProductionLicenseContent',
        logicOption: 'any',
      },
    ],
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有化妆品生产许可',
        value: 'true',
      },
      {
        name: '无化妆品生产许可',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 154,
    itemName: '有无化妆品生产许可',
    itemField: 'corp_business_tags|cosmeticsLicense',
    logicOption: 'bool',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '道路机动车辆产品准入许可',
        value: 'vehicleAppr',
      },
      {
        name: '甘草麻黄草收购许可',
        value: 'purchaseLicoriceEphedraAppr',
      },
      {
        name: '食盐批发或生产许可',
        value: 'saltAppr',
      },
      {
        name: '设置5G电台(站)许可',
        value: '5GBaseStationAppr',
      },
      {
        name: '监控化学品生产相关许可',
        value: 'monitoringChemicalProductionAppr',
      },
      {
        name: '监控化学品使用经营许可',
        value: 'monitoringChemicalOperatingAppr',
      },
      {
        name: '道路机动车辆生产企业准入许可',
        value: 'produceVehicleCompanyAppr',
      },
      {
        name: '无线电许可',
        value: 'radioAppr',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 156,
    itemName: '工信部许可内容',
    itemField: 'corp_business_tags',
    logicOption: 'any',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有互联网信息服务算法备案',
        value: 'true',
      },
      {
        name: '无互联网信息服务算法备案',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 157,
    itemName: '有无互联网信息服务算法备案',
    itemField: 'corp_business_tags|internetAlgorithmAppr',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有直销产品',
        value: 'true',
      },
      {
        name: '无直销产品',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 158,
    itemName: '有无直销产品',
    itemField: 'corp_business_tags|districtSaleProduct',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有建筑工程施工许可',
        value: 'true',
      },
      {
        name: '无建筑工程施工许可',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 159,
    itemName: '有无建筑工程施工许可',
    itemField: 'corp_business_tags|constructionAppr',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有安全生产许可',
        value: 'true',
      },
      {
        name: '无安全生产许可',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 160,
    itemName: '有无安全生产许可',
    itemField: 'corp_business_tags|safetyProductionAppr',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '有施工图审查机构资质',
        value: 'true',
      },
      {
        name: '无施工图审查机构资质',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 161,
    itemName: '有无施工图审查机构资质',
    itemField: 'corp_business_tags|constructionDrawingReviewAppr',
    logicOption: 'bool',
  },
]

export const mockIPFilterConfig: FilterConfigItem[] = [
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'trademark number',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 28,
        isVip: 1,
        itemId: 30,
        itemName: '商标数量',
        itemField: 'count.trademark_num',
        logicOption: 'range',
      },
      {
        itemType: '3',
        itemEn: 'business_status',
        selfDefine: 0,
        itemOption: [
          {
            name: '已注册',
            value: '商标已注册',
          },
          {
            name: '商标申请',
            value: '商标注册申请中',
          },
          {
            name: '初审公告',
            value: '商标初步审定公告',
          },
          {
            name: '终止',
            value:
              '有退信(注册人死亡/终止注销商标申请核准通知书),注册人死亡/终止注销商标申请完成,排版送达公告(注册人死亡/终止注销商标申请结案通知书),有退信(注册人死亡/终止注销商标申请不予核准通知书),有退信(注册人死亡/终止注销商标申请答辩通知书),排版送达公告(注册人死亡/终止注销商标申请答辩补正通知书),排版送达公告(注册人死亡/终止注销商标申请答辩通知书),有退信(注册人死亡/终止注销商标申请答辩补正通知书),排版送达公告(注册人死亡/终止注销商标申请核准通知书),注册人死亡/终止注销商标申请中,提前终止公告排版,排版送达公告(注册人死亡/终止注销商标申请不予核准通知书),有退信(注册人死亡/终止注销商标申请结案通知书),领退信(注册人死亡/终止注销商标申请不予核准通知书),商标使用许可合同提取终止中',
          },
        ],
        hasExtra: false,
        parentId: 28,
        isVip: 1,
        itemId: 24,
        itemName: '商标状态',
        itemField: 'business_status',
        logicOption: 'any',
      },
      {
        itemType: '2',
        itemEn: 'brand_name',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 28,
        isVip: 1,
        itemId: 25,
        itemName: '商标名称',
        itemField: 'brand_name',
        logicOption: 'any',
      },
      {
        itemId: 26,
        itemName: '商标申请日期',
        itemType: '4',
        itemEn: 'application_date',
        selfDefine: 4,
        itemField: 'application_date',
        itemRemark: '年月日',
        logicOption: 'range',
        hasExtra: false,
        parentId: 28,
        isVip: 1,
      },
    ],
    itemEn: 'brand_name',
    selfDefine: 0,
    itemOption: [
      {
        name: '有商标',
        value: 'true',
      },
      {
        name: '无商标',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 28,
    itemName: '有无商标',
    itemField: 'count.trademark_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'patent number',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 31,
        isVip: 1,
        itemId: 32,
        itemName: '专利数量',
        itemField: 'count.patent_num',
        logicOption: 'range',
      },
      {
        itemType: '3',
        itemEn: 'law_status',
        selfDefine: 0,
        itemOption: [
          {
            name: '公布',
            value: '913005000',
          },
          {
            name: '实质审查',
            value: '913009000',
          },
          {
            name: '授权',
            value: '913010000',
          },
          {
            name: '专利权的终止',
            value: '913014000,913014001,913014002,913014003',
          },
          {
            name: '发明专利申请公布后的驳回',
            value: '913001002',
          },
          {
            name: '发明专利申请公布后的视为撤回',
            value: '913002002',
          },
        ],
        hasExtra: false,
        parentId: 31,
        isVip: 1,
        itemId: 48,
        itemName: '专利法律状态',
        itemField: 'law_status',
        logicOption: 'any',
      },
      {
        itemType: '3',
        itemEn: 'patent_type',
        selfDefine: 0,
        itemOption: [
          {
            name: '发明专利',
            value: '发明专利',
          },
          {
            name: '实用新型专利',
            value: '实用新型专利',
          },
          {
            name: '外观设计',
            value: '外观设计',
          },
        ],
        hasExtra: false,
        parentId: 31,
        isVip: 0,
        itemId: 49,
        itemName: '专利类型',
        itemField: 'patent_type',
        logicOption: 'any',
      },
      {
        itemType: '2',
        itemEn: 'patent',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 31,
        isVip: 1,
        itemId: 50,
        itemName: '专利名称',
        itemField: 'patent',
        logicOption: 'any',
      },
      {
        itemId: 51,
        itemName: '专利申请日期',
        itemType: '4',
        itemEn: 'patent_apply_date',
        selfDefine: 4,
        itemField: 'patent_apply_date',
        itemRemark: '年月日',
        logicOption: 'range',
        hasExtra: false,
        parentId: 31,
        isVip: 1,
      },
      {
        itemId: 52,
        itemName: '专利公开日期',
        itemType: '4',
        itemEn: 'patent_publication_date',
        selfDefine: 4,
        itemField: 'patent_publication_date',
        itemRemark: '年月日',
        logicOption: 'range',
        hasExtra: false,
        parentId: 31,
        isVip: 1,
      },
    ],
    itemEn: 'patent',
    selfDefine: 0,
    itemOption: [
      {
        name: '有专利',
        value: 'true',
      },
      {
        name: '无专利',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 31,
    itemName: '有无专利',
    itemField: 'count.patent_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 35,
        isVip: 1,
        itemId: 36,
        itemName: '作品著作权数量',
        itemField: 'count.work_copyright_num',
        logicOption: 'range',
      },
      {
        itemType: '2',
        itemEn: 'production_copyright',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 35,
        isVip: 1,
        itemId: 95,
        itemName: '作品名称',
        itemField: 'production_copyright',
        logicOption: 'any',
      },
    ],
    itemEn: 'production_copyright',
    selfDefine: 0,
    itemOption: [
      {
        name: '有作品著作权',
        value: 'true',
      },
      {
        name: '无作品著作权',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 35,
    itemName: '有无作品著作权',
    itemField: 'count.work_copyright_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'count.software_copyright_num',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 33,
        isVip: 1,
        itemId: 34,
        itemName: '软著数量',
        itemField: 'count.software_copyright_num',
        logicOption: 'range',
      },
      {
        itemType: '2',
        itemEn: 'software_copyright',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 33,
        isVip: 1,
        itemId: 96,
        itemName: '软件名称',
        itemField: 'software_copyright',
        logicOption: 'any',
      },
    ],
    itemEn: 'software_copyright',
    selfDefine: 0,
    itemOption: [
      {
        name: '有软著',
        value: 'true',
      },
      {
        name: '无软著',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 33,
    itemName: '有无软著',
    itemField: 'count.software_copyright_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '是',
        value: 'true',
      },
      {
        name: '否',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 133,
    itemName: '是否参与标准信息制定',
    itemField: 'standard_info',
    logicOption: 'bool',
  },
  {
    itemType: '2',
    itemEn: 'app_name',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 38,
    itemName: 'APP产品名称',
    itemField: 'app_name',
    logicOption: 'any',
  },
]

export const mockMediaFilterConfig: FilterConfigItem[] = [
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 39,
        isVip: 1,
        itemId: 40,
        itemName: '微信公众号数量',
        itemField: 'count.wechat_public_num',
        logicOption: 'range',
      },
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 39,
        isVip: 1,
        itemId: 41,
        itemName: '微信公众号名称',
        itemField: 'wechat_name',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有微信公众号',
        value: 'true',
      },
      {
        name: '无微信公众号',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 39,
    itemName: '有无微信公众号',
    itemField: 'count.wechat_public_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 46,
        isVip: 1,
        itemId: 47,
        itemName: '头条号数量',
        itemField: 'count.today_headline_num',
        logicOption: 'range',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有头条号',
        value: 'true',
      },
      {
        name: '无头条号',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 46,
    itemName: '有无头条号',
    itemField: 'count.today_headline_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 44,
        isVip: 1,
        itemId: 45,
        itemName: '网站数量',
        itemField: 'count.domain_num',
        logicOption: 'range',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有网站备案',
        value: 'true',
      },
      {
        name: '无网站备案',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 0,
    itemId: 44,
    itemName: '有无网站(ICP备案)',
    itemField: 'count.domain_num',
    logicOption: 'bool',
  },
]

export const mockBidFilterConfig: FilterConfigItem[] = [
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        itemEn: 'bidding_subject_name',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 42,
        isVip: 1,
        itemId: 43,
        itemName: '招标产品',
        itemField: 'bidding_subject_name',
        logicOption: 'any',
      },
    ],
    itemEn: 'bidding',
    selfDefine: 0,
    itemOption: [
      {
        name: '有对外招标',
        value: 'true',
      },
      {
        name: '无对外招标',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 42,
    itemName: '有无对外招标',
    itemField: 'corp_tags|bidding',
    logicOption: 'bool',
  },
]

export const mockFeatureFilterConfig: FilterConfigItem[] = [
  {
    searchPlaceholder: '请输入关键词',
    itemType: '91',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        certYear: 0,
        id: '2010202098|108020101',
        name: '高新技术企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202479|108020113',
        name: '科技小巨人企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202470|108020102',
        name: '科技型中小企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202482|108020118',
        name: '初创科技型企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010100370|108020119',
        name: '专精特新小巨人企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202505|108020136',
        name: '重点专精特新小巨人企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010202471|108020116',
        name: '专精特新中小企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202500|108020137',
        name: '创建世界一流示范企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202501|108020138',
        name: '创建世界一流专精特新示范企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202481|108020117',
        name: '民营科技企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202480|108020115',
        name: '技术先进型服务企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010202474|108020105',
        name: '瞪羚企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202478|108020112',
        name: '雏鹰企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010202495|108020111',
        name: '企业技术中心',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202498|108020139',
        name: '双百企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010202499|108020140',
        name: '科改企业',
        validDate: 0,
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 138,
    itemName: '科技型企业名录',
    itemField: 'corpListDetailQueryLogic',
    logicOption: 'any',
  },
  {
    searchPlaceholder: '请输入关键词',
    itemType: '91',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        certYear: 0,
        id: '2010202489|108020121',
        name: '中华老字号',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202476|108020109',
        name: '创新型企业',
        validDate: 0,
      },
      {
        certYear: 0,
        id: '2010202496|108020135',
        name: '创新型中小企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202477|108020110',
        name: '隐形冠军企业',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202566|108020097,108020098,108020099',
        name: '制造业单项冠军企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010100369|108020097',
        name: '制造业单项冠军示范企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202513|108020098',
        name: '制造业单项冠军培育企业',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202514|108020099',
        name: '制造业单项冠军产品企业',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202472|108020103',
        name: '双软企业',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202506|108020142',
        name: '联合国责任投资原则组织全球企业',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202507|108020141',
        name: '联合国责任投资原则组织国内企业',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202510|108020146',
        name: '知识产权优势企业\r\n',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202509|108020147',
        name: '知识产权示范企业\r\n',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202511|108020148',
        name: '企业工业设计中心\r\n',
        validDate: 1,
      },
      {
        certYear: 0,
        id: '2010202512|108020149',
        name: '工业设计企业\r\n',
        validDate: 1,
      },
      {
        certYear: 1,
        id: '2010202515|108020194',
        name: '机电产品再制造试点单位',
        validDate: 0,
      },
      {
        certYear: 1,
        id: '2010202567|108020195',
        name: '农业产业化国家重点龙头企业',
        validDate: 0,
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 139,
    itemName: '特色企业名录',
    itemField: 'corpListDetailQueryLogic',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        certYear: 0,
        name: '国资委实际控股企业',
        validDate: 0,
        value: '2010100011',
      },
      {
        certYear: 0,
        name: '国资委直接参股企业',
        validDate: 0,
        value: '2010100012',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 122,
    itemName: '国企名录',
    itemField: 'listing_tags_id',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        certYear: 0,
        name: '教育部直属高校',
        validDate: 0,
        value: '2010100689',
      },
      {
        certYear: 0,
        name: '双一流院校',
        validDate: 0,
        value: '2010100692,2010100693',
      },
      {
        certYear: 0,
        name: '双高院校',
        validDate: 0,
        value: '2010100695,2010100696',
      },
      {
        certYear: 0,
        name: '985工程院校',
        validDate: 0,
        value: '2010100697',
      },
      {
        certYear: 0,
        name: '211工程院校',
        validDate: 0,
        value: '2010100698',
      },
      {
        certYear: 0,
        name: '101计划高校',
        validDate: 0,
        value: '2010100701',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 123,
    itemName: '高校名录',
    itemField: 'listing_tags_id',
    logicOption: 'any',
  },
  {
    itemType: '3',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        certYear: 0,
        name: '绿色工厂',
        validDate: 0,
        value: '2010202491',
      },
      {
        certYear: 0,
        name: '绿色供应链管理企业',
        validDate: 0,
        value: '2010202492',
      },
      {
        certYear: 0,
        name: '全国碳排放权交易配额管理企业',
        validDate: 0,
        value: '2010202497',
      },
      {
        certYear: 0,
        name: '重点用能行业能效领跑者',
        validDate: 0,
        value: '2010202516',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    itemId: 124,
    itemName: '绿色名录',
    itemField: 'listing_tags_id',
    logicOption: 'any',
  },
  {
    itemType: '3',
    selfDefine: 0,
    itemOption: [
      {
        itemOption: [
          {
            name: '政策性银行',
            label: '政策性银行',
            value: '1000034381000000',
          },
          {
            name: '国有商业银行',
            label: '国有商业银行',
            value: '1000034408000000',
          },
          {
            name: '股份制商业银行',
            label: '股份制商业银行',
            value: '1000034409000000',
          },
          {
            name: '城市商业银行',
            label: '城市商业银行',
            value: '1000034410000000',
          },
          {
            name: '农村商业银行',
            label: '农村商业银行',
            value: '1000034411000000',
          },
          {
            name: '民营银行',
            label: '民营银行',
            value: '1000034414000000',
          },
          {
            name: '外资银行',
            label: '外资银行',
            value: '1000034382000000',
          },
          {
            name: '其他商业银行',
            label: '其他商业银行',
            value: '0409019900000000,1000048454000000',
          },
          {
            name: '农村合作银行',
            label: '农村合作银行',
            value: '1000034412000000',
          },
          {
            name: '村镇银行',
            label: '村镇银行',
            value: '1000034413000000',
          },
          {
            name: '农村信用社',
            label: '农村信用社',
            value: '1000034416000000',
          },
          {
            name: '农村资金互助社',
            label: '农村资金互助社',
            value: '1000048455000000',
          },
        ],
        name: '银行',
        value: [
          '1000034381000000',
          '1000034408000000',
          '1000034409000000',
          '1000034410000000',
          '1000034411000000',
          '1000034414000000',
          '1000034382000000',
          '0409019900000000',
          '1000048454000000',
          '1000034412000000',
          '1000034413000000',
          '1000034416000000',
          '1000048455000000',
        ],
      },
      {
        itemOption: [
          {
            name: '保险集团公司',
            label: '保险集团公司',
            value: '1000034384000000',
          },
          {
            name: '财产险公司',
            label: '财产险公司',
            value: '1000034385000000',
          },
          {
            name: '人身险公司',
            label: '人身险公司',
            value: '1000034386000000',
          },
          {
            name: '再保险公司',
            label: '再保险公司',
            value: '1000034387000000',
          },
          {
            name: '养老险公司',
            label: '养老险公司',
            value: '1000045100000000',
          },
        ],
        name: '保险公司',
        value: ['1000034384000000', '1000034385000000', '1000034386000000', '1000034387000000', '1000045100000000'],
      },
      {
        name: '证券公司',
        value: '1000034377000000',
      },
      {
        name: '期货公司',
        value: '1000034378000000',
      },
      {
        itemOption: [
          {
            name: '基金公司',
            label: '基金公司',
            value: '1000034388000000',
          },
          {
            name: '银行资产管理',
            label: '银行资产管理',
            value: '1000034389000000',
          },
          {
            name: '保险资产管理',
            label: '保险资产管理',
            value: '1000034390000000',
          },
          {
            name: '券商资产管理',
            label: '券商资产管理',
            value: '1000034391000000',
          },
          {
            name: '期货资产管理',
            label: '期货资产管理',
            value: '1000034395000000',
          },
          {
            name: '信托公司',
            label: '信托公司',
            value: '1000034392000000',
          },
          {
            name: '基金特定资产管理公司',
            label: '基金特定资产管理公司',
            value: '1000034393000000',
          },
          {
            name: '期货公司风险管理子公司',
            label: '期货公司风险管理子公司',
            value: '1000034394000000',
          },
        ],
        name: '资产管理',
        value: [
          '1000034388000000',
          '1000034389000000',
          '1000034390000000',
          '1000034391000000',
          '1000034395000000',
          '1000034392000000',
          '1000034393000000',
          '1000034394000000',
        ],
      },
      {
        itemOption: [
          {
            name: '财务公司',
            label: '财务公司',
            value: '1000034399000000',
          },
          {
            name: '货币经纪公司',
            label: '货币经纪公司',
            value: '1000034401000000',
          },
          {
            name: '金融租赁公司',
            label: '金融租赁公司',
            value: '1000034402000000',
          },
          {
            name: '金融资产管理公司',
            label: '金融资产管理公司',
            value: '1000034404000000',
          },
          {
            name: '汽车金融公司',
            label: '汽车金融公司',
            value: '1000034405000000',
          },
          {
            name: '消费金融公司',
            label: '消费金融公司',
            value: '1000034406000000',
          },
          {
            name: '其他金融机构',
            label: '其他金融机构',
            value: '1000048456000000',
          },
        ],
        name: '其他金融机构',
        value: [
          '1000034399000000',
          '1000034401000000',
          '1000034402000000',
          '1000034404000000',
          '1000034405000000',
          '1000034406000000',
          '1000048456000000',
        ],
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 106,
    itemName: '金融机构',
    multiCbx: 1,
    itemField: 'finance_type_code',
    logicOption: 'any',
  },
  {
    itemType: '5',
    itemEn: '',
    selfDefine: 0,
    itemOption: [
      {
        name: '是',
        value: 'true',
      },
      {
        name: '否',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 27,
    itemName: '是否城投公司',
    itemField: 'corp_tags|urban',
    logicOption: 'bool',
  },
  {
    searchPlaceholder: '请输入榜单名称',
    itemType: '9',
    key4ajax: 'keyword',
    itemEn: '',
    selfDefine: 0,
    itemOption: [],
    hasExtra: false,
    parentId: 0,
    isVip: 0,
    cmd4ajax: 'corplistpersearch',
    itemId: 83,
    itemName: '上榜榜单',
    itemField: 'listing_tags_id',
    logicOption: 'any',
  },
]

export const mockRiskFilterConfig: FilterConfigItem[] = [
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '5',
        extraConfig: [
          {
            itemType: '2',
            selfDefine: 0,
            itemOption: [],
            hasExtra: false,
            parentId: 64,
            isVip: 1,
            itemId: 65,
            itemName: '当前被列入经营异常的原因',
            itemField: 'current_abnormal_operations_cause',
            logicOption: 'any',
          },
        ],
        selfDefine: 0,
        itemOption: [
          {
            name: '是',
            value: 'true',
          },
          {
            name: '否',
            value: 'false',
          },
        ],
        hasExtra: true,
        parentId: 63,
        isVip: 1,
        itemId: 64,
        itemName: '当前是否经营异常',
        itemField: 'current_abnormal_operations',
        logicOption: 'bool',
      },
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 63,
        isVip: 1,
        itemId: 66,
        itemName: '历史被列入经营异常的原因',
        itemField: 'his_abnormal_operations_cause',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有经营异常',
        value: 'true',
      },
      {
        name: '无经营异常',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 63,
    itemName: '有无经营异常',
    itemField: 'abnormal_operations',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    selfDefine: 0,
    itemOption: [
      {
        name: '有失信信息',
        value: 'true',
      },
      {
        name: '无失信信息',
        value: 'false',
      },
    ],
    hasExtra: false,
    parentId: 0,
    isVip: 1,
    itemId: 76,
    itemName: '有无失信信息',
    itemField: 'break_promise',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 67,
        isVip: 1,
        itemId: 68,
        itemName: '行政处罚事由',
        itemField: 'administrative_penalties_cause',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有行政处罚',
        value: 'true',
      },
      {
        name: '无行政处罚',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 67,
    itemName: '有无行政处罚',
    itemField: 'administrative_penalties_cause',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 69,
        isVip: 1,
        itemId: 70,
        itemName: '严重违法事由',
        itemField: 'serious_illegal_acts_cause',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有严重违法',
        value: 'true',
      },
      {
        name: '无严重违法',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 69,
    itemName: '是否有严重违法',
    itemField: 'serious_illegal_acts_cause',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'tax_arrears_num',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 71,
        isVip: 1,
        itemId: 72,
        itemName: '欠税信息数量',
        itemField: 'tax_arrears_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'tax_arrears_num',
    selfDefine: 0,
    itemOption: [
      {
        name: '有欠税信息',
        value: 'true',
      },
      {
        name: '无欠税信息',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 71,
    itemName: '是否有欠税信息',
    itemField: 'tax_arrears_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'illegal_tax_num',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 87,
        isVip: 1,
        itemId: 88,
        itemName: '税收违法数量',
        itemField: 'illegal_tax_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'illegal_tax_num',
    selfDefine: 0,
    itemOption: [
      {
        name: '有税收违法',
        value: 'true',
      },
      {
        name: '无税收违法',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 87,
    itemName: '是否有税收违法信息',
    itemField: 'illegal_tax_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 73,
        isVip: 1,
        itemId: 74,
        itemName: '裁判文书案由',
        itemField: 'legal_papers_cause',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有裁判文书',
        value: 'true',
      },
      {
        name: '无裁判文书',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 73,
    itemName: '有无裁判文书',
    itemField: 'legal_papers_cause',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '2',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 81,
        isVip: 1,
        itemId: 82,
        itemName: '开庭公告案由',
        itemField: 'court_session_cause',
        logicOption: 'any',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有开庭公告',
        value: 'true',
      },
      {
        name: '无开庭公告',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 81,
    itemName: '有无开庭公告',
    itemField: 'court_session_cause',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'judicial_assistances_num',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 91,
        isVip: 1,
        itemId: 92,
        itemName: '司法协助数量',
        itemField: 'judicial_assistances_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'judicial_assistances_num',
    selfDefine: 0,
    itemOption: [
      {
        name: '有司法协助',
        value: 'true',
      },
      {
        name: '无司法协助',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 91,
    itemName: '是否有司法协助',
    itemField: 'judicial_assistances_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        itemEn: 'judicial_sale_num',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 93,
        isVip: 1,
        itemId: 94,
        itemName: '司法拍卖数量',
        itemField: 'judicial_sale_num',
        logicOption: 'range',
      },
    ],
    itemEn: 'judicial_sale_num',
    selfDefine: 0,
    itemOption: [
      {
        name: '有司法拍卖',
        value: 'true',
      },
      {
        name: '无司法拍卖',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 93,
    itemName: '是否有司法拍卖',
    itemField: 'judicial_sale_num',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 61,
        isVip: 1,
        itemId: 62,
        itemName: '动产抵押数量',
        itemField: 'chattel_mortgage',
        logicOption: 'range',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有',
        value: 'true',
      },
      {
        name: '无',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 61,
    itemName: '有无动产抵押',
    itemField: 'chattel_mortgage',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 108,
        isVip: 1,
        itemId: 109,
        itemName: '股权出质数量',
        itemField: 'equity_pledge',
        logicOption: 'range',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有股权出质',
        value: 'true',
      },
      {
        name: '无股权出质',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 108,
    itemName: '有无股权出质',
    itemField: 'equity_pledge',
    logicOption: 'bool',
  },
  {
    itemType: '5',
    extraConfig: [
      {
        itemType: '6',
        selfDefine: 0,
        itemOption: [],
        hasExtra: false,
        parentId: 110,
        isVip: 1,
        itemId: 111,
        itemName: '知识产权出质数量',
        itemField: 'intellectual_property_ledges',
        logicOption: 'range',
      },
    ],
    selfDefine: 0,
    itemOption: [
      {
        name: '有知识产权出质',
        value: 'true',
      },
      {
        name: '无知识产权出质',
        value: 'false',
      },
    ],
    hasExtra: true,
    parentId: 0,
    isVip: 1,
    itemId: 110,
    itemName: '有无知识产权出质',
    itemField: 'intellectual_property_ledges',
    logicOption: 'bool',
  },
]
