// 登录
export const REGESTER_LOGIN = 'REGESTER_LOGIN'
export const GET_VERIFYCODE = 'GET_VERIFYCODE'
export const LOGIN_OUT = 'LOGIN_OUT'
export const GET_QRCODE = 'GET_QRCODE'
export const WECHAT_REFRESH = 'WECHAT_REFRESH'

// 个人中心
export const GET_CUSTOME_SETTINGS = 'GET_CUSTOME_SETTINGS'
export const RECOMMEND_UPDATE = 'RECOMMEND_UPDATE'
export const NOTICE_QUERY = 'NOTICE_QUERY'
export const NOTICE_UPDATE = 'NOTICE_UPDATE'
export const GET_USER_INDUSTRY = 'GET_USER_INDUSTRY'
export const SET_USER_INDUSTRY = 'SET_USER_INDUSTRY'
export const GET_USER_SALE = 'GET_USER_SALE'
export const SET_USER_SALE = 'SET_USER_SALE'
export const MY_TERRITORY_LIST = 'MY_TERRITORY_LIST'
export const GET_FILES = 'GET_FILES'

// 首页
export const GET_USERPACKAGE = 'GET_USERPACKAGE' //获取用户权限
export const SET_USERPACKAGE_LOADED = 'SET_USERPACKAGE_LOADED' // 用户权限包是否获取过
export const GET_PRECORPSEARCH = 'GET_PRECORPSEARCH' //预搜索-企业
export const GET_PREGROUPSEARCH = 'GET_PREGROUPSEARCH' //预搜索-集团系
export const SHOW_VIPPOPUP = 'SHOW_VIPPOPUP' // 显示vip弹框
export const GET_PAYORDER = 'GET_PAYORDER' // 获取微信支付二维码
export const GET_PAYGOODS = 'GET_PAYGOODS' // 获取可开通的商品类型

export const GET_HOTCORP = 'GET_HOTCORP'
export const GET_CORPEVENT = 'GET_CORPEVENT'
export const GET_CORPNEWS = 'GET_CORPNEWS'
export const GET_ADS = 'GET_ADS'

export const SET_BIND_PHONE_MODAL = 'SET_BIND_PHONE_MODAL' // 绑定手机

// 全局配置
export const SET_GLOBAL_MODAL = 'SET_GLOBAL_MODAL'
export const CLEAR_GLOBAL_MODAL = 'CLEAR_GLOBAL_MODAL'
export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_GLOBAL_VIP_MODAL = 'SET_GLOBAL_VIP_MODAL'
export const SET_GLOBALSEARCH = 'SET_GLOBALSEARCH' // 搜索组件刷新当前路由

// 固定配置
export const GET_FILTER_ITEM = 'GET_FILTER_ITEM'
export const GET_REGIONS = 'GET_REGIONS'
export const GET_INDUSTRIES = 'GET_INDUSTRIES'

// 找客户
export const GET_INDICATOR = 'GET_INDICATOR'
export const SPEECH_SEARCH = 'SPEECH_SEARCH'
export const SEARCH = 'SEARCH'
export const MEASURE_SEARCH = 'MEASURE_SEARCH'
export const GET_MYSUSLIST = 'GET_MYSUSLIST'
export const GET_SEENLIST = 'GET_SEENLIST'
export const GET_FELLOWLIST = 'GET_FELLOWLIST'
export const CLEAR_SUBTYPE = 'CLEAR_SUBTYPE'
export const QUERY_USER_INDUSTRIES = 'QUERY_USER_INDUSTRIES'

// 订阅和收藏
export const TOGGLE_COLLECT = 'TOGGLE_COLLECT'
export const COLLECT_QUERY = 'COLLECT_QUERY'
export const GET_CONTACT_COLLECTION = 'GET_CONTACT_COLLECTION'

// 全局搜索框
export const SET_GLOBAL_SEARCH_KEYWORD = 'SET_GLOBAL_SEARCH_KEYWORD'

// 筛选结果页
export const RES_SUBSCRIBE = 'RES_SUBSCRIBE'
export const RES_DISSUBSCRIBE = 'RES_DISSUBSCRIBE'
export const CLEAR_DATAS = 'CLEAR_DATAS'
export const GET_CONTACT_BY_CROPID = 'GET_CONTACT_BY_CROPID'

// 模板
export const TEMPLATE_LIST = 'TEMPLATE_LIST'
export const TEMPLATE_QUERY = 'TEMPLATE_QUERY'
export const TEMPLATE_PRAISE = 'TEMPLATE_PRAISE'
export const TEMPLATE_RESET = 'TEMPLATE_RESET'

// 企业详情页
export const GET_COMPANYHEADER_INFO = 'GET_COMPANYHEADER_INFO'
export const GET_COMPANY_INFO = 'GET_COMPANY_INFO'
export const PAGE_SHAREHOLDER = 'PAGE_SHAREHOLDER'
export const QUERY_CROPNEWS = 'QUERY_CROPNEWS'
export const COMPANY_DETAIL_TOGGLE_COLLECT = 'COMPANY_DETAIL_TOGGLE_COLLECT'
export const COMPANY_TENDERING_INFO = 'COMPANY_TENDERING_INFO'
export const COMPANY_BIDDING_INFO = 'COMPANY_BIDDING_INFO'
export const COMPANY_TEL_INFO = 'COMPANY_TEL_INFO'
export const COMPANY_MAIL_INFO = 'COMPANY_MAIL_INFO'
export const COMPANY_BRANCH_INFO = 'COMPANY_BRANCH_INFO'
export const GET_COMPANY_CONFIG_LIST = 'GET_COMPANY_CONFIG_LIST'
export const SET_FEEDBACK_PARAM = 'SET_FEEDBACK_PARAM'
export const SET_COLLECT_STATE = 'SET_COLLECT_STATE'
export const SET_IS_OBJECTION = 'SET_IS_OBJECTION'

export const SET_CORP_MODULE_READYED = 'SET_CORP_MODULE_READYED' // 已经加载的module集合
export const GET_COMPANY_BASICNUM = 'GET_COMPANY_BASICNUM' // 获取统计数字
export const SET_COMPANY_CATEGORY = 'SET_COMPANY_CATEGORY' // 获取企业category - 公募基金、私募基金、医药、上市 等
export const SET_COMPANY_AREA = 'SET_COMPANY_AREA' // 获取企业地区 美韩日英等

// 招投标
export const BIDDING_FILTERITEMS = 'BIDDING_FILTERITEMS'
export const BIDDING_SEARCH = 'BIDDING_SEARCH'
export const BIDDING_CLEAR = 'BIDDING_CLEAR'
export const BIDDING_SUGGEST = 'BIDDING_SUGGEST'
export const BIDDING_DETAIL = 'BIDDING_DETAIL'
export const BIDDING_DETAIL_SUB = 'BIDDING_DETAIL_SUB'
export const BIDDING_DETAIL_SUB_REL = 'BIDDING_DETAIL_SUB_REL'
export const BIDDING_ATTACHMENT = 'BIDDING_ATTACHMENT'
export const BIDDING_PROCESS = 'BIDDING_PROCESS'

// 榜单名录
export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'
export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY'
export const DELETEALL_SEARCH_HISTORY = 'DELETEALL_SEARCH_HISTORY'
export const DELETEONE_SEARCH_HISTORY = 'DELETEONE_SEARCH_HISTORY'
export const ADD_VISIT_HISTORY = 'ADD_VISIT_HISTORY'
export const GET_VISIT_HISTORY = 'GET_VISIT_HISTORY'
export const DELETEALL_VISIT_HISTORY = 'DELETEALL_VISIT_HISTORY'
export const DELETEONE_VISIT_HISTORY = 'DELETEONE_VISIT_HISTORY'
export const RANKINGLIST_SEARCH_CROPS = 'RANKINGLIST_SEARCH_CROPS'
export const RANKINGLIST_SUGGEST = 'RANKINGLIST_SUGGEST'
export const RANKINGLIST_INPUT_SEARCH = 'RANKINGLIST_INPUT_SEARCH'
export const RANKINGLIST_TREE_SEARCH = 'RANKINGLIST_TREE_SEARCH'
export const RANKINGLIST_STATISTICS = 'RANKINGLIST_STATISTICS'
export const CLEAR_RANKINGLIST_DETAIL = 'CLEAR_RANKINGLIST_DETAIL'
export const GET_RANKINGLIST_TYPE = 'GET_RANKINGLIST_TYPE'

// 搜索结果页
export const SEARCH_COMPANY = 'SEARCH_COMPANY'
export const VIEW_COMPANY = 'VIEW_COMPANY'
export const VIEW_PERSON = 'VIEW_PERSON'
export const HOT_VIEW_COMPANY = 'HOT_VIEW_COMPANY'
export const SEARCH_GROUP = 'SEARCH_GROUP'
export const HOT_VIEW_GROUP = 'HOT_VIEW_GROUP'
export const HOT_VIEW_JOB = 'HOT_VIEW_JOB'
export const VIEW_JOB = 'VIEW_JOB'
export const SEARCH_JOB = 'SEARCH_JOB'
export const SEARCH_INTELLECTUAL = 'SEARCH_INTELLECTUAL'
export const SEARCH_PATENT = 'SEARCH_PATENT'
export const VIEW_INTELLECTUAL = 'VIEW_INTELLECTUAL'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const SEARCH_BID = 'SEARCH_BID'
export const VIEW_BID = 'VIEW_BID'
export const CLEAR_VIEW = 'CLEAR_VIEW'
export const COLLECT_CLIST = 'COLLECT_CLIST'
export const ADD_COLLECT = 'ADD_COLLECT'
export const SEARCH_OUTCOMPANY = 'SEARCH_OUTCOMPANY'
export const SEARCH_HOT_OUTCOMPANY = 'SEARCH_HOT_OUTCOMPANY'
export const SEARCH_HIS_OUTCOMPANY = 'SEARCH_HIS_OUTCOMPANY'
export const SEARCH_PERSON = 'SEARCH_PERSON'
export const VIEW_OUTCOMPANY = 'VIEW_OUTCOMPANY'
export const SEARCH_GLOBALWORLD = 'SEARCH_GLOBALWORLD'
