import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoSPE: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030504',
  biz_reg_no: '632724200000026',
  bus_address: '治多县城南规划区',
  business_scope: '纯净水、土特产、乳汁品、特色畜产品生产加工销售、种草林业服务、草原生态治理、草籽、运输、铺面出租',
  cancel_date: '20210402',
  configType: 'SPE',
  corp_id: '1004283596',
  corp_name: '治多县嘉洛珠姆工贸有限公司',
  corp_old_id: 'VyBi4xvrQg',
  corp_type: '个人独资企业',
  corp_type_id: 298010000,
  credit_code: '91632724661949512F',
  domainCount: 0,
  endowment_num: 3,
  eng_name: 'Zhido County Jialuozhum Industry and Trade Co, Ltd',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'A',
      industryName: '农、林、牧、渔业',
      type: 'gb',
      windId: '1004283596',
    },
    {
      industryCode: 'A03',
      industryName: '畜牧业',
      type: 'gb',
      windId: '1004283596',
    },
  ],
  industryGbFold: '农、林、牧、渔业-畜牧业',
  industryWindFold: '日常消费-食品饮料-食品-食品加工与肉类',
  industryWindFoldCode: '30202030',
  issue_date: '2021-04-02',
  legal_person_id: 'D48E46EA31C3CDE7335E8256534D487C',
  legal_person_name: '更松',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2008-08-08',
  oper_period_end: '',
  org_code: '91632724661949512F',
  overseasCorpIndustryList: [],
  paid_in_capital: 100,
  paid_in_capital_currency: 'CNY',
  paid_in_capital_currency_name: '人民币元',
  postal_address: '治多县城南规划区',
  province: '青海省',
  reg_address: '治多县城南规划区',
  reg_authority: '治多县市场监督管理局',
  reg_capital: 100,
  reg_date: '2008-08-08',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '20210402',
  scale: '微型企业',
  scaleAll: '微型企业',
  seIndustriesCount: 0,
  state: '注销',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
