import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoCO: CorpBasicInfo = {
  abbreviation: '比亚迪',
  anotherNames: null,
  areaCode: '030405',
  biz_reg_no: '440301501127941',
  bus_address: '广东省深圳市坪山新区比亚迪路3009号',
  business_scope:
    '锂离子电池以及其他电池、充电器、电子产品、仪器仪表、柔性线路板、五金制品、液晶显示器、手机零配件、模具、塑胶制品及其相关附件的生产、销售;3D眼镜、GPS导航产品的研发、生产及销售;货物及技术进出口(不含分销、国家专营专控商品);作为比亚迪汽车有限公司比亚迪品牌乘用车、电动车的总经销商,从事上述品牌的乘用车、电动车及其零部件的营销、批发和出口,提供售后服务;电池管理系统、换流柜、逆变柜/器、汇流箱、开关柜、储能机组的销售;汽车电子装置研发、销售;新能源汽车关键零部件研发以及上述零部件的关键零件、部件的研发、销售;轨道交通运输设备(含轨道交通车辆、工程机械、各类机电设备、电子设备及零部件、电子电气件、轨道交通信号系统、通信及综合监控系统与设备)的研发、设计、销售、租赁与售后服务(不涉及国营贸易管理商品,涉及配额、许可证管理及其他专项管理的商品,按国家有关规定办理申请);轨道梁柱的研发、设计、销售;自有物业租赁(物业位于大鹏新区葵涌街道延安路一号比亚迪工业园内及龙岗区龙岗街道宝龙工业城宝荷路3001号比亚迪工业园内);广告设计、制作、代理及发布;信息与技术咨询、技术服务。',
  cancel_date: '',
  configType: 'CO',
  corp_id: '1173319566',
  corp_name: '比亚迪股份有限公司',
  corp_old_id: '0PH88221AE',
  corp_type: '股份有限公司(台港澳与境内合资、上市)',
  corp_type_id: 298010000,
  credit_code: '91440300192317458F',
  domainCount: 0,
  endowment_num: 2945,
  eng_name: 'BYD Company Limited',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'C',
      industryName: '制造业',
      type: 'gb',
      windId: '1173319566',
    },
    {
      industryCode: 'C36',
      industryName: '汽车制造业',
      type: 'gb',
      windId: '1173319566',
    },
    {
      industryCode: 'C361',
      industryName: '汽车整车制造',
      type: 'gb',
      windId: '1173319566',
    },
    {
      industryCode: 'C3612',
      industryName: '新能源车整车制造',
      type: 'gb',
      windId: '1173319566',
    },
  ],
  industryGbFold: '制造业-汽车制造业-汽车整车制造-新能源车整车制造',
  industryWindFold: '可选消费-汽车与零配件-汽车-汽车制造',
  industryWindFoldCode: '142614863',
  issue_date: '2025-05-07',
  legal_person_id: '0D26A1E0339F59149C00C331CCB588B7',
  legal_person_name: '王传福',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '1995-02-10',
  oper_period_end: '2053-02-08',
  org_code: '91440300192317458F',
  overseasCorpIndustryList: [],
  paid_in_capital: 303906.6,
  paid_in_capital_currency: 'CNY',
  paid_in_capital_currency_name: '人民币元',
  postal_address: '深圳市大鹏新区葵涌街道延安路一号',
  province: '广东省',
  reg_address: '深圳市大鹏新区葵涌街道延安路一号',
  reg_authority: '深圳市市场监督管理局',
  reg_capital: 303906.5855,
  reg_date: '1995-02-10',
  reg_unit: 'CNY',
  reg_unit_name: '人民币元',
  revokeDate: '',
  revokeOrCancelDate: '',
  scale: '大型企业',
  scaleAll: '大型企业',
  seIndustriesCount: 40,
  state: '存续',
  taxIdNo: '91440300192317458F',
  taxQualiType: '增值税一般纳税人',
  telCount: 0,
  usednames: [
    {
      orgType: '工商曾用名',
      useFrom: '1995-02-10',
      useTo: '2002-06-11',
      used_name: '深圳市比亚迪实业有限公司',
    },
  ],
  xxIndustryList: {
    '0': [
      {
        industryCode: '142614862',
        industryName: '新能源汽车产业',
        type: 'xx',
        windId: '1173319566',
      },
      {
        industryCode: '142614620',
        industryName: '新能源汽车整车制造',
        type: 'xx',
        windId: '1173319566',
      },
      {
        industryCode: '142614863',
        industryName: '新能源汽车整车制造',
        type: 'xx',
        windId: '1173319566',
      },
    ],
  },
}
