import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoHK: CorpBasicInfo = {
  anotherNames: null,
  areaCode: '030408',
  biz_reg_no: 'F0024367',
  bus_address: '北京市海淀区安宁庄路小米科技园',
  cancel_date: '',
  configType: 'HK',
  corp_id: '1207343546',
  corp_name: 'Xiaomi Corporation',
  corp_old_id: 'fp7kjp726I',
  corp_type: '註冊非香港公司',
  corp_type_id: 298060000,
  credit_code: '69365572',
  domainCount: 0,
  eng_name: '',
  formerNameList: [],
  gbIndustryList: [],
  issue_date: '',
  mailCount: 0,
  org_code: '69365572',
  overseasCorpIndustryList: [],
  province: '香港特别行政区',
  reg_address: 'PO Box 309, Ugland House, Grand Cayman, KY1-1104, Cayman Islands',
  reg_date: '2010-01-05',
  remark: '上市公司',
  revokeDate: '',
  seIndustriesCount: 0,
  state: '仍註冊',
  telCount: 0,
  usednames: [],
  xxIndustryList: null,
}
