import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoOE: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030103',
  biz_reg_no: '320829000024710',
  bus_address: '洪泽县高良涧镇东风路94号',
  business_scope: '许可经营范围:一般经营范围:服装零售。',
  cancel_date: '',
  configType: 'OE',
  corp_id: '1054443718',
  corp_name: '洪泽县新世界购物中心东风路分店',
  corp_old_id: '',
  corp_type: '个人独资企业分支机构',
  corp_type_id: 298010000,
  credit_code: '',
  domainCount: 0,
  employee_num: 0,
  eng_name: 'Dongfeng Road branch of Hongze County New World Shopping Center',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'F',
      industryName: '批发和零售业',
      type: 'gb',
      windId: '1054443718',
    },
    {
      industryCode: 'F52',
      industryName: '零售业',
      type: 'gb',
      windId: '1054443718',
    },
  ],
  industryGbFold: '批发和零售业-零售业',
  industryWindFold: '日常消费-日常消费零售',
  industryWindFoldCode: '3010',
  issue_date: '2023-01-10',
  legal_person_id: 'W00000000000000TNGN0',
  legal_person_name: '葛兵',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2006-11-03',
  oper_period_end: '',
  org_code: '',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '洪泽县高良涧镇东风路94号',
  province: '江苏省',
  reg_address: '洪泽县高良涧镇东风路94号',
  reg_authority: '淮安市洪泽区行政审批局',
  reg_date: '2006-11-03',
  reg_unit: '',
  revokeDate: '20230110',
  revokeOrCancelDate: '20230110',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '吊销,未注销',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
