export { translateDataWithApi } from './apiAdapter'
export type { TranslateServiceOptions } from './apiAdapter'
export { detectChinese, detectEnglish, getDetectorByLocale, hasTranslatableContent } from './languageDetector'
export type { TextDetector } from './languageDetector'
export type { TranslateResult } from './types'
