import { IBuryPointConfig } from '@/api/pointBuried/config/type.ts'
import { PageModuleEnum } from '@/api/pointBuried/module.ts'

export const frontAndSearchBuryList: IBuryPointConfig[] = [
  {
    moduleId: 922602101021,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-点击查集团TAB',
    opActive: 'click',
  },
  {
    moduleId: 922602101022,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-点击查司法TAB',
    opActive: 'click',
  },
  {
    moduleId: 922602101023,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-功能推荐-点击',
    opActive: 'click',
  },
  {
    moduleId: 922602101024,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-功能推荐-换一换',
    opActive: 'switch',
  },
  {
    moduleId: 922602101025,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-企业动态-滚动查看',
    opActive: 'scroll',
  },
  {
    moduleId: 922602101026,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-企业动态-类型筛选',
    opActive: 'filter',
  },
  {
    moduleId: 922602101027,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-企业动态-时间筛选',
    opActive: 'filter',
  },
  {
    moduleId: 922602101028,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-HOVER全部功能',
    opActive: 'hover',
  },
  {
    moduleId: 922602101029,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-全部功能-选择任一功能',
    opActive: 'select',
  },
  {
    moduleId: 922602101030,
    pageId: PageModuleEnum.HOME_PAGE,
    pageName: 'PC-首页',
    describe: '首页-左上角查看征信备案公告',
    opActive: 'view',
  },
  {
    moduleId: 922602101031,
    pageId: PageModuleEnum.SEARCH,
    pageName: 'PC-搜索',
    describe: '企业搜索结果页-清空最近浏览企业',
    opActive: 'clear',
  },
  {
    moduleId: 922602101032,
    pageId: PageModuleEnum.SEARCH,
    pageName: 'PC-搜索',
    describe: '企业搜索结果页-搜索结果导出',
    opActive: 'export',
  },
  {
    moduleId: 922602101033,
    pageId: PageModuleEnum.SEARCH,
    pageName: 'PC-搜索',
    describe: '人物搜索结果页-筛选省份地区',
    opActive: 'filter',
  },
  {
    moduleId: 922602101034,
    pageId: PageModuleEnum.SEARCH,
    pageName: 'PC-搜索',
    describe: '人物搜索结果页-筛选国标行业',
    opActive: 'filter',
  },
  {
    moduleId: 922602101035,
    pageId: PageModuleEnum.SEARCH,
    pageName: 'PC-搜索',
    describe: '海外企业搜索结果页-国家筛选',
    opActive: 'filter',
  },
]
