import { IBuryPointConfig } from '@/api/pointBuried/config/type.ts'

import { PageModuleEnum } from '@/api/pointBuried/module.ts'

const pageName = 'PC-通用'

export const userBuryConfigList: IBuryPointConfig[] = [
  {
    moduleId: 922602101046,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的账号',
    opActive: 'click',
  },
  {
    moduleId: 922602101047,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的账号-点击网址',
    opActive: 'click',
  },
  {
    moduleId: 922602101048,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏',
    opActive: 'click',
  },
  {
    moduleId: 922602101049,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-新建分组',
    opActive: 'click',
  },
  {
    moduleId: 922602101050,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-删除分组',
    opActive: 'click',
  },
  {
    moduleId: 922602101051,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-编辑分组',
    opActive: 'click',
  },
  {
    moduleId: 922602101052,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-清空收藏',
    opActive: 'click',
  },
  {
    moduleId: 922602101053,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-取消收藏',
    opActive: 'click',
  },
  {
    moduleId: 922602101054,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-移动到',
    opActive: 'click',
  },
  {
    moduleId: 922602101055,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-复制到',
    opActive: 'click',
  },
  {
    moduleId: 922602101056,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-批量导入',
    opActive: 'click',
  },
  {
    moduleId: 922602101057,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-搜索企业',
    opActive: 'click',
  },
  {
    moduleId: 922602101058,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的收藏-切换动态',
    opActive: 'click',
  },
  {
    moduleId: 922602101059,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的数据',
    opActive: 'click',
  },
  {
    moduleId: 922602101060,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-我的订单',
    opActive: 'click',
  },
  {
    moduleId: 922602101061,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-用户协议',
    opActive: 'click',
  },
  {
    moduleId: 922602101062,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-隐私政策',
    opActive: 'click',
  },
  {
    moduleId: 922602101064,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-免责声明',
    opActive: 'click',
  },
  {
    moduleId: 922602101065,
    pageId: PageModuleEnum.GENERAL,
    pageName,
    describe: '用户中心-联系我们',
    opActive: 'click',
  },
]
