import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoFCP: CorpBasicInfo = {
  abbreviation: '蜂御医',
  anotherNames: null,
  areaCode: '030105',
  biz_reg_no: '330702NB000001X',
  bus_address: '浙江省金华市婺城区胜利北街气象巷5号',
  business_scope: '蜂产品(蜂蜜)加工(凭有效许可证件经营)。（依法须经批准的项目，经相关部门批准后方可开展经营活动）',
  cancel_date: '',
  configType: 'FCP',
  corp_id: '1063144164',
  corp_name: '金华市蜂御医养蜂专业合作社蜂产品加工厂',
  corp_old_id: '',
  corp_type: '农民专业合作社分支机构',
  corp_type_id: 298020000,
  credit_code: '933307026702886050',
  domainCount: 0,
  eng_name: 'The bee product processing plant of Jinhua Fengyu Medical Beekeeping Professional Cooperative',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'C',
      industryName: '制造业',
      type: 'gb',
      windId: '1063144164',
    },
    {
      industryCode: 'C13',
      industryName: '农副食品加工业',
      type: 'gb',
      windId: '1063144164',
    },
  ],
  industryGbFold: '制造业-农副食品加工业',
  industryWindFold: '日常消费-食品饮料-食品',
  industryWindFoldCode: '302020',
  issue_date: '2019-10-25',
  legal_person_id: '185CE228A0C624DC7C7BA7EECCE70F32',
  legal_person_name: '郑北鹿',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2007-12-27',
  oper_period_end: '',
  org_code: '933307026702886050',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '',
  province: '浙江省',
  reg_address: '浙江省金华市婺城区胜利北街气象巷5号',
  reg_authority: '金华市婺城区市场监督管理局',
  reg_date: '2007-12-27',
  reg_unit: '',
  revokeDate: '',
  revokeOrCancelDate: '',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '存续',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
