import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoIIP: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030405',
  biz_reg_no: '442000601070903',
  bus_address: '中山市东升镇',
  business_scope: '加工：电器开关、电子元件、电子仪器、电子仪表。',
  cancel_date: '',
  configType: 'IIP',
  corp_id: '1102955966',
  corp_name: '中山市东升镇迪比隆电气厂',
  corp_type: '个体工商户',
  corp_type_id: 298030000,
  credit_code: '92442000L00176148E',
  domainCount: 0,
  employee_num: 2,
  endowment_num: 1,
  eng_name: '',
  formerNameList: [],
  gbIndustryList: [
    {
      industryCode: 'C',
      industryName: '制造业',
      type: 'gb',
      windId: '1102955966',
    },
    {
      industryCode: 'C39',
      industryName: '计算机、通信和其他电子设备制造业',
      type: 'gb',
      windId: '1102955966',
    },
    {
      industryCode: 'C397',
      industryName: '电子器件制造',
      type: 'gb',
      windId: '1102955966',
    },
    {
      industryCode: 'C3979',
      industryName: '其他电子器件制造',
      type: 'gb',
      windId: '1102955966',
    },
  ],
  industryGbFold: '制造业-计算机、通信和其他电子设备制造业-电子器件制造-其他电子器件制造',
  industryWindFold: '工业-资本货物',
  industryWindFoldCode: '2010',
  issue_date: '2017-06-27',
  legal_person_id: 'W00000000000000S6HLH',
  legal_person_name: '吴洪彬',
  legal_person_type: 'person',
  mailCount: 0,
  oper_period_begin: '2001-04-16',
  oper_period_end: '',
  org_code: '92442000L00176148E',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '',
  province: '广东省',
  reg_address: '中山市东升镇兆隆村六队',
  reg_authority: '中山市市场监督管理局',
  reg_date: '2001-04-16',
  reg_unit: '',
  revokeDate: '',
  revokeOrCancelDate: '',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '存续',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
