import { CorpBasicInfo } from '@/api/corp/info/basicInfo'

export const mockCorpBasicInfoTW: CorpBasicInfo = {
  abbreviation: '',
  anotherNames: null,
  areaCode: '030407',
  biz_reg_no: '38849413',
  bus_address: '',
  business_scope: '',
  cancel_date: '',
  configType: '00',
  corp_id: '1250975407',
  corp_name: '小米社',
  corp_old_id: '',
  corp_type: '商業',
  corp_type_id: 298067001,
  credit_code: '',
  domainCount: 0,
  eng_name: 'Xiaomi Club',
  formerNameList: [],
  gbIndustryList: [],
  industryGbFold: '',
  industryWindFold: '',
  industryWindFoldCode: '',
  issue_date: '2022-10-19',
  legal_person_id: '325686443',
  legal_person_name: '張峻維',
  legal_person_type: '',
  mailCount: 0,
  oper_period_begin: '',
  oper_period_end: '',
  org_code: '',
  overseasCorpIndustryList: [],
  paid_in_capital_currency: '',
  postal_address: '',
  province: '台湾省',
  reg_address: '臺中市北屯區三光里九龍街１６７號',
  reg_authority: '臺中市政府',
  reg_capital: 90,
  reg_date: '2014-08-13',
  reg_unit: 'TWD',
  revokeDate: '',
  revokeOrCancelDate: '',
  scale: '',
  scaleAll: '',
  seIndustriesCount: 0,
  state: '核准設立',
  taxIdNo: '',
  taxQualiType: '',
  telCount: 0,
  usednames: [],
  xxIndustryList: {},
}
