import { IBuryPointConfig } from '@/api/pointBuried/config/type'

import { PageModuleEnum } from '@/api/pointBuried/module.ts'

export const corpReportBuryList: IBuryPointConfig[] = [
  {
    moduleId: 922602101008,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业深度信用报告-点击查看样例',
    opActive: 'click',
  },
  {
    moduleId: 922602101009,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业深度信用报告-点击下载',
    opActive: 'click',
  },
  {
    moduleId: 922602101010,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '尽职调查报告-点击在线编辑',
    opActive: 'click',
  },
  {
    moduleId: 922602101011,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '股权穿透报告-6层-点击查看样例',
    opActive: 'click',
  },
  {
    moduleId: 922602101012,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '股权穿透报告-6层-点击下载报告',
    opActive: 'click',
  },
  {
    moduleId: 922602101013,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '股权穿透分析报告-点击查看样例',
    opActive: 'click',
  },
  {
    moduleId: 922602101014,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '股权穿透分析报告-点击下载报告',
    opActive: 'click',
  },
  {
    moduleId: 922602101015,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '投资穿透报告Excel版-点击查看样例',
    opActive: 'click',
  },
  {
    moduleId: 922602101016,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '投资穿透报告Excel版-点击下载报告',
    opActive: 'click',
  },
  {
    moduleId: 922602101017,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '关联方认定报告-点击查看样例',
    opActive: 'click',
  },
  {
    moduleId: 922602101018,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '关联方认定报告-点击下载报告',
    opActive: 'click',
  },
  {
    moduleId: 922602101019,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '关联方认定报告-点击切换规则',
    opActive: 'click',
  },
  {
    moduleId: 922602101126,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-点击“详情”或侧边栏查看科创分',
    opActive: 'click',
  },
  {
    moduleId: 922602101127,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-下载科创分报告',
    opActive: 'click',
  },
  {
    moduleId: 922602101128,
    pageId: PageModuleEnum.COMPANY_DETAILS,
    pageName: '企业详情',
    describe: '企业详情-下载科创分样例报告',
    opActive: 'click',
  },
]
